package libreria_sibilia.codicefiscale.document ;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_G extends HashMap<String, String> {

    public CitiesCodes_G(){
        this.put("GABBIONETA BINANUOVA","D834");
        this.put("GABIANO","D835");
        this.put("GABICCE MARE","D836");
        this.put("GABY","D839");
        this.put("GADESCO PIEVE DELMONA","D841");
        this.put("GADONI","D842");
        this.put("GAETA","D843");
        this.put("GAGGI","D844");
        this.put("GAGGIANO","D845");
        this.put("GAGGIO MONTANO","D847");
        this.put("GAGLIANICO","D848");
        this.put("GAGLIANO ATERNO","D850");
        this.put("GAGLIANO CASTELFERRATO","D849");
        this.put("GAGLIANO DEL CAPO","D851");
        this.put("GAGLIATO","D852");
        this.put("GAGLIOLE","D853");
        this.put("GAIARINE","D854");
        this.put("GAIBA","D855");
        this.put("GAIOLA","D856");
        this.put("GAIOLE IN CHIANTI","D858");
        this.put("GAIRO","D859");
        this.put("GAIS .GAIS.","D860");
        this.put("GALATI MAMERTINO","D861");
        this.put("GALATINA","D862");
        this.put("GALATONE","D863");
        this.put("GALATRO","D864");
        this.put("GALBIATE","D865");
        this.put("GALEATA","D867");
        this.put("GALGAGNANO","D868");
        this.put("GALLARATE","D869");
        this.put("GALLESE","D870");
        this.put("GALLIATE","D872");
        this.put("GALLIATE LOMBARDO","D871");
        this.put("GALLIAVOLA","D873");
        this.put("GALLICANO","D874");
        this.put("GALLICANO NEL LAZIO","D875");
        this.put("GALLICCHIO","D876");
        this.put("GALLIERA","D878");
        this.put("GALLIERA VENETA","D879");
        this.put("GALLINARO","D881");
        this.put("GALLIO","D882");
        this.put("GALLIPOLI","D883");
        this.put("GALLO MATESE","D884");
        this.put("GALLODORO","D885");
        this.put("GALLUCCIO","D886");
        this.put("GALTELLI'","D888");
        this.put("GALZIGNANO TERME","D889");
        this.put("GAMALERO","D890");
        this.put("GAMBARA","D891");
        this.put("GAMBARANA","D892");
        this.put("GAMBASCA","D894");
        this.put("GAMBASSI TERME","D895");
        this.put("GAMBATESA","D896");
        this.put("GAMBELLARA","D897");
        this.put("GAMBERALE","D898");
        this.put("GAMBETTOLA","D899");
        this.put("GAMBOLO'","D901");
        this.put("GAMBUGLIANO","D902");
        this.put("GANDELLINO","D903");
        this.put("GANDINO","D905");
        this.put("GANDOSSO","D906");
        this.put("GANGI","D907");
        this.put("GARAGUSO","D909");
        this.put("GARBAGNA","D910");
        this.put("GARBAGNA NOVARESE","D911");
        this.put("GARBAGNATE MILANESE","D912");
        this.put("GARBAGNATE MONASTERO","D913");
        this.put("GARDA","D915");
        this.put("GARDONE RIVIERA","D917");
        this.put("GARDONE VAL TROMPIA","D918");
        this.put("GARESSIO","D920");
        this.put("GARGALLO","D921");
        this.put("GARGAZZONE .GARGAZON.","D923");
        this.put("GARGNANO","D924");
        this.put("GARLASCO","D925");
        this.put("GARLATE","D926");
        this.put("GARLENDA","D927");
        this.put("GARNIGA TERME","D928");
        this.put("GARZENO","D930");
        this.put("GARZIGLIANA","D931");
        this.put("GASPERINA","D932");
        this.put("GASSINO TORINESE","D933");
        this.put("GATTATICO","D934");
        this.put("GATTEO","D935");
        this.put("GATTICO","D937");
        this.put("GATTICO VERUNO","M416");
        this.put("GATTINARA","D938");
        this.put("GAVARDO","D940");
        this.put("GAVAZZANA","D941");
        this.put("GAVELLO","D942");
        this.put("GAVERINA TERME","D943");
        this.put("GAVI","D944");
        this.put("GAVIGNANO","D945");
        this.put("GAVIRATE","D946");
        this.put("GAVOI","D947");
        this.put("GAVORRANO","D948");
        this.put("GAZOLDO DEGLI IPPOLITI","D949");
        this.put("GAZZADA SCHIANNO","D951");
        this.put("GAZZANIGA","D952");
        this.put("GAZZO","D956");
        this.put("GAZZO VERONESE","D957");
        this.put("GAZZOLA","D958");
        this.put("GAZZUOLO","D959");
        this.put("GELA","D960");
        this.put("GEMMANO","D961");
        this.put("GEMONA DEL FRIULI","D962");
        this.put("GEMONIO","D963");
        this.put("GENAZZANO","D964");
        this.put("GENGA","D965");
        this.put("GENIVOLTA","D966");
        this.put("GENOLA","D967");
        this.put("GENONI","D968");
        this.put("GENOVA","D969");
        this.put("GENURI","D970");
        this.put("GENZANO DI LUCANIA","D971");
        this.put("GENZANO DI ROMA","D972");
        this.put("GENZONE","D973");
        this.put("GERA LARIO","D974");
        this.put("GERACE","D975");
        this.put("GERACI SICULO","D977");
        this.put("GERANO","D978");
        this.put("GERENZAGO","D980");
        this.put("GERENZANO","D981");
        this.put("GERGEI","D982");
        this.put("GERMAGNANO","D983");
        this.put("GERMAGNO","D984");
        this.put("GERMASINO","D986");
        this.put("GERMIGNAGA","D987");
        this.put("GEROCARNE","D988");
        this.put("GEROLA ALTA","D990");
        this.put("GEROSA","D991");
        this.put("GERRE DE' CAPRIOLI","D993");
        this.put("GESICO","D994");
        this.put("GESSATE","D995");
        this.put("GESSOPALENA","D996");
        this.put("GESTURI","D997");
        this.put("GESUALDO","D998");
        this.put("GHEDI","D999");
        this.put("GHEMME","E001");
        this.put("GHIFFA","E003");
        this.put("GHILARZA","E004");
        this.put("GHISALBA","E006");
        this.put("GHISLARENGO","E007");
        this.put("GIACCIANO CON BARUCHELLA","E008");
        this.put("GIAGLIONE","E009");
        this.put("GIANICO","E010");
        this.put("GIANO DELL'UMBRIA","E012");
        this.put("GIANO VETUSTO","E011");
        this.put("GIARDINELLO","E013");
        this.put("GIARDINI NAXOS","E014");
        this.put("GIAROLE","E015");
        this.put("GIARRATANA","E016");
        this.put("GIARRE","E017");
        this.put("GIAVE","E019");
        this.put("GIAVENO","E020");
        this.put("GIAVERA DEL MONTELLO","E021");
        this.put("GIBA","E022");
        this.put("GIBELLINA","E023");
        this.put("GIFFLENGA","E024");
        this.put("GIFFONE","E025");
        this.put("GIFFONI SEI CASALI","E026");
        this.put("GIFFONI VALLE PIANA","E027");
        this.put("GIGNESE","E028");
        this.put("GIGNOD","E029");
        this.put("GILDONE","E030");
        this.put("GIMIGLIANO","E031");
        this.put("GINESTRA","E033");
        this.put("GINESTRA DEGLI SCHIAVONI","E034");
        this.put("GINOSA","E036");
        this.put("GIOI","E037");
        this.put("GIOIA DEI MARSI","E040");
        this.put("GIOIA DEL COLLE","E038");
        this.put("GIOIA SANNITICA","E039");
        this.put("GIOIA TAURO","E041");
        this.put("GIOIOSA IONICA","E044");
        this.put("GIOIOSA MAREA","E043");
        this.put("GIOVE","E045");
        this.put("GIOVINAZZO","E047");
        this.put("GIOVO","E048");
        this.put("GIRASOLE","E049");
        this.put("GIRIFALCO","E050");
        this.put("GIRONICO","E051");
        this.put("GISSI","E052");
        this.put("GIUGGIANELLO","E053");
        this.put("GIUGLIANO IN CAMPANIA","E054");
        this.put("GIULIANA","E055");
        this.put("GIULIANO DI ROMA","E057");
        this.put("GIULIANO TEATINO","E056");
        this.put("GIULIANOVA","E058");
        this.put("GIUNCUGNANO","E059");
        this.put("GIUNGANO","E060");
        this.put("GIURDIGNANO","E061");
        this.put("GIUSSAGO","E062");
        this.put("GIUSSANO","E063");
        this.put("GIUSTENICE","E064");
        this.put("GIUSTINO","E065");
        this.put("GIUSVALLA","E066");
        this.put("GIVOLETTO","E067");
        this.put("GIZZERIA","E068");
        this.put("GLORENZA .GLURNS.","E069");
        this.put("GODEGA DI SANT'URBANO","E071");
        this.put("GODIASCO SALICE TERME","E072");
        this.put("GODRANO","E074");
        this.put("GOITO","E078");
        this.put("GOLASECCA","E079");
        this.put("GOLFERENZO","E081");
        this.put("GOLFO ARANCI","M274");
        this.put("GOMBITO","E082");
        this.put("GONARS","E083");
        this.put("GONI","E084");
        this.put("GONNESA","E086");
        this.put("GONNOSCODINA","E087");
        this.put("GONNOSFANADIGA","E085");
        this.put("GONNOSNO'","D585");
        this.put("GONNOSTRAMATZA","E088");
        this.put("GONZAGA","E089");
        this.put("GORDONA","E090");
        this.put("GORGA","E091");
        this.put("GORGO AL MONTICANO","E092");
        this.put("GORGOGLIONE","E093");
        this.put("GORGONZOLA","E094");
        this.put("GORIANO SICOLI","E096");
        this.put("GORIZIA","E098");
        this.put("GORLA MAGGIORE","E101");
        this.put("GORLA MINORE","E102");
        this.put("GORLAGO","E100");
        this.put("GORLE","E103");
        this.put("GORNATE OLONA","E104");
        this.put("GORNO","E106");
        this.put("GORO","E107");
        this.put("GORRETO","E109");
        this.put("GORZEGNO","E111");
        this.put("GOSALDO","E113");
        this.put("GOSSOLENGO","E114");
        this.put("GOTTASECCA","E115");
        this.put("GOTTOLENGO","E116");
        this.put("GOVONE","E118");
        this.put("GOZZANO","E120");
        this.put("GRADARA","E122");
        this.put("GRADISCA D'ISONZO","E124");
        this.put("GRADO","E125");
        this.put("GRADOLI","E126");
        this.put("GRAFFIGNANA","E127");
        this.put("GRAFFIGNANO","E128");
        this.put("GRAGLIA","E130");
        this.put("GRAGNANO","E131");
        this.put("GRAGNANO TREBBIENSE","E132");
        this.put("GRAMMICHELE","E133");
        this.put("GRANA MONFERRATO","E134");
        this.put("GRANAGLIONE","E135");
        this.put("GRANAROLO DELL'EMILIA","E136");
        this.put("GRANCONA","E138");
        this.put("GRANDATE","E139");
        this.put("GRANDOLA ED UNITI","E141");
        this.put("GRANITI","E142");
        this.put("GRANOZZO CON MONTICELLO","E143");
        this.put("GRANTOLA","E144");
        this.put("GRANTORTO","E145");
        this.put("GRANZE","E146");
        this.put("GRASSANO","E147");
        this.put("GRASSOBBIO","E148");
        this.put("GRATTERI","E149");
        this.put("GRAUNO","E150");
        this.put("GRAVEDONA","E151");
        this.put("GRAVEDONA ED UNITI","M315");
        this.put("GRAVELLONA LOMELLINA","E152");
        this.put("GRAVELLONA TOCE","E153");
        this.put("GRAVERE","E154");
        this.put("GRAVINA DI CATANIA","E156");
        this.put("GRAVINA IN PUGLIA","E155");
        this.put("GRAZZANISE","E158");
        this.put("GRAZZANO BADOGLIO","E159");
        this.put("GRECCIO","E160");
        this.put("GRECI","E161");
        this.put("GREGGIO","E163");
        this.put("GREMIASCO","E164");
        this.put("GRESSAN","E165");
        this.put("GRESSONEY LA TRINITE'","E167");
        this.put("GRESSONEY SAINT JEAN","E168");
        this.put("GREVE IN CHIANTI","E169");
        this.put("GREZZAGO","E170");
        this.put("GREZZANA","E171");
        this.put("GRIANTE","E172");
        this.put("GRICIGNANO DI AVERSA","E173");
        this.put("GRIGNASCO","E177");
        this.put("GRIGNO","E178");
        this.put("GRIMACCO","E179");
        this.put("GRIMALDI","E180");
        this.put("GRINZANE CAVOUR","E182");
        this.put("GRISIGNANO DI ZOCCO","E184");
        this.put("GRISOLIA","E185");
        this.put("GRIZZANA MORANDI","E187");
        this.put("GROGNARDO","E188");
        this.put("GROMO","E189");
        this.put("GRONDONA","E191");
        this.put("GRONE","E192");
        this.put("GRONTARDO","E193");
        this.put("GROPELLO CAIROLI","E195");
        this.put("GROPPARELLO","E196");
        this.put("GROSCAVALLO","E199");
        this.put("GROSIO","E200");
        this.put("GROSOTTO","E201");
        this.put("GROSSETO","E202");
        this.put("GROSSO","E203");
        this.put("GROTTAFERRATA","E204");
        this.put("GROTTAGLIE","E205");
        this.put("GROTTAMINARDA","E206");
        this.put("GROTTAMMARE","E207");
        this.put("GROTTAZZOLINA","E208");
        this.put("GROTTE","E209");
        this.put("GROTTE DI CASTRO","E210");
        this.put("GROTTERIA","E212");
        this.put("GROTTOLE","E213");
        this.put("GROTTOLELLA","E214");
        this.put("GRUARO","E215");
        this.put("GRUGLIASCO","E216");
        this.put("GRUMELLO CREMONESE ED UNITI","E217");
        this.put("GRUMELLO DEL MONTE","E219");
        this.put("GRUMENTO NOVA","E221");
        this.put("GRUMES","E222");
        this.put("GRUMO APPULA","E223");
        this.put("GRUMO NEVANO","E224");
        this.put("GRUMOLO DELLE ABBADESSE","E226");
        this.put("GUAGNANO","E227");
        this.put("GUALDO","E228");
        this.put("GUALDO CATTANEO","E229");
        this.put("GUALDO TADINO","E230");
        this.put("GUALTIERI","E232");
        this.put("GUALTIERI SICAMINO'","E233");
        this.put("GUAMAGGIORE","E234");
        this.put("GUANZATE","E235");
        this.put("GUARCINO","E236");
        this.put("GUARDA VENETA","E240");
        this.put("GUARDABOSONE","E237");
        this.put("GUARDAMIGLIO","E238");
        this.put("GUARDAVALLE","E239");
        this.put("GUARDEA","E241");
        this.put("GUARDIA LOMBARDI","E245");
        this.put("GUARDIA PERTICARA","E246");
        this.put("GUARDIA PIEMONTESE","E242");
        this.put("GUARDIA SANFRAMONDI","E249");
        this.put("GUARDIAGRELE","E243");
        this.put("GUARDIALFIERA","E244");
        this.put("GUARDIAREGIA","E248");
        this.put("GUARDISTALLO","E250");
        this.put("GUARENE","E251");
        this.put("GUASILA","E252");
        this.put("GUASTALLA","E253");
        this.put("GUAZZORA","E255");
        this.put("GUBBIO","E256");
        this.put("GUDO VISCONTI","E258");
        this.put("GUGLIONESI","E259");
        this.put("GUIDIZZOLO","E261");
        this.put("GUIDONIA MONTECELIO","E263");
        this.put("GUIGLIA","E264");
        this.put("GUILMI","E266");
        this.put("GURRO","E269");
        this.put("GUSPINI","E270");
        this.put("GUSSAGO","E271");
        this.put("GUSSOLA","E272");
        this.put("HONE","E273");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
