package libreria_sibilia.codicefiscale.document ;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_A extends HashMap<String, String> {
    public CitiesCodes_A(){
        this.put("ABANO TERME","A001");
        this.put("ABBADIA CERRETO","A004");
        this.put("ABBADIA LARIANA","A005");
        this.put("ABBADIA SAN SALVATORE","A006");
        this.put("ABBASANTA","A007");
        this.put("ABBATEGGIO","A008");
        this.put("ABBIATEGRASSO","A010");
        this.put("ABETONE","A012");
        this.put("ABETONE CUTIGLIANO","M376");
        this.put("ABRIOLA","A013");
        this.put("ACATE","A014");
        this.put("ACCADIA","A015");
        this.put("ACCEGLIO","A016");
        this.put("ACCETTURA","A017");
        this.put("ACCIANO","A018");
        this.put("ACCUMOLI","A019");
        this.put("ACERENZA","A020");
        this.put("ACERNO","A023");
        this.put("ACERRA","A024");
        this.put("ACI BONACCORSI","A025");
        this.put("ACI CASTELLO","A026");
        this.put("ACI CATENA","A027");
        this.put("ACI SANT'ANTONIO","A029");
        this.put("ACIREALE","A028");
        this.put("ACQUACANINA","A031");
        this.put("ACQUAFONDATA","A032");
        this.put("ACQUAFORMOSA","A033");
        this.put("ACQUAFREDDA","A034");
        this.put("ACQUALAGNA","A035");
        this.put("ACQUANEGRA CREMONESE","A039");
        this.put("ACQUANEGRA SUL CHIESE","A038");
        this.put("ACQUAPENDENTE","A040");
        this.put("ACQUAPPESA","A041");
        this.put("ACQUARICA DEL CAPO","A042");
        this.put("ACQUARO","A043");
        this.put("ACQUASANTA TERME","A044");
        this.put("ACQUASPARTA","A045");
        this.put("ACQUAVIVA COLLECROCE","A050");
        this.put("ACQUAVIVA DELLE FONTI","A048");
        this.put("ACQUAVIVA D'ISERNIA","A051");
        this.put("ACQUAVIVA PICENA","A047");
        this.put("ACQUAVIVA PLATANI","A049");
        this.put("ACQUEDOLCI","M211");
        this.put("ACQUI TERME","A052");
        this.put("ACRI","A053");
        this.put("ACUTO","A054");
        this.put("ADELFIA","A055");
        this.put("ADRANO","A056");
        this.put("ADRARA SAN MARTINO","A057");
        this.put("ADRARA SAN ROCCO","A058");
        this.put("ADRIA","A059");
        this.put("ADRO","A060");
        this.put("AFFI","A061");
        this.put("AFFILE","A062");
        this.put("AFRAGOLA","A064");
        this.put("AFRICO","A065");
        this.put("AGAZZANO","A067");
        this.put("AGEROLA","A068");
        this.put("AGGIUS","A069");
        this.put("AGIRA","A070");
        this.put("AGLIANA","A071");
        this.put("AGLIANO TERME","A072");
        this.put("AGLIE'","A074");
        this.put("AGLIENTU","H848");
        this.put("AGNA","A075");
        this.put("AGNADELLO","A076");
        this.put("AGNANA CALABRA","A077");
        this.put("AGNONE","A080");
        this.put("AGNOSINE","A082");
        this.put("AGORDO","A083");
        this.put("AGOSTA","A084");
        this.put("AGRA","A085");
        this.put("AGRATE BRIANZA","A087");
        this.put("AGRATE CONTURBIA","A088");
        this.put("AGRIGENTO","A089");
        this.put("AGROPOLI","A091");
        this.put("AGUGLIANO","A092");
        this.put("AGUGLIARO","A093");
        this.put("AICURZIO","A096");
        this.put("AIDOMAGGIORE","A097");
        this.put("AIDONE","A098");
        this.put("AIELLI","A100");
        this.put("AIELLO CALABRO","A102");
        this.put("AIELLO DEL FRIULI","A103");
        this.put("AIELLO DEL SABATO","A101");
        this.put("AIETA","A105");
        this.put("AILANO","A106");
        this.put("AILOCHE","A107");
        this.put("AIRASCA","A109");
        this.put("AIROLA","A110");
        this.put("AIROLE","A111");
        this.put("AIRUNO","A112");
        this.put("AISONE","A113");
        this.put("ALA","A116");
        this.put("ALA' DEI SARDI","A115");
        this.put("ALA DI STURA","A117");
        this.put("ALAGNA","A118");
        this.put("ALAGNA VALSESIA","A119");
        this.put("ALANNO","A120");
        this.put("ALANO DI PIAVE","A121");
        this.put("ALASSIO","A122");
        this.put("ALATRI","A123");
        this.put("ALBA","A124");
        this.put("ALBA ADRIATICA","A125");
        this.put("ALBAGIARA","A126");
        this.put("ALBAIRATE","A127");
        this.put("ALBANELLA","A128");
        this.put("ALBANO DI LUCANIA","A131");
        this.put("ALBANO LAZIALE","A132");
        this.put("ALBANO SANT'ALESSANDRO","A129");
        this.put("ALBANO VERCELLESE","A130");
        this.put("ALBAREDO ARNABOLDI","A134");
        this.put("ALBAREDO D'ADIGE","A137");
        this.put("ALBAREDO PER SAN MARCO","A135");
        this.put("ALBARETO","A138");
        this.put("ALBARETTO DELLA TORRE","A139");
        this.put("ALBAVILLA","A143");
        this.put("ALBENGA","A145");
        this.put("ALBERA LIGURE","A146");
        this.put("ALBEROBELLO","A149");
        this.put("ALBERONA","A150");
        this.put("ALBESE CON CASSANO","A153");
        this.put("ALBETTONE","A154");
        this.put("ALBI","A155");
        this.put("ALBIANO","A158");
        this.put("ALBIANO D'IVREA","A157");
        this.put("ALBIATE","A159");
        this.put("ALBIDONA","A160");
        this.put("ALBIGNASEGO","A161");
        this.put("ALBINEA","A162");
        this.put("ALBINO","A163");
        this.put("ALBIOLO","A164");
        this.put("ALBISOLA SUPERIORE","A166");
        this.put("ALBISSOLA MARINA","A165");
        this.put("ALBIZZATE","A167");
        this.put("ALBONESE","A171");
        this.put("ALBOSAGGIA","A172");
        this.put("ALBUGNANO","A173");
        this.put("ALBUZZANO","A175");
        this.put("ALCAMO","A176");
        this.put("ALCARA LI FUSI","A177");
        this.put("ALDENO","A178");
        this.put("ALDINO .ALDEIN.","A179");
        this.put("ALES","A180");
        this.put("ALESSANDRIA","A182");
        this.put("ALESSANDRIA DEL CARRETTO","A183");
        this.put("ALESSANDRIA DELLA ROCCA","A181");
        this.put("ALESSANO","A184");
        this.put("ALEZIO","A185");
        this.put("ALFANO","A186");
        this.put("ALFEDENA","A187");
        this.put("ALFIANELLO","A188");
        this.put("ALFIANO NATTA","A189");
        this.put("ALFONSINE","A191");
        this.put("ALGHERO","A192");
        this.put("ALGUA","A193");
        this.put("ALI'","A194");
        this.put("ALI' TERME","A201");
        this.put("ALIA","A195");
        this.put("ALIANO","A196");
        this.put("ALICE BEL COLLE","A197");
        this.put("ALICE CASTELLO","A198");
        this.put("ALICE SUPERIORE","A199");
        this.put("ALIFE","A200");
        this.put("ALIMENA","A202");
        this.put("ALIMINUSA","A203");
        this.put("ALLAI","A204");
        this.put("ALLEGHE","A206");
        this.put("ALLEIN","A205");
        this.put("ALLERONA","A207");
        this.put("ALLISTE","A208");
        this.put("ALLUMIERE","A210");
        this.put("ALLUVIONI CAMBIO'","A211");
        this.put("ALLUVIONI PIOVERA","M397");
        this.put("ALME'","A214");
        this.put("ALMENNO SAN BARTOLOMEO","A216");
        this.put("ALMENNO SAN SALVATORE","A217");
        this.put("ALMESE","A218");
        this.put("ALONTE","A220");
        this.put("ALPAGO","M375");
        this.put("ALPETTE","A221");
        this.put("ALPIGNANO","A222");
        this.put("ALSENO","A223");
        this.put("ALSERIO","A224");
        this.put("ALTA VAL TIDONE","M386");
        this.put("ALTA VALLE INTELVI","M383");
        this.put("ALTAMURA","A225");
        this.put("ALTARE","A226");
        this.put("ALTAVALLE","M349");
        this.put("ALTAVILLA IRPINA","A228");
        this.put("ALTAVILLA MILICIA","A229");
        this.put("ALTAVILLA MONFERRATO","A227");
        this.put("ALTAVILLA SILENTINA","A230");
        this.put("ALTAVILLA VICENTINA","A231");
        this.put("ALTIDONA","A233");
        this.put("ALTILIA","A234");
        this.put("ALTINO","A235");
        this.put("ALTISSIMO","A236");
        this.put("ALTIVOLE","A237");
        this.put("ALTO","A238");
        this.put("ALTO RENO TERME","M369");
        this.put("ALTO SERMENZA","M389");
        this.put("ALTOFONTE","A239");
        this.put("ALTOMONTE","A240");
        this.put("ALTOPASCIO","A241");
        this.put("ALTOPIANO DELLA VIGOLANA","M350");
        this.put("ALVIANO","A242");
        this.put("ALVIGNANO","A243");
        this.put("ALVITO","A244");
        this.put("ALZANO LOMBARDO","A246");
        this.put("ALZANO SCRIVIA","A245");
        this.put("ALZATE BRIANZA","A249");
        this.put("AMALFI","A251");
        this.put("AMANDOLA","A252");
        this.put("AMANTEA","A253");
        this.put("AMARO","A254");
        this.put("AMARONI","A255");
        this.put("AMASENO","A256");
        this.put("AMATO","A257");
        this.put("AMATRICE","A258");
        this.put("AMBIVERE","A259");
        this.put("AMBLAR","A260");
        this.put("AMBLAR DON","M351");
        this.put("AMEGLIA","A261");
        this.put("AMELIA","A262");
        this.put("AMENDOLARA","A263");
        this.put("AMENO","A264");
        this.put("AMOROSI","A265");
        this.put("AMPEZZO","A267");
        this.put("ANACAPRI","A268");
        this.put("ANAGNI","A269");
        this.put("ANCARANO","A270");
        this.put("ANCONA","A271");
        this.put("ANDALI","A272");
        this.put("ANDALO","A274");
        this.put("ANDALO VALTELLINO","A273");
        this.put("ANDEZENO","A275");
        this.put("ANDORA","A278");
        this.put("ANDORNO MICCA","A280");
        this.put("ANDRANO","A281");
        this.put("ANDRATE","A282");
        this.put("ANDREIS","A283");
        this.put("ANDRETTA","A284");
        this.put("ANDRIA","A285");
        this.put("ANDRIANO .ANDRIAN.","A286");
        this.put("ANELA","A287");
        this.put("ANFO","A288");
        this.put("ANGERA","A290");
        this.put("ANGHIARI","A291");
        this.put("ANGIARI","A292");
        this.put("ANGOLO TERME","A293");
        this.put("ANGRI","A294");
        this.put("ANGROGNA","A295");
        this.put("ANGUILLARA SABAZIA","A297");
        this.put("ANGUILLARA VENETA","A296");
        this.put("ANNICCO","A299");
        this.put("ANNONE DI BRIANZA","A301");
        this.put("ANNONE VENETO","A302");
        this.put("ANOIA","A303");
        this.put("ANTEGNATE","A304");
        this.put("ANTERIVO .ALTREI.","A306");
        this.put("ANTEY SAINT ANDRE'","A305");
        this.put("ANTICOLI CORRADO","A309");
        this.put("ANTIGNANO","A312");
        this.put("ANTILLO","A313");
        this.put("ANTONIMINA","A314");
        this.put("ANTRODOCO","A315");
        this.put("ANTRONA SCHIERANCO","A317");
        this.put("ANVERSA DEGLI ABRUZZI","A318");
        this.put("ANZANO DEL PARCO","A319");
        this.put("ANZANO DI PUGLIA","A320");
        this.put("ANZI","A321");
        this.put("ANZIO","A323");
        this.put("ANZOLA DELL'EMILIA","A324");
        this.put("ANZOLA D'OSSOLA","A325");
        this.put("AOSTA","A326");
        this.put("APECCHIO","A327");
        this.put("APICE","A328");
        this.put("APIRO","A329");
        this.put("APOLLOSA","A330");
        this.put("APPIANO GENTILE","A333");
        this.put("APPIANO SULLA STRADA DEL VINO .EPPAN AN DER.","A332");
        this.put("APPIGNANO","A334");
        this.put("APPIGNANO DEL TRONTO","A335");
        this.put("APRICA","A337");
        this.put("APRICALE","A338");
        this.put("APRICENA","A339");
        this.put("APRIGLIANO","A340");
        this.put("APRILIA","A341");
        this.put("AQUARA","A343");
        this.put("AQUILA D'ARROSCIA","A344");
        this.put("AQUILEIA","A346");
        this.put("AQUILONIA","A347");
        this.put("AQUINO","A348");
        this.put("ARADEO","A350");
        this.put("ARAGONA","A351");
        this.put("ARAMENGO","A352");
        this.put("ARBA","A354");
        this.put("ARBOREA","A357");
        this.put("ARBORIO","A358");
        this.put("ARBUS","A359");
        this.put("ARCADE","A360");
        this.put("ARCE","A363");
        this.put("ARCENE","A365");
        this.put("ARCEVIA","A366");
        this.put("ARCHI","A367");
        this.put("ARCIDOSSO","A369");
        this.put("ARCINAZZO ROMANO","A370");
        this.put("ARCISATE","A371");
        this.put("ARCO","A372");
        this.put("ARCOLA","A373");
        this.put("ARCOLE","A374");
        this.put("ARCONATE","A375");
        this.put("ARCORE","A376");
        this.put("ARCUGNANO","A377");
        this.put("ARDARA","A379");
        this.put("ARDAULI","A380");
        this.put("ARDEA","M213");
        this.put("ARDENNO","A382");
        this.put("ARDESIO","A383");
        this.put("ARDORE","A385");
        this.put("ARENA","A386");
        this.put("ARENA PO","A387");
        this.put("ARENZANO","A388");
        this.put("ARESE","A389");
        this.put("AREZZO","A390");
        this.put("ARGEGNO","A391");
        this.put("ARGELATO","A392");
        this.put("ARGENTA","A393");
        this.put("ARGENTERA","A394");
        this.put("ARGUELLO","A396");
        this.put("ARGUSTO","A397");
        this.put("ARI","A398");
        this.put("ARIANO IRPINO","A399");
        this.put("ARIANO NEL POLESINE","A400");
        this.put("ARICCIA","A401");
        this.put("ARIELLI","A402");
        this.put("ARIENZO","A403");
        this.put("ARIGNANO","A405");
        this.put("ARITZO","A407");
        this.put("ARIZZANO","A409");
        this.put("ARLENA DI CASTRO","A412");
        this.put("ARLUNO","A413");
        this.put("ARMENO","A414");
        this.put("ARMENTO","A415");
        this.put("ARMO","A418");
        this.put("ARMUNGIA","A419");
        this.put("ARNAD","A424");
        this.put("ARNARA","A421");
        this.put("ARNASCO","A422");
        this.put("ARNESANO","A425");
        this.put("AROLA","A427");
        this.put("ARONA","A429");
        this.put("AROSIO","A430");
        this.put("ARPAIA","A431");
        this.put("ARPAISE","A432");
        this.put("ARPINO","A433");
        this.put("ARQUA' PETRARCA","A434");
        this.put("ARQUA' POLESINE","A435");
        this.put("ARQUATA DEL TRONTO","A437");
        this.put("ARQUATA SCRIVIA","A436");
        this.put("ARRE","A438");
        this.put("ARRONE","A439");
        this.put("ARSAGO SEPRIO","A441");
        this.put("ARSIE'","A443");
        this.put("ARSIERO","A444");
        this.put("ARSITA","A445");
        this.put("ARSOLI","A446");
        this.put("ARTA TERME","A447");
        this.put("ARTEGNA","A448");
        this.put("ARTENA","A449");
        this.put("ARTOGNE","A451");
        this.put("ARVIER","A452");
        this.put("ARZACHENA","A453");
        this.put("ARZAGO D'ADDA","A440");
        this.put("ARZANA","A454");
        this.put("ARZANO","A455");
        this.put("ARZENE","A456");
        this.put("ARZERGRANDE","A458");
        this.put("ARZIGNANO","A459");
        this.put("ASCEA","A460");
        this.put("ASCIANO","A461");
        this.put("ASCOLI PICENO","A462");
        this.put("ASCOLI SATRIANO","A463");
        this.put("ASCREA","A464");
        this.put("ASIAGO","A465");
        this.put("ASIGLIANO VENETO","A467");
        this.put("ASIGLIANO VERCELLESE","A466");
        this.put("ASOLA","A470");
        this.put("ASOLO","A471");
        this.put("ASSAGO","A473");
        this.put("ASSEMINI","A474");
        this.put("ASSISI","A475");
        this.put("ASSO","A476");
        this.put("ASSOLO","A477");
        this.put("ASSORO","A478");
        this.put("ASTI","A479");
        this.put("ASUNI","A480");
        this.put("ATELETA","A481");
        this.put("ATELLA","A482");
        this.put("ATENA LUCANA","A484");
        this.put("ATESSA","A485");
        this.put("ATINA","A486");
        this.put("ATRANI","A487");
        this.put("ATRI","A488");
        this.put("ATRIPALDA","A489");
        this.put("ATTIGLIANO","A490");
        this.put("ATTIMIS","A491");
        this.put("ATZARA","A492");
        this.put("AUDITORE","A493");
        this.put("AUGUSTA","A494");
        this.put("AULETTA","A495");
        this.put("AULLA","A496");
        this.put("AURANO","A497");
        this.put("AURIGO","A499");
        this.put("AURONZO DI CADORE","A501");
        this.put("AUSONIA","A502");
        this.put("AUSTIS","A503");
        this.put("AVEGNO","A506");
        this.put("AVELENGO .HAFLING.","A507");
        this.put("AVELLA","A508");
        this.put("AVELLINO","A509");
        this.put("AVERARA","A511");
        this.put("AVERSA","A512");
        this.put("AVETRANA","A514");
        this.put("AVEZZANO","A515");
        this.put("AVIANO","A516");
        this.put("AVIATICO","A517");
        this.put("AVIGLIANA","A518");
        this.put("AVIGLIANO","A519");
        this.put("AVIGLIANO UMBRO","M258");
        this.put("AVIO","A520");
        this.put("AVISE","A521");
        this.put("AVOLA","A522");
        this.put("AVOLASCA","A523");
        this.put("AYAS","A094");
        this.put("AYMAVILLES","A108");
        this.put("AZEGLIO","A525");
        this.put("AZZANELLO","A526");
        this.put("AZZANO D'ASTI","A527");
        this.put("AZZANO DECIMO","A530");
        this.put("AZZANO MELLA","A529");
        this.put("AZZANO SAN PAOLO","A528");
        this.put("AZZATE","A531");
        this.put("AZZIO","A532");
        this.put("AZZONE","A533");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
