package libreria_sibilia.codicefiscale.document ;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_C extends HashMap<String, String> {

    public CitiesCodes_C(){
        this.put("CA' D'ANDREA","B320");
        this.put("CABELLA LIGURE","B311");
        this.put("CABIATE","B313");
        this.put("CABRAS","B314");
        this.put("CACCAMO","B315");
        this.put("CACCURI","B319");
        this.put("CADEGLIANO VICONAGO","B326");
        this.put("CADELBOSCO DI SOPRA","B328");
        this.put("CADEO","B332");
        this.put("CADERZONE TERME","B335");
        this.put("CADONEGHE","B345");
        this.put("CADORAGO","B346");
        this.put("CADREZZATE","B347");
        this.put("CADREZZATE CON OSMATE","M425");
        this.put("CAERANO DI SAN MARCO","B349");
        this.put("CAFASSE","B350");
        this.put("CAGGIANO","B351");
        this.put("CAGLI","B352");
        this.put("CAGLIARI","B354");
        this.put("CAGLIO","B355");
        this.put("CAGNANO AMITERNO","B358");
        this.put("CAGNANO VARANO","B357");
        this.put("CAGNO'","B360");
        this.put("CAGNO","B359");
        this.put("CAIANELLO","B361");
        this.put("CAIAZZO","B362");
        this.put("CAINES .KUENS.","B364");
        this.put("CAINO","B365");
        this.put("CAIOLO","B366");
        this.put("CAIRANO","B367");
        this.put("CAIRATE","B368");
        this.put("CAIRO MONTENOTTE","B369");
        this.put("CAIVANO","B371");
        this.put("CALABRITTO","B374");
        this.put("CALALZO DI CADORE","B375");
        this.put("CALAMANDRANA","B376");
        this.put("CALAMONACI","B377");
        this.put("CALANGIANUS","B378");
        this.put("CALANNA","B379");
        this.put("CALASCA CASTIGLIONE","B380");
        this.put("CALASCIBETTA","B381");
        this.put("CALASCIO","B382");
        this.put("CALASETTA","B383");
        this.put("CALATABIANO","B384");
        this.put("CALATAFIMI SEGESTA","B385");
        this.put("CALAVINO","B386");
        this.put("CALCATA","B388");
        this.put("CALCERANICA AL LAGO","B389");
        this.put("CALCI","B390");
        this.put("CALCIANO","B391");
        this.put("CALCINAIA","B392");
        this.put("CALCINATE","B393");
        this.put("CALCINATO","B394");
        this.put("CALCIO","B395");
        this.put("CALCO","B396");
        this.put("CALDARO SULLA STRADA DEL VINO .KALTERN AN DE.","B397");
        this.put("CALDAROLA","B398");
        this.put("CALDERARA DI RENO","B399");
        this.put("CALDES","B400");
        this.put("CALDIERO","B402");
        this.put("CALDOGNO","B403");
        this.put("CALDONAZZO","B404");
        this.put("CALENDASCO","B405");
        this.put("CALENZANO","B406");
        this.put("CALESTANO","B408");
        this.put("CALICE AL CORNOVIGLIO","B410");
        this.put("CALICE LIGURE","B409");
        this.put("CALIMERA","B413");
        this.put("CALITRI","B415");
        this.put("CALIZZANO","B416");
        this.put("CALLABIANA","B417");
        this.put("CALLIANO","B419");
        this.put("CALLIANO MONFERRATO","B418");
        this.put("CALOLZIOCORTE","B423");
        this.put("CALOPEZZATI","B424");
        this.put("CALOSSO","B425");
        this.put("CALOVETO","B426");
        this.put("CALTABELLOTTA","B427");
        this.put("CALTAGIRONE","B428");
        this.put("CALTANISSETTA","B429");
        this.put("CALTAVUTURO","B430");
        this.put("CALTIGNAGA","B431");
        this.put("CALTO","B432");
        this.put("CALTRANO","B433");
        this.put("CALUSCO D'ADDA","B434");
        this.put("CALUSO","B435");
        this.put("CALVAGESE DELLA RIVIERA","B436");
        this.put("CALVANICO","B437");
        this.put("CALVATONE","B439");
        this.put("CALVELLO","B440");
        this.put("CALVENE","B441");
        this.put("CALVENZANO","B442");
        this.put("CALVERA","B443");
        this.put("CALVI","B444");
        this.put("CALVI DELL'UMBRIA","B446");
        this.put("CALVI RISORTA","B445");
        this.put("CALVIGNANO","B447");
        this.put("CALVIGNASCO","B448");
        this.put("CALVISANO","B450");
        this.put("CALVIZZANO","B452");
        this.put("CAMAGNA MONFERRATO","B453");
        this.put("CAMAIORE","B455");
        this.put("CAMAIRAGO","B456");
        this.put("CAMANDONA","B457");
        this.put("CAMASTRA","B460");
        this.put("CAMBIAGO","B461");
        this.put("CAMBIANO","B462");
        this.put("CAMBIASCA","B463");
        this.put("CAMBURZANO","B465");
        this.put("CAMERANA","B467");
        this.put("CAMERANO","B468");
        this.put("CAMERANO CASASCO","B469");
        this.put("CAMERATA CORNELLO","B471");
        this.put("CAMERATA NUOVA","B472");
        this.put("CAMERATA PICENA","B470");
        this.put("CAMERI","B473");
        this.put("CAMERINO","B474");
        this.put("CAMEROTA","B476");
        this.put("CAMIGLIANO","B477");
        this.put("CAMINATA","B479");
        this.put("CAMINI","B481");
        this.put("CAMINO","B482");
        this.put("CAMINO AL TAGLIAMENTO","B483");
        this.put("CAMISANO","B484");
        this.put("CAMISANO VICENTINO","B485");
        this.put("CAMMARATA","B486");
        this.put("CAMO","B489");
        this.put("CAMOGLI","B490");
        this.put("CAMPAGNA","B492");
        this.put("CAMPAGNA LUPIA","B493");
        this.put("CAMPAGNANO DI ROMA","B496");
        this.put("CAMPAGNATICO","B497");
        this.put("CAMPAGNOLA CREMASCA","B498");
        this.put("CAMPAGNOLA EMILIA","B499");
        this.put("CAMPANA","B500");
        this.put("CAMPARADA","B501");
        this.put("CAMPEGINE","B502");
        this.put("CAMPELLO SUL CLITUNNO","B504");
        this.put("CAMPERTOGNO","B505");
        this.put("CAMPI BISENZIO","B507");
        this.put("CAMPI SALENTINA","B506");
        this.put("CAMPIGLIA CERVO","B508");
        this.put("CAMPIGLIA CERVO","M373");
        this.put("CAMPIGLIA DEI BERICI","B511");
        this.put("CAMPIGLIA MARITTIMA","B509");
        this.put("CAMPIGLIONE FENILE","B512");
        this.put("CAMPIONE D'ITALIA","B513");
        this.put("CAMPITELLO DI FASSA","B514");
        this.put("CAMPLI","B515");
        this.put("CAMPO CALABRO","B516");
        this.put("CAMPO DI GIOVE","B526");
        this.put("CAMPO DI TRENS .FREIENFELD.","B529");
        this.put("CAMPO LIGURE","B538");
        this.put("CAMPO NELL'ELBA","B553");
        this.put("CAMPO SAN MARTINO","B564");
        this.put("CAMPO TURES .SAND IN TAUFERS.","B570");
        this.put("CAMPOBASSO","B519");
        this.put("CAMPOBELLO DI LICATA","B520");
        this.put("CAMPOBELLO DI MAZARA","B521");
        this.put("CAMPOCHIARO","B522");
        this.put("CAMPODARSEGO","B524");
        this.put("CAMPODENNO","B525");
        this.put("CAMPODIMELE","B527");
        this.put("CAMPODIPIETRA","B528");
        this.put("CAMPODOLCINO","B530");
        this.put("CAMPODORO","B531");
        this.put("CAMPOFELICE DI FITALIA","B533");
        this.put("CAMPOFELICE DI ROCCELLA","B532");
        this.put("CAMPOFILONE","B534");
        this.put("CAMPOFIORITO","B535");
        this.put("CAMPOFORMIDO","B536");
        this.put("CAMPOFRANCO","B537");
        this.put("CAMPOGALLIANO","B539");
        this.put("CAMPOLATTARO","B541");
        this.put("CAMPOLI APPENNINO","B543");
        this.put("CAMPOLI DEL MONTE TABURNO","B542");
        this.put("CAMPOLIETO","B544");
        this.put("CAMPOLONGO AL TORRE","B545");
        this.put("CAMPOLONGO MAGGIORE","B546");
        this.put("CAMPOLONGO SUL BRENTA","B547");
        this.put("CAMPOLONGO TAPOGLIANO","M311");
        this.put("CAMPOMAGGIORE","B549");
        this.put("CAMPOMARINO","B550");
        this.put("CAMPOMORONE","B551");
        this.put("CAMPONOGARA","B554");
        this.put("CAMPORA","B555");
        this.put("CAMPOREALE","B556");
        this.put("CAMPORGIANO","B557");
        this.put("CAMPOROSSO","B559");
        this.put("CAMPOROTONDO DI FIASTRONE","B562");
        this.put("CAMPOROTONDO ETNEO","B561");
        this.put("CAMPOSAMPIERO","B563");
        this.put("CAMPOSANO","B565");
        this.put("CAMPOSANTO","B566");
        this.put("CAMPOSPINOSO","B567");
        this.put("CAMPOTOSTO","B569");
        this.put("CAMUGNANO","B572");
        this.put("CANAL SAN BOVO","B577");
        this.put("CANALE","B573");
        this.put("CANALE D'AGORDO","B574");
        this.put("CANALE MONTERANO","B576");
        this.put("CANARO","B578");
        this.put("CANAZEI","B579");
        this.put("CANCELLARA","B580");
        this.put("CANCELLO ED ARNONE","B581");
        this.put("CANDA","B582");
        this.put("CANDELA","B584");
        this.put("CANDELO","B586");
        this.put("CANDIA CANAVESE","B588");
        this.put("CANDIA LOMELLINA","B587");
        this.put("CANDIANA","B589");
        this.put("CANDIDA","B590");
        this.put("CANDIDONI","B591");
        this.put("CANDIOLO","B592");
        this.put("CANEGRATE","B593");
        this.put("CANELLI","B594");
        this.put("CANEPINA","B597");
        this.put("CANEVA","B598");
        this.put("CANEVINO","B599");
        this.put("CANICATTI'","B602");
        this.put("CANICATTINI BAGNI","B603");
        this.put("CANINO","B604");
        this.put("CANISCHIO","B605");
        this.put("CANISTRO","B606");
        this.put("CANNA","B607");
        this.put("CANNALONGA","B608");
        this.put("CANNARA","B609");
        this.put("CANNERO RIVIERA","B610");
        this.put("CANNETO PAVESE","B613");
        this.put("CANNETO SULL'OGLIO","B612");
        this.put("CANNOBIO","B615");
        this.put("CANNOLE","B616");
        this.put("CANOLO","B617");
        this.put("CANONICA D'ADDA","B618");
        this.put("CANOSA DI PUGLIA","B619");
        this.put("CANOSA SANNITA","B620");
        this.put("CANOSIO","B621");
        this.put("CANOSSA","C669");
        this.put("CANSANO","B624");
        this.put("CANTAGALLO","B626");
        this.put("CANTALICE","B627");
        this.put("CANTALUPA","B628");
        this.put("CANTALUPO IN SABINA","B631");
        this.put("CANTALUPO LIGURE","B629");
        this.put("CANTALUPO NEL SANNIO","B630");
        this.put("CANTARANA","B633");
        this.put("CANTELLO","B634");
        this.put("CANTERANO","B635");
        this.put("CANTIANO","B636");
        this.put("CANTOIRA","B637");
        this.put("CANTU'","B639");
        this.put("CANZANO","B640");
        this.put("CANZO","B641");
        this.put("CAORLE","B642");
        this.put("CAORSO","B643");
        this.put("CAPACCIO PAESTUM","B644");
        this.put("CAPACI","B645");
        this.put("CAPALBIO","B646");
        this.put("CAPANNOLI","B647");
        this.put("CAPANNORI","B648");
        this.put("CAPENA","B649");
        this.put("CAPERGNANICA","B650");
        this.put("CAPESTRANO","B651");
        this.put("CAPIAGO INTIMIANO","B653");
        this.put("CAPISTRANO","B655");
        this.put("CAPISTRELLO","B656");
        this.put("CAPITIGNANO","B658");
        this.put("CAPIZZI","B660");
        this.put("CAPIZZONE","B661");
        this.put("CAPO DI PONTE","B664");
        this.put("CAPO D'ORLANDO","B666");
        this.put("CAPODIMONTE","B663");
        this.put("CAPODRISE","B667");
        this.put("CAPOLIVERI","B669");
        this.put("CAPOLONA","B670");
        this.put("CAPONAGO","B671");
        this.put("CAPORCIANO","B672");
        this.put("CAPOSELE","B674");
        this.put("CAPOTERRA","B675");
        this.put("CAPOVALLE","B676");
        this.put("CAPPADOCIA","B677");
        this.put("CAPPELLA CANTONE","B679");
        this.put("CAPPELLA DE' PICENARDI","B680");
        this.put("CAPPELLA MAGGIORE","B678");
        this.put("CAPPELLE SUL TAVO","B681");
        this.put("CAPRACOTTA","B682");
        this.put("CAPRAIA E LIMITE","B684");
        this.put("CAPRAIA ISOLA","B685");
        this.put("CAPRALBA","B686");
        this.put("CAPRANICA","B688");
        this.put("CAPRANICA PRENESTINA","B687");
        this.put("CAPRARICA DI LECCE","B690");
        this.put("CAPRAROLA","B691");
        this.put("CAPRAUNA","B692");
        this.put("CAPRESE MICHELANGELO","B693");
        this.put("CAPREZZO","B694");
        this.put("CAPRI","B696");
        this.put("CAPRI LEONE","B695");
        this.put("CAPRIANA","B697");
        this.put("CAPRIANO DEL COLLE","B698");
        this.put("CAPRIATA D'ORBA","B701");
        this.put("CAPRIATE SAN GERVASIO","B703");
        this.put("CAPRIATI A VOLTURNO","B704");
        this.put("CAPRIE","B705");
        this.put("CAPRIGLIA IRPINA","B706");
        this.put("CAPRIGLIO","B707");
        this.put("CAPRILE","B708");
        this.put("CAPRINO BERGAMASCO","B710");
        this.put("CAPRINO VERONESE","B709");
        this.put("CAPRIOLO","B711");
        this.put("CAPRIVA DEL FRIULI","B712");
        this.put("CAPUA","B715");
        this.put("CAPURSO","B716");
        this.put("CARAFFA DEL BIANCO","B718");
        this.put("CARAFFA DI CATANZARO","B717");
        this.put("CARAGLIO","B719");
        this.put("CARAMAGNA PIEMONTE","B720");
        this.put("CARAMANICO TERME","B722");
        this.put("CARANO","B723");
        this.put("CARAPELLE","B724");
        this.put("CARAPELLE CALVISIO","B725");
        this.put("CARASCO","B726");
        this.put("CARASSAI","B727");
        this.put("CARATE BRIANZA","B729");
        this.put("CARATE URIO","B730");
        this.put("CARAVAGGIO","B731");
        this.put("CARAVATE","B732");
        this.put("CARAVINO","B733");
        this.put("CARAVONICA","B734");
        this.put("CARBOGNANO","B735");
        this.put("CARBONARA AL TICINO","B741");
        this.put("CARBONARA DI NOLA","B740");
        this.put("CARBONARA DI PO","B739");
        this.put("CARBONARA SCRIVIA","B736");
        this.put("CARBONATE","B742");
        this.put("CARBONE","B743");
        this.put("CARBONERA","B744");
        this.put("CARBONIA","B745");
        this.put("CARCARE","B748");
        this.put("CARCERI","B749");
        this.put("CARCOFORO","B752");
        this.put("CARDANO AL CAMPO","B754");
        this.put("CARDE'","B755");
        this.put("CARDEDU","M285");
        this.put("CARDETO","B756");
        this.put("CARDINALE","B758");
        this.put("CARDITO","B759");
        this.put("CAREGGINE","B760");
        this.put("CAREMA","B762");
        this.put("CARENNO","B763");
        this.put("CARENTINO","B765");
        this.put("CARERI","B766");
        this.put("CARESANA","B767");
        this.put("CARESANABLOT","B768");
        this.put("CAREZZANO","B769");
        this.put("CARFIZZI","B771");
        this.put("CARGEGHE","B772");
        this.put("CARIATI","B774");
        this.put("CARIFE","B776");
        this.put("CARIGNANO","B777");
        this.put("CARIMATE","B778");
        this.put("CARINARO","B779");
        this.put("CARINI","B780");
        this.put("CARINOLA","B781");
        this.put("CARISIO","B782");
        this.put("CARISOLO","B783");
        this.put("CARLANTINO","B784");
        this.put("CARLAZZO","B785");
        this.put("CARLENTINI","B787");
        this.put("CARLINO","B788");
        this.put("CARLOFORTE","B789");
        this.put("CARLOPOLI","B790");
        this.put("CARMAGNOLA","B791");
        this.put("CARMIANO","B792");
        this.put("CARMIGNANO","B794");
        this.put("CARMIGNANO DI BRENTA","B795");
        this.put("CARNAGO","B796");
        this.put("CARNATE","B798");
        this.put("CAROBBIO DEGLI ANGELI","B801");
        this.put("CAROLEI","B802");
        this.put("CARONA","B803");
        this.put("CARONIA","B804");
        this.put("CARONNO PERTUSELLA","B805");
        this.put("CARONNO VARESINO","B807");
        this.put("CAROSINO","B808");
        this.put("CAROVIGNO","B809");
        this.put("CAROVILLI","B810");
        this.put("CARPANETO PIACENTINO","B812");
        this.put("CARPANZANO","B813");
        this.put("CARPASIO","B814");
        this.put("CARPEGNA","B816");
        this.put("CARPENEDOLO","B817");
        this.put("CARPENETO","B818");
        this.put("CARPI","B819");
        this.put("CARPIANO","B820");
        this.put("CARPIGNANO SALENTINO","B822");
        this.put("CARPIGNANO SESIA","B823");
        this.put("CARPINETI","B825");
        this.put("CARPINETO DELLA NORA","B827");
        this.put("CARPINETO ROMANO","B828");
        this.put("CARPINETO SINELLO","B826");
        this.put("CARPINO","B829");
        this.put("CARPINONE","B830");
        this.put("CARRARA","B832");
        this.put("CARRE'","B835");
        this.put("CARREGA LIGURE","B836");
        this.put("CARRO","B838");
        this.put("CARRODANO","B839");
        this.put("CARROSIO","B840");
        this.put("CARRU'","B841");
        this.put("CARSOLI","B842");
        this.put("CARTIGLIANO","B844");
        this.put("CARTIGNANO","B845");
        this.put("CARTOCETO","B846");
        this.put("CARTOSIO","B847");
        this.put("CARTURA","B848");
        this.put("CARUGATE","B850");
        this.put("CARUGO","B851");
        this.put("CARUNCHIO","B853");
        this.put("CARVICO","B854");
        this.put("CARZANO","B856");
        this.put("CASABONA","B857");
        this.put("CASACALENDA","B858");
        this.put("CASACANDITELLA","B859");
        this.put("CASAGIOVE","B860");
        this.put("CASAL CERMELLI","B870");
        this.put("CASAL DI PRINCIPE","B872");
        this.put("CASAL VELINO","B895");
        this.put("CASALANGUIDA","B861");
        this.put("CASALATTICO","B862");
        this.put("CASALBELTRAME","B864");
        this.put("CASALBORDINO","B865");
        this.put("CASALBORE","B866");
        this.put("CASALBORGONE","B867");
        this.put("CASALBUONO","B868");
        this.put("CASALBUTTANO ED UNITI","B869");
        this.put("CASALCIPRANO","B871");
        this.put("CASALDUNI","B873");
        this.put("CASALE CORTE CERRO","B876");
        this.put("CASALE CREMASCO VIDOLASCO","B881");
        this.put("CASALE DI SCODOSIA","B877");
        this.put("CASALE LITTA","B875");
        this.put("CASALE MARITTIMO","B878");
        this.put("CASALE MONFERRATO","B885");
        this.put("CASALE SUL SILE","B879");
        this.put("CASALECCHIO DI RENO","B880");
        this.put("CASALEGGIO BOIRO","B882");
        this.put("CASALEGGIO NOVARA","B883");
        this.put("CASALEONE","B886");
        this.put("CASALETTO CEREDANO","B889");
        this.put("CASALETTO DI SOPRA","B890");
        this.put("CASALETTO LODIGIANO","B887");
        this.put("CASALETTO SPARTANO","B888");
        this.put("CASALETTO VAPRIO","B891");
        this.put("CASALFIUMANESE","B892");
        this.put("CASALGRANDE","B893");
        this.put("CASALGRASSO","B894");
        this.put("CASALI DEL MANCO","M385");
        this.put("CASALINCONTRADA","B896");
        this.put("CASALINO","B897");
        this.put("CASALMAGGIORE","B898");
        this.put("CASALMAIOCCO","B899");
        this.put("CASALMORANO","B900");
        this.put("CASALMORO","B901");
        this.put("CASALNOCETO","B902");
        this.put("CASALNUOVO DI NAPOLI","B905");
        this.put("CASALNUOVO MONTEROTARO","B904");
        this.put("CASALOLDO","B907");
        this.put("CASALPUSTERLENGO","B910");
        this.put("CASALROMANO","B911");
        this.put("CASALSERUGO","B912");
        this.put("CASALUCE","B916");
        this.put("CASALVECCHIO DI PUGLIA","B917");
        this.put("CASALVECCHIO SICULO","B918");
        this.put("CASALVIERI","B919");
        this.put("CASALVOLONE","B920");
        this.put("CASALZUIGNO","B921");
        this.put("CASAMARCIANO","B922");
        this.put("CASAMASSIMA","B923");
        this.put("CASAMICCIOLA TERME","B924");
        this.put("CASANDRINO","B925");
        this.put("CASANOVA ELVO","B928");
        this.put("CASANOVA LERRONE","B927");
        this.put("CASANOVA LONATI","B929");
        this.put("CASAPE","B932");
        this.put("CASAPESENNA","M260");
        this.put("CASAPINTA","B933");
        this.put("CASAPROTA","B934");
        this.put("CASAPULLA","B935");
        this.put("CASARANO","B936");
        this.put("CASARGO","B937");
        this.put("CASARILE","B938");
        this.put("CASARSA DELLA DELIZIA","B940");
        this.put("CASARZA LIGURE","B939");
        this.put("CASASCO","B941");
        this.put("CASASCO D'INTELVI","B942");
        this.put("CASATENOVO","B943");
        this.put("CASATISMA","B945");
        this.put("CASAVATORE","B946");
        this.put("CASAZZA","B947");
        this.put("CASCIA","B948");
        this.put("CASCIAGO","B949");
        this.put("CASCIANA TERME","A559");
        this.put("CASCIANA TERME LARI","M327");
        this.put("CASCINA","B950");
        this.put("CASCINETTE D'IVREA","B953");
        this.put("CASEI GEROLA","B954");
        this.put("CASELETTE","B955");
        this.put("CASELLA","B956");
        this.put("CASELLE IN PITTARI","B959");
        this.put("CASELLE LANDI","B961");
        this.put("CASELLE LURANI","B958");
        this.put("CASELLE TORINESE","B960");
        this.put("CASERTA","B963");
        this.put("CASIER","B965");
        this.put("CASIGNANA","B966");
        this.put("CASINA","B967");
        this.put("CASIRATE D'ADDA","B971");
        this.put("CASLINO D'ERBA","B974");
        this.put("CASNATE CON BERNATE","B977");
        this.put("CASNIGO","B978");
        this.put("CASOLA DI NAPOLI","B980");
        this.put("CASOLA IN LUNIGIANA","B979");
        this.put("CASOLA VALSENIO","B982");
        this.put("CASOLE BRUZIO","B983");
        this.put("CASOLE D'ELSA","B984");
        this.put("CASOLI","B985");
        this.put("CASORATE PRIMO","B988");
        this.put("CASORATE SEMPIONE","B987");
        this.put("CASOREZZO","B989");
        this.put("CASORIA","B990");
        this.put("CASORZO MONFERRATO","B991");
        this.put("CASPERIA","A472");
        this.put("CASPOGGIO","B993");
        this.put("CASSACCO","B994");
        this.put("CASSAGO BRIANZA","B996");
        this.put("CASSANO ALL'IONIO","C002");
        this.put("CASSANO D'ADDA","C003");
        this.put("CASSANO DELLE MURGE","B998");
        this.put("CASSANO IRPINO","B997");
        this.put("CASSANO MAGNAGO","C004");
        this.put("CASSANO SPINOLA","C005");
        this.put("CASSANO SPINOLA","M388");
        this.put("CASSANO VALCUVIA","B999");
        this.put("CASSARO","C006");
        this.put("CASSIGLIO","C007");
        this.put("CASSINA DE' PECCHI","C014");
        this.put("CASSINA RIZZARDI","C020");
        this.put("CASSINA VALSASSINA","C024");
        this.put("CASSINASCO","C022");
        this.put("CASSINE","C027");
        this.put("CASSINELLE","C030");
        this.put("CASSINETTA DI LUGAGNANO","C033");
        this.put("CASSINO","C034");
        this.put("CASSOLA","C037");
        this.put("CASSOLNOVO","C038");
        this.put("CASTAGNARO","C041");
        this.put("CASTAGNETO CARDUCCI","C044");
        this.put("CASTAGNETO PO","C045");
        this.put("CASTAGNITO","C046");
        this.put("CASTAGNOLE DELLE LANZE","C049");
        this.put("CASTAGNOLE MONFERRATO","C047");
        this.put("CASTAGNOLE PIEMONTE","C048");
        this.put("CASTANA","C050");
        this.put("CASTANO PRIMO","C052");
        this.put("CASTEGGIO","C053");
        this.put("CASTEGNATO","C055");
        this.put("CASTEGNERO","C056");
        this.put("CASTEL BARONIA","C058");
        this.put("CASTEL BOGLIONE","C064");
        this.put("CASTEL BOLOGNESE","C065");
        this.put("CASTEL CAMPAGNANO","B494");
        this.put("CASTEL CASTAGNA","C040");
        this.put("CASTEL COLONNA","C071");
        this.put("CASTEL CONDINO","C183");
        this.put("CASTEL D'AIANO","C075");
        this.put("CASTEL D'ARIO","C076");
        this.put("CASTEL D'AZZANO","C078");
        this.put("CASTEL DEL GIUDICE","C082");
        this.put("CASTEL DEL MONTE","C083");
        this.put("CASTEL DEL PIANO","C085");
        this.put("CASTEL DEL RIO","C086");
        this.put("CASTEL DI CASIO","B969");
        this.put("CASTEL DI IERI","C090");
        this.put("CASTEL DI IUDICA","C091");
        this.put("CASTEL DI LAMA","C093");
        this.put("CASTEL DI LUCIO","C094");
        this.put("CASTEL DI SANGRO","C096");
        this.put("CASTEL DI SASSO","C097");
        this.put("CASTEL DI TORA","C098");
        this.put("CASTEL FOCOGNANO","C102");
        this.put("CASTEL FRENTANO","C114");
        this.put("CASTEL GABBIANO","C115");
        this.put("CASTEL GANDOLFO","C116");
        this.put("CASTEL GIORGIO","C117");
        this.put("CASTEL GOFFREDO","C118");
        this.put("CASTEL GUELFO DI BOLOGNA","C121");
        this.put("CASTEL IVANO","M354");
        this.put("CASTEL MADAMA","C203");
        this.put("CASTEL MAGGIORE","C204");
        this.put("CASTEL MELLA","C208");
        this.put("CASTEL MORRONE","C211");
        this.put("CASTEL RITALDI","C252");
        this.put("CASTEL ROCCHERO","C253");
        this.put("CASTEL ROZZONE","C255");
        this.put("CASTEL SAN GIORGIO","C259");
        this.put("CASTEL SAN GIOVANNI","C261");
        this.put("CASTEL SAN LORENZO","C262");
        this.put("CASTEL SAN NICCOLO'","C263");
        this.put("CASTEL SAN PIETRO ROMANO","C266");
        this.put("CASTEL SAN PIETRO TERME","C265");
        this.put("CASTEL SAN VINCENZO","C270");
        this.put("CASTEL SANT'ANGELO","C268");
        this.put("CASTEL SANT'ELIA","C269");
        this.put("CASTEL VISCARDO","C289");
        this.put("CASTEL VITTORIO","C110");
        this.put("CASTEL VOLTURNO","C291");
        this.put("CASTELBALDO","C057");
        this.put("CASTELBELFORTE","C059");
        this.put("CASTELBELLINO","C060");
        this.put("CASTELBELLO CIARDES .KASTELBELL TSCHARS.","C062");
        this.put("CASTELBIANCO","C063");
        this.put("CASTELBOTTACCIO","C066");
        this.put("CASTELBUONO","C067");
        this.put("CASTELCIVITA","C069");
        this.put("CASTELCOVATI","C072");
        this.put("CASTELCUCCO","C073");
        this.put("CASTELDACCIA","C074");
        this.put("CASTELDELCI","C080");
        this.put("CASTELDELFINO","C081");
        this.put("CASTELDIDONE","C089");
        this.put("CASTELFIDARDO","C100");
        this.put("CASTELFIORENTINO","C101");
        this.put("CASTELFONDO","C103");
        this.put("CASTELFORTE","C104");
        this.put("CASTELFRANCI","C105");
        this.put("CASTELFRANCO DI SOPRA","C112");
        this.put("CASTELFRANCO DI SOTTO","C113");
        this.put("CASTELFRANCO EMILIA","C107");
        this.put("CASTELFRANCO IN MISCANO","C106");
        this.put("CASTELFRANCO PIANDISCO'","M322");
        this.put("CASTELFRANCO VENETO","C111");
        this.put("CASTELGERUNDO","M393");
        this.put("CASTELGOMBERTO","C119");
        this.put("CASTELGRANDE","C120");
        this.put("CASTELGUGLIELMO","C122");
        this.put("CASTELGUIDONE","C123");
        this.put("CASTELLABATE","C125");
        this.put("CASTELLAFIUME","C126");
        this.put("CASTELL'ALFERO","C127");
        this.put("CASTELLALTO","C128");
        this.put("CASTELLAMMARE DEL GOLFO","C130");
        this.put("CASTELLAMMARE DI STABIA","C129");
        this.put("CASTELLAMONTE","C133");
        this.put("CASTELLANA GROTTE","C134");
        this.put("CASTELLANA SICULA","C135");
        this.put("CASTELLANETA","C136");
        this.put("CASTELLANIA COPPI","C137");
        this.put("CASTELLANZA","C139");
        this.put("CASTELLAR","C140");
        this.put("CASTELLAR GUIDOBONO","C142");
        this.put("CASTELLARANO","C141");
        this.put("CASTELLARO","C143");
        this.put("CASTELL'ARQUATO","C145");
        this.put("CASTELLAVAZZO","C146");
        this.put("CASTELL'AZZARA","C147");
        this.put("CASTELLAZZO BORMIDA","C148");
        this.put("CASTELLAZZO NOVARESE","C149");
        this.put("CASTELLEONE","C153");
        this.put("CASTELLEONE DI SUASA","C152");
        this.put("CASTELLERO","C154");
        this.put("CASTELLETTO CERVO","C155");
        this.put("CASTELLETTO D'ERRO","C156");
        this.put("CASTELLETTO DI BRANDUZZO","C157");
        this.put("CASTELLETTO D'ORBA","C158");
        this.put("CASTELLETTO MERLI","C160");
        this.put("CASTELLETTO MOLINA","C161");
        this.put("CASTELLETTO MONFERRATO","C162");
        this.put("CASTELLETTO SOPRA TICINO","C166");
        this.put("CASTELLETTO STURA","C165");
        this.put("CASTELLETTO UZZONE","C167");
        this.put("CASTELLI","C169");
        this.put("CASTELLI CALEPIO","C079");
        this.put("CASTELLINA IN CHIANTI","C172");
        this.put("CASTELLINA MARITTIMA","C174");
        this.put("CASTELLINALDO D'ALBA","C173");
        this.put("CASTELLINO DEL BIFERNO","C175");
        this.put("CASTELLINO TANARO","C176");
        this.put("CASTELLIRI","C177");
        this.put("CASTELLO CABIAGLIO","B312");
        this.put("CASTELLO D'AGOGNA","C184");
        this.put("CASTELLO D'ARGILE","C185");
        this.put("CASTELLO DEL MATESE","C178");
        this.put("CASTELLO DELL'ACQUA","C186");
        this.put("CASTELLO DI ANNONE","A300");
        this.put("CASTELLO DI BRIANZA","C187");
        this.put("CASTELLO DI CISTERNA","C188");
        this.put("CASTELLO DI GODEGO","C190");
        this.put("CASTELLO DI SERRAVALLE","C191");
        this.put("CASTELLO TESINO","C194");
        this.put("CASTELLO MOLINA DI FIEMME","C189");
        this.put("CASTELLUCCHIO","C195");
        this.put("CASTELLUCCIO DEI SAURI","C198");
        this.put("CASTELLUCCIO INFERIORE","C199");
        this.put("CASTELLUCCIO SUPERIORE","C201");
        this.put("CASTELLUCCIO VALMAGGIORE","C202");
        this.put("CASTELL'UMBERTO","C051");
        this.put("CASTELMAGNO","C205");
        this.put("CASTELMARTE","C206");
        this.put("CASTELMASSA","C207");
        this.put("CASTELMAURO","C197");
        this.put("CASTELMEZZANO","C209");
        this.put("CASTELMOLA","C210");
        this.put("CASTELNOVETTO","C213");
        this.put("CASTELNOVO BARIANO","C215");
        this.put("CASTELNOVO DEL FRIULI","C217");
        this.put("CASTELNOVO DI SOTTO","C218");
        this.put("CASTELNOVO NE' MONTI","C219");
        this.put("CASTELNUOVO","C216");
        this.put("CASTELNUOVO BELBO","C226");
        this.put("CASTELNUOVO BERARDENGA","C227");
        this.put("CASTELNUOVO BOCCA D'ADDA","C228");
        this.put("CASTELNUOVO BORMIDA","C229");
        this.put("CASTELNUOVO BOZZENTE","C220");
        this.put("CASTELNUOVO CALCEA","C230");
        this.put("CASTELNUOVO CILENTO","C231");
        this.put("CASTELNUOVO DEL GARDA","C225");
        this.put("CASTELNUOVO DELLA DAUNIA","C222");
        this.put("CASTELNUOVO DI CEVA","C214");
        this.put("CASTELNUOVO DI CONZA","C235");
        this.put("CASTELNUOVO DI FARFA","C224");
        this.put("CASTELNUOVO DI GARFAGNANA","C236");
        this.put("CASTELNUOVO DI PORTO","C237");
        this.put("CASTELNUOVO DON BOSCO","C232");
        this.put("CASTELNUOVO MAGRA","C240");
        this.put("CASTELNUOVO NIGRA","C241");
        this.put("CASTELNUOVO PARANO","C223");
        this.put("CASTELNUOVO RANGONE","C242");
        this.put("CASTELNUOVO SCRIVIA","C243");
        this.put("CASTELNUOVO VAL DI CECINA","C244");
        this.put("CASTELPAGANO","C245");
        this.put("CASTELPETROSO","C246");
        this.put("CASTELPIZZUTO","C247");
        this.put("CASTELPLANIO","C248");
        this.put("CASTELPOTO","C250");
        this.put("CASTELRAIMONDO","C251");
        this.put("CASTELROTTO .KASTELRUTH.","C254");
        this.put("CASTELSANTANGELO SUL NERA","C267");
        this.put("CASTELSARACENO","C271");
        this.put("CASTELSARDO","C272");
        this.put("CASTELSEPRIO","C273");
        this.put("CASTELSILANO","B968");
        this.put("CASTELSPINA","C274");
        this.put("CASTELTERMINI","C275");
        this.put("CASTELVECCANA","C181");
        this.put("CASTELVECCHIO CALVISIO","C278");
        this.put("CASTELVECCHIO DI ROCCA BARBENA","C276");
        this.put("CASTELVECCHIO SUBEQUO","C279");
        this.put("CASTELVENERE","C280");
        this.put("CASTELVERDE","B129");
        this.put("CASTELVERRINO","C200");
        this.put("CASTELVETERE IN VAL FORTORE","C284");
        this.put("CASTELVETERE SUL CALORE","C283");
        this.put("CASTELVETRANO","C286");
        this.put("CASTELVETRO DI MODENA","C287");
        this.put("CASTELVETRO PIACENTINO","C288");
        this.put("CASTELVISCONTI","C290");
        this.put("CASTENASO","C292");
        this.put("CASTENEDOLO","C293");
        this.put("CASTIADAS","M288");
        this.put("CASTIGLION FIBOCCHI","C318");
        this.put("CASTIGLION FIORENTINO","C319");
        this.put("CASTIGLIONE A CASAURIA","C308");
        this.put("CASTIGLIONE CHIAVARESE","C302");
        this.put("CASTIGLIONE COSENTINO","C301");
        this.put("CASTIGLIONE D'ADDA","C304");
        this.put("CASTIGLIONE DEI PEPOLI","C296");
        this.put("CASTIGLIONE DEL GENOVESI","C306");
        this.put("CASTIGLIONE DEL LAGO","C309");
        this.put("CASTIGLIONE DELLA PESCAIA","C310");
        this.put("CASTIGLIONE DELLE STIVIERE","C312");
        this.put("CASTIGLIONE DI GARFAGNANA","C303");
        this.put("CASTIGLIONE DI SICILIA","C297");
        this.put("CASTIGLIONE D'INTELVI","C299");
        this.put("CASTIGLIONE D'ORCIA","C313");
        this.put("CASTIGLIONE FALLETTO","C314");
        this.put("CASTIGLIONE IN TEVERINA","C315");
        this.put("CASTIGLIONE MESSER MARINO","C298");
        this.put("CASTIGLIONE MESSER RAIMONDO","C316");
        this.put("CASTIGLIONE OLONA","C300");
        this.put("CASTIGLIONE TINELLA","C317");
        this.put("CASTIGLIONE TORINESE","C307");
        this.put("CASTIGNANO","C321");
        this.put("CASTILENTI","C322");
        this.put("CASTINO","C323");
        this.put("CASTIONE ANDEVENNO","C325");
        this.put("CASTIONE DELLA PRESOLANA","C324");
        this.put("CASTIONS DI STRADA","C327");
        this.put("CASTIRAGA VIDARDO","C329");
        this.put("CASTO","C330");
        this.put("CASTORANO","C331");
        this.put("CASTREZZATO","C332");
        this.put("CASTRI DI LECCE","C334");
        this.put("CASTRIGNANO DE' GRECI","C335");
        this.put("CASTRIGNANO DEL CAPO","C336");
        this.put("CASTRO","C337");
        this.put("CASTRO","M261");
        this.put("CASTRO DEI VOLSCI","C338");
        this.put("CASTROCARO TERME E TERRA DEL SOLE","C339");
        this.put("CASTROCIELO","C340");
        this.put("CASTROFILIPPO","C341");
        this.put("CASTROLIBERO","C108");
        this.put("CASTRONNO","C343");
        this.put("CASTRONOVO DI SICILIA","C344");
        this.put("CASTRONUOVO DI SANT'ANDREA","C345");
        this.put("CASTROPIGNANO","C346");
        this.put("CASTROREALE","C347");
        this.put("CASTROREGIO","C348");
        this.put("CASTROVILLARI","C349");
        this.put("CATANIA","C351");
        this.put("CATANZARO","C352");
        this.put("CATENANUOVA","C353");
        this.put("CATIGNANO","C354");
        this.put("CATTOLICA","C357");
        this.put("CATTOLICA ERACLEA","C356");
        this.put("CAULONIA","C285");
        this.put("CAUTANO","C359");
        this.put("CAVA DE' TIRRENI","C361");
        this.put("CAVA MANARA","C360");
        this.put("CAVACURTA","C362");
        this.put("CAVAGLIA'","C363");
        this.put("CAVAGLIETTO","C364");
        this.put("CAVAGLIO D'AGOGNA","C365");
        this.put("CAVAGLIO SPOCCIA","C367");
        this.put("CAVAGNOLO","C369");
        this.put("CAVAION VERONESE","C370");
        this.put("CAVALESE","C372");
        this.put("CAVALLASCA","C374");
        this.put("CAVALLERLEONE","C375");
        this.put("CAVALLERMAGGIORE","C376");
        this.put("CAVALLINO","C377");
        this.put("CAVALLINO TREPORTI","M308");
        this.put("CAVALLIRIO","C378");
        this.put("CAVARENO","C380");
        this.put("CAVARGNA","C381");
        this.put("CAVARIA CON PREMEZZO","C382");
        this.put("CAVARZERE","C383");
        this.put("CAVASO DEL TOMBA","C384");
        this.put("CAVASSO NUOVO","C385");
        this.put("CAVATORE","C387");
        this.put("CAVAZZO CARNICO","C389");
        this.put("CAVE","C390");
        this.put("CAVEDAGO","C392");
        this.put("CAVEDINE","C393");
        this.put("CAVENAGO D'ADDA","C394");
        this.put("CAVENAGO DI BRIANZA","C395");
        this.put("CAVERNAGO","C396");
        this.put("CAVEZZO","C398");
        this.put("CAVIZZANA","C400");
        this.put("CAVOUR","C404");
        this.put("CAVRIAGO","C405");
        this.put("CAVRIANA","C406");
        this.put("CAVRIGLIA","C407");
        this.put("CAZZAGO BRABBIA","C409");
        this.put("CAZZAGO SAN MARTINO","C408");
        this.put("CAZZANO DI TRAMIGNA","C412");
        this.put("CAZZANO SANT'ANDREA","C410");
        this.put("CECCANO","C413");
        this.put("CECIMA","C414");
        this.put("CECINA","C415");
        this.put("CEDEGOLO","C417");
        this.put("CEDRASCO","C418");
        this.put("CEFALA' DIANA","C420");
        this.put("CEFALU'","C421");
        this.put("CEGGIA","C422");
        this.put("CEGLIE MESSAPICA","C424");
        this.put("CELANO","C426");
        this.put("CELENZA SUL TRIGNO","C428");
        this.put("CELENZA VALFORTORE","C429");
        this.put("CELICO","C430");
        this.put("CELLA DATI","C435");
        this.put("CELLA MONTE","C432");
        this.put("CELLAMARE","C436");
        this.put("CELLARA","C437");
        this.put("CELLARENGO","C438");
        this.put("CELLATICA","C439");
        this.put("CELLE DI BULGHERIA","C444");
        this.put("CELLE DI MACRA","C441");
        this.put("CELLE DI SAN VITO","C442");
        this.put("CELLE ENOMONDO","C440");
        this.put("CELLE LIGURE","C443");
        this.put("CELLENO","C446");
        this.put("CELLERE","C447");
        this.put("CELLINO ATTANASIO","C449");
        this.put("CELLINO SAN MARCO","C448");
        this.put("CELLIO","C450");
        this.put("CELLIO CON BREIA","M398");
        this.put("CELLOLE","M262");
        this.put("CEMBRA","C452");
        this.put("CEMBRA LISIGNAGO","M355");
        this.put("CENADI","C453");
        this.put("CENATE SOPRA","C456");
        this.put("CENATE SOTTO","C457");
        this.put("CENCENIGHE AGORDINO","C458");
        this.put("CENE","C459");
        this.put("CENESELLI","C461");
        this.put("CENGIO","C463");
        this.put("CENTA SAN NICOLO'","C467");
        this.put("CENTALLO","C466");
        this.put("CENTO","C469");
        this.put("CENTOLA","C470");
        this.put("CENTRACHE","C472");
        this.put("CENTRO VALLE INTELVI","M394");
        this.put("CENTURIPE","C471");
        this.put("CEPAGATTI","C474");
        this.put("CEPPALONI","C476");
        this.put("CEPPO MORELLI","C478");
        this.put("CEPRANO","C479");
        this.put("CERAMI","C480");
        this.put("CERANESI","C481");
        this.put("CERANO","C483");
        this.put("CERANO D'INTELVI","C482");
        this.put("CERANOVA","C484");
        this.put("CERASO","C485");
        this.put("CERCEMAGGIORE","C486");
        this.put("CERCENASCO","C487");
        this.put("CERCEPICCOLA","C488");
        this.put("CERCHIARA DI CALABRIA","C489");
        this.put("CERCHIO","C492");
        this.put("CERCINO","C493");
        this.put("CERCIVENTO","C494");
        this.put("CERCOLA","C495");
        this.put("CERDA","C496");
        this.put("CEREA","C498");
        this.put("CEREGNANO","C500");
        this.put("CERENZIA","C501");
        this.put("CERES","C497");
        this.put("CERESARA","C502");
        this.put("CERESETO","C503");
        this.put("CERESOLE ALBA","C504");
        this.put("CERESOLE REALE","C505");
        this.put("CERETE","C506");
        this.put("CERETTO LOMELLINA","C508");
        this.put("CERGNAGO","C509");
        this.put("CERIALE","C510");
        this.put("CERIANA","C511");
        this.put("CERIANO LAGHETTO","C512");
        this.put("CERIGNALE","C513");
        this.put("CERIGNOLA","C514");
        this.put("CERISANO","C515");
        this.put("CERMENATE","C516");
        this.put("CERMES .TSCHERMS.","A022");
        this.put("CERMIGNANO","C517");
        this.put("CERNOBBIO","C520");
        this.put("CERNUSCO LOMBARDONE","C521");
        this.put("CERNUSCO SUL NAVIGLIO","C523");
        this.put("CERRETO CASTELLO","C526");
        this.put("CERRETO D'ASTI","C528");
        this.put("CERRETO D'ESI","C524");
        this.put("CERRETO DI SPOLETO","C527");
        this.put("CERRETO GRUE","C507");
        this.put("CERRETO GUIDI","C529");
        this.put("CERRETO LAZIALE","C518");
        this.put("CERRETO SANNITA","C525");
        this.put("CERRETTO LANGHE","C530");
        this.put("CERRINA MONFERRATO","C531");
        this.put("CERRIONE","C532");
        this.put("CERRO AL LAMBRO","C536");
        this.put("CERRO AL VOLTURNO","C534");
        this.put("CERRO MAGGIORE","C537");
        this.put("CERRO TANARO","C533");
        this.put("CERRO VERONESE","C538");
        this.put("CERSOSIMO","C539");
        this.put("CERTALDO","C540");
        this.put("CERTOSA DI PAVIA","C541");
        this.put("CERVA","C542");
        this.put("CERVARA DI ROMA","C543");
        this.put("CERVARESE SANTA CROCE","C544");
        this.put("CERVARO","C545");
        this.put("CERVASCA","C547");
        this.put("CERVATTO","C548");
        this.put("CERVENO","C549");
        this.put("CERVERE","C550");
        this.put("CERVESINA","C551");
        this.put("CERVETERI","C552");
        this.put("CERVIA","C553");
        this.put("CERVICATI","C554");
        this.put("CERVIGNANO D'ADDA","C555");
        this.put("CERVIGNANO DEL FRIULI","C556");
        this.put("CERVINARA","C557");
        this.put("CERVINO","C558");
        this.put("CERVO","C559");
        this.put("CERZETO","C560");
        this.put("CESA","C561");
        this.put("CESANA BRIANZA","C563");
        this.put("CESANA TORINESE","C564");
        this.put("CESANO BOSCONE","C565");
        this.put("CESANO MADERNO","C566");
        this.put("CESARA","C567");
        this.put("CESARO'","C568");
        this.put("CESATE","C569");
        this.put("CESENA","C573");
        this.put("CESENATICO","C574");
        this.put("CESINALI","C576");
        this.put("CESIO","C578");
        this.put("CESIOMAGGIORE","C577");
        this.put("CESSALTO","C580");
        this.put("CESSANITI","C581");
        this.put("CESSAPALOMBO","C582");
        this.put("CESSOLE","C583");
        this.put("CETARA","C584");
        this.put("CETO","C585");
        this.put("CETONA","C587");
        this.put("CETRARO","C588");
        this.put("CEVA","C589");
        this.put("CEVO","C591");
        this.put("CHALLAND SAINT ANSELME","C593");
        this.put("CHALLAND SAINT VICTOR","C594");
        this.put("CHAMBAVE","C595");
        this.put("CHAMOIS","B491");
        this.put("CHAMPDEPRAZ","C596");
        this.put("CHAMPORCHER","B540");
        this.put("CHARVENSOD","C598");
        this.put("CHATILLON","C294");
        this.put("CHERASCO","C599");
        this.put("CHEREMULE","C600");
        this.put("CHIALAMBERTO","C604");
        this.put("CHIAMPO","C605");
        this.put("CHIANCHE","C606");
        this.put("CHIANCIANO TERME","C608");
        this.put("CHIANNI","C609");
        this.put("CHIANOCCO","C610");
        this.put("CHIARAMONTE GULFI","C612");
        this.put("CHIARAMONTI","C613");
        this.put("CHIARANO","C614");
        this.put("CHIARAVALLE","C615");
        this.put("CHIARAVALLE CENTRALE","C616");
        this.put("CHIARI","C618");
        this.put("CHIAROMONTE","C619");
        this.put("CHIAUCI","C620");
        this.put("CHIAVARI","C621");
        this.put("CHIAVENNA","C623");
        this.put("CHIAVERANO","C624");
        this.put("CHIENES .KIENS.","C625");
        this.put("CHIERI","C627");
        this.put("CHIES D'ALPAGO","C630");
        this.put("CHIESA IN VALMALENCO","C628");
        this.put("CHIESANUOVA","C629");
        this.put("CHIESINA UZZANESE","C631");
        this.put("CHIETI","C632");
        this.put("CHIEUTI","C633");
        this.put("CHIEVE","C634");
        this.put("CHIGNOLO D'ISOLA","C635");
        this.put("CHIGNOLO PO","C637");
        this.put("CHIOGGIA","C638");
        this.put("CHIOMONTE","C639");
        this.put("CHIONS","C640");
        this.put("CHIOPRIS VISCONE","C641");
        this.put("CHITIGNANO","C648");
        this.put("CHIUDUNO","C649");
        this.put("CHIUPPANO","C650");
        this.put("CHIURO","C651");
        this.put("CHIUSA DI PESIO","C653");
        this.put("CHIUSA DI SAN MICHELE","C655");
        this.put("CHIUSA .KLAUSEN.","C652");
        this.put("CHIUSA SCLAFANI","C654");
        this.put("CHIUSAFORTE","C656");
        this.put("CHIUSANICO","C657");
        this.put("CHIUSANO D'ASTI","C658");
        this.put("CHIUSANO DI SAN DOMENICO","C659");
        this.put("CHIUSAVECCHIA","C660");
        this.put("CHIUSDINO","C661");
        this.put("CHIUSI","C662");
        this.put("CHIUSI DELLA VERNA","C663");
        this.put("CHIVASSO","C665");
        this.put("CIAMPINO","M272");
        this.put("CIANCIANA","C668");
        this.put("CIBIANA DI CADORE","C672");
        this.put("CICAGNA","C673");
        this.put("CICALA","C674");
        this.put("CICCIANO","C675");
        this.put("CICERALE","C676");
        this.put("CICILIANO","C677");
        this.put("CICOGNOLO","C678");
        this.put("CICONIO","C679");
        this.put("CIGLIANO","C680");
        this.put("CIGLIE'","C681");
        this.put("CIGOGNOLA","C684");
        this.put("CIGOLE","C685");
        this.put("CILAVEGNA","C686");
        this.put("CIMADOLMO","C689");
        this.put("CIMBERGO","C691");
        this.put("CIMEGO","C694");
        this.put("CIMINA'","C695");
        this.put("CIMINNA","C696");
        this.put("CIMITILE","C697");
        this.put("CIMOLAIS","C699");
        this.put("CIMONE","C700");
        this.put("CINAGLIO","C701");
        this.put("CINETO ROMANO","C702");
        this.put("CINGIA DE' BOTTI","C703");
        this.put("CINGOLI","C704");
        this.put("CINIGIANO","C705");
        this.put("CINISELLO BALSAMO","C707");
        this.put("CINISI","C708");
        this.put("CINO","C709");
        this.put("CINQUEFRONDI","C710");
        this.put("CINTANO","C711");
        this.put("CINTE TESINO","C712");
        this.put("CINTO CAOMAGGIORE","C714");
        this.put("CINTO EUGANEO","C713");
        this.put("CINZANO","C715");
        this.put("CIORLANO","C716");
        this.put("CIPRESSA","C718");
        this.put("CIRCELLO","C719");
        this.put("CIRIE'","C722");
        this.put("CIRIGLIANO","C723");
        this.put("CIRIMIDO","C724");
        this.put("CIRO'","C725");
        this.put("CIRO' MARINA","C726");
        this.put("CIS","C727");
        this.put("CISANO BERGAMASCO","C728");
        this.put("CISANO SUL NEVA","C729");
        this.put("CISERANO","C730");
        this.put("CISLAGO","C732");
        this.put("CISLIANO","C733");
        this.put("CISMON DEL GRAPPA","C734");
        this.put("CISON DI VALMARINO","C735");
        this.put("CISSONE","C738");
        this.put("CISTERNA D'ASTI","C739");
        this.put("CISTERNA DI LATINA","C740");
        this.put("CISTERNINO","C741");
        this.put("CITERNA","C742");
        this.put("CITTA' DELLA PIEVE","C744");
        this.put("CITTA' DI CASTELLO","C745");
        this.put("CITTA' SANT'ANGELO","C750");
        this.put("CITTADELLA","C743");
        this.put("CITTADUCALE","C746");
        this.put("CITTANOVA","C747");
        this.put("CITTAREALE","C749");
        this.put("CITTIGLIO","C751");
        this.put("CIVATE","C752");
        this.put("CIVENNA","C754");
        this.put("CIVEZZA","C755");
        this.put("CIVEZZANO","C756");
        this.put("CIVIASCO","C757");
        this.put("CIVIDALE DEL FRIULI","C758");
        this.put("CIVIDATE AL PIANO","C759");
        this.put("CIVIDATE CAMUNO","C760");
        this.put("CIVITA","C763");
        this.put("CIVITA CASTELLANA","C765");
        this.put("CIVITA D'ANTINO","C766");
        this.put("CIVITACAMPOMARANO","C764");
        this.put("CIVITALUPARELLA","C768");
        this.put("CIVITANOVA DEL SANNIO","C769");
        this.put("CIVITANOVA MARCHE","C770");
        this.put("CIVITAQUANA","C771");
        this.put("CIVITAVECCHIA","C773");
        this.put("CIVITELLA ALFEDENA","C778");
        this.put("CIVITELLA CASANOVA","C779");
        this.put("CIVITELLA D'AGLIANO","C780");
        this.put("CIVITELLA DEL TRONTO","C781");
        this.put("CIVITELLA DI ROMAGNA","C777");
        this.put("CIVITELLA IN VAL DI CHIANA","C774");
        this.put("CIVITELLA MESSER RAIMONDO","C776");
        this.put("CIVITELLA PAGANICO","C782");
        this.put("CIVITELLA ROVETO","C783");
        this.put("CIVITELLA SAN PAOLO","C784");
        this.put("CIVO","C785");
        this.put("CLAINO CON OSTENO","C787");
        this.put("CLAUT","C790");
        this.put("CLAUZETTO","C791");
        this.put("CLAVESANA","C792");
        this.put("CLAVIERE","C793");
        this.put("CLES","C794");
        this.put("CLETO","C795");
        this.put("CLIVIO","C796");
        this.put("CLOZ","C797");
        this.put("CLUSONE","C800");
        this.put("COASSOLO TORINESE","C801");
        this.put("COAZZE","C803");
        this.put("COAZZOLO","C804");
        this.put("COCCAGLIO","C806");
        this.put("COCCONATO","C807");
        this.put("COCQUIO TREVISAGO","C810");
        this.put("COCULLO","C811");
        this.put("CODEVIGO","C812");
        this.put("CODEVILLA","C813");
        this.put("CODIGORO","C814");
        this.put("CODOGNE'","C815");
        this.put("CODOGNO","C816");
        this.put("CODROIPO","C817");
        this.put("CODRONGIANOS","C818");
        this.put("COGGIOLA","C819");
        this.put("COGLIATE","C820");
        this.put("COGNE","C821");
        this.put("COGOLETO","C823");
        this.put("COGOLLO DEL CENGIO","C824");
        this.put("COGORNO","C826");
        this.put("COLAZZA","C829");
        this.put("COLBORDOLO","C830");
        this.put("COLCERESA","M426");
        this.put("COLERE","C835");
        this.put("COLFELICE","C836");
        this.put("COLI","C838");
        this.put("COLICO","C839");
        this.put("COLLAGNA","C840");
        this.put("COLLALTO SABINO","C841");
        this.put("COLLARMELE","C844");
        this.put("COLLAZZONE","C845");
        this.put("COLLE BRIANZA","C851");
        this.put("COLLE D'ANCHISE","C854");
        this.put("COLLE DI TORA","C857");
        this.put("COLLE DI VAL D'ELSA","C847");
        this.put("COLLE SAN MAGNO","C870");
        this.put("COLLE SANNITA","C846");
        this.put("COLLE SANTA LUCIA","C872");
        this.put("COLLE UMBERTO","C848");
        this.put("COLLEBEATO","C850");
        this.put("COLLECCHIO","C852");
        this.put("COLLECORVINO","C853");
        this.put("COLLEDARA","C311");
        this.put("COLLEDIMACINE","C855");
        this.put("COLLEDIMEZZO","C856");
        this.put("COLLEFERRO","C858");
        this.put("COLLEGIOVE","C859");
        this.put("COLLEGNO","C860");
        this.put("COLLELONGO","C862");
        this.put("COLLEPARDO","C864");
        this.put("COLLEPASSO","C865");
        this.put("COLLEPIETRO","C866");
        this.put("COLLERETTO CASTELNUOVO","C867");
        this.put("COLLERETTO GIACOSA","C868");
        this.put("COLLESALVETTI","C869");
        this.put("COLLESANO","C871");
        this.put("COLLETORTO","C875");
        this.put("COLLEVECCHIO","C876");
        this.put("COLLI A VOLTURNO","C878");
        this.put("COLLI AL METAURO","M380");
        this.put("COLLI DEL TRONTO","C877");
        this.put("COLLI SUL VELINO","C880");
        this.put("COLLI VERDI","M419");
        this.put("COLLIANO","C879");
        this.put("COLLINAS","C882");
        this.put("COLLIO","C883");
        this.put("COLLOBIANO","C884");
        this.put("COLLOREDO DI MONTE ALBANO","C885");
        this.put("COLMURANO","C886");
        this.put("COLOBRARO","C888");
        this.put("COLOGNA VENETA","C890");
        this.put("COLOGNE","C893");
        this.put("COLOGNO AL SERIO","C894");
        this.put("COLOGNO MONZESE","C895");
        this.put("COLOGNOLA AI COLLI","C897");
        this.put("COLONNA","C900");
        this.put("COLONNELLA","C901");
        this.put("COLONNO","C902");
        this.put("COLORINA","C903");
        this.put("COLORNO","C904");
        this.put("COLOSIMI","C905");
        this.put("COLTURANO","C908");
        this.put("COLVERDE","M336");
        this.put("COLZATE","C910");
        this.put("COMABBIO","C911");
        this.put("COMACCHIO","C912");
        this.put("COMANO","C914");
        this.put("COMANO TERME","M314");
        this.put("COMAZZO","C917");
        this.put("COMEGLIANS","C918");
        this.put("COMELICO SUPERIORE","C920");
        this.put("COMERIO","C922");
        this.put("COMEZZANO CIZZAGO","C925");
        this.put("COMIGNAGO","C926");
        this.put("COMISO","C927");
        this.put("COMITINI","C928");
        this.put("COMIZIANO","C929");
        this.put("COMMESSAGGIO","C930");
        this.put("COMMEZZADURA","C931");
        this.put("COMO","C933");
        this.put("COMPIANO","C934");
        this.put("COMUN NUOVO","C937");
        this.put("COMUNANZA","C935");
        this.put("CONA","C938");
        this.put("CONCA CASALE","C941");
        this.put("CONCA DEI MARINI","C940");
        this.put("CONCA DELLA CAMPANIA","C939");
        this.put("CONCAMARISE","C943");
        this.put("CONCEI","C944");
        this.put("CONCERVIANO","C946");
        this.put("CONCESIO","C948");
        this.put("CONCO","C949");
        this.put("CONCORDIA SAGITTARIA","C950");
        this.put("CONCORDIA SULLA SECCHIA","C951");
        this.put("CONCOREZZO","C952");
        this.put("CONDINO","C953");
        this.put("CONDOFURI","C954");
        this.put("CONDOVE","C955");
        this.put("CONDRO'","C956");
        this.put("CONEGLIANO","C957");
        this.put("CONFIENZA","C958");
        this.put("CONFIGNI","C959");
        this.put("CONFLENTI","C960");
        this.put("CONIOLO","C962");
        this.put("CONSELICE","C963");
        this.put("CONSELVE","C964");
        this.put("CONSIGLIO DI RUMO","C965");
        this.put("CONTA'","M356");
        this.put("CONTESSA ENTELLINA","C968");
        this.put("CONTIGLIANO","C969");
        this.put("CONTRADA","C971");
        this.put("CONTROGUERRA","C972");
        this.put("CONTRONE","C973");
        this.put("CONTURSI TERME","C974");
        this.put("CONVERSANO","C975");
        this.put("CONZA DELLA CAMPANIA","C976");
        this.put("CONZANO","C977");
        this.put("COPERTINO","C978");
        this.put("COPIANO","C979");
        this.put("COPPARO","C980");
        this.put("CORANA","C982");
        this.put("CORATO","C983");
        this.put("CORBARA","C984");
        this.put("CORBETTA","C986");
        this.put("CORBOLA","C987");
        this.put("CORCHIANO","C988");
        this.put("CORCIANO","C990");
        this.put("CORDENONS","C991");
        this.put("CORDIGNANO","C992");
        this.put("CORDOVADO","C993");
        this.put("COREDO","C994");
        this.put("COREGLIA ANTELMINELLI","C996");
        this.put("COREGLIA LIGURE","C995");
        this.put("CORENO AUSONIO","C998");
        this.put("CORFINIO","C999");
        this.put("CORI","D003");
        this.put("CORIANO","D004");
        this.put("CORIGLIANO CALABRO","D005");
        this.put("CORIGLIANO D'OTRANTO","D006");
        this.put("CORIGLIANO ROSSANO","M403");
        this.put("CORINALDO","D007");
        this.put("CORIO","D008");
        this.put("CORLEONE","D009");
        this.put("CORLETO MONFORTE","D011");
        this.put("CORLETO PERTICARA","D010");
        this.put("CORMANO","D013");
        this.put("CORMONS","D014");
        this.put("CORNA IMAGNA","D015");
        this.put("CORNALBA","D016");
        this.put("CORNALE","D017");
        this.put("CORNALE E BASTIDA","M338");
        this.put("CORNAREDO","D018");
        this.put("CORNATE D'ADDA","D019");
        this.put("CORNEDO ALL'ISARCO .KARNEID.","B799");
        this.put("CORNEDO VICENTINO","D020");
        this.put("CORNEGLIANO LAUDENSE","D021");
        this.put("CORNELIANO D'ALBA","D022");
        this.put("CORNIGLIO","D026");
        this.put("CORNO DI ROSAZZO","D027");
        this.put("CORNO GIOVINE","D028");
        this.put("CORNOVECCHIO","D029");
        this.put("CORNUDA","D030");
        this.put("CORREGGIO","D037");
        this.put("CORREZZANA","D038");
        this.put("CORREZZOLA","D040");
        this.put("CORRIDO","D041");
        this.put("CORRIDONIA","D042");
        this.put("CORROPOLI","D043");
        this.put("CORSANO","D044");
        this.put("CORSICO","D045");
        this.put("CORSIONE","D046");
        this.put("CORTACCIA SULLA STRADA DEL VINO .KURTATSCH A.","D048");
        this.put("CORTALE","D049");
        this.put("CORTANDONE","D050");
        this.put("CORTANZE","D051");
        this.put("CORTAZZONE","D052");
        this.put("CORTE BRUGNATELLA","D054");
        this.put("CORTE DE' CORTESI CON CIGNONE","D056");
        this.put("CORTE DE' FRATI","D057");
        this.put("CORTE FRANCA","D058");
        this.put("CORTE PALASIO","D068");
        this.put("CORTEMAGGIORE","D061");
        this.put("CORTEMILIA","D062");
        this.put("CORTENO GOLGI","D064");
        this.put("CORTENOVA","D065");
        this.put("CORTENUOVA","D066");
        this.put("CORTEOLONA","D067");
        this.put("CORTEOLONA E GENZONE","M372");
        this.put("CORTIGLIONE","D072");
        this.put("CORTINA D'AMPEZZO","A266");
        this.put("CORTINA SULLA STRADA DEL VINO .KURTINIG AN D.","D075");
        this.put("CORTINO","D076");
        this.put("CORTONA","D077");
        this.put("CORVARA","D078");
        this.put("CORVARA IN BADIA .CORVARA.","D079");
        this.put("CORVINO SAN QUIRICO","D081");
        this.put("CORZANO","D082");
        this.put("COSEANO","D085");
        this.put("COSENZA","D086");
        this.put("COSIO D'ARROSCIA","D087");
        this.put("COSIO VALTELLINO","D088");
        this.put("COSOLETO","D089");
        this.put("COSSANO BELBO","D093");
        this.put("COSSANO CANAVESE","D092");
        this.put("COSSATO","D094");
        this.put("COSSERIA","D095");
        this.put("COSSIGNANO","D096");
        this.put("COSSOGNO","D099");
        this.put("COSSOINE","D100");
        this.put("COSSOMBRATO","D101");
        this.put("COSTA DE' NOBILI","D109");
        this.put("COSTA DI MEZZATE","D110");
        this.put("COSTA DI ROVIGO","D105");
        this.put("COSTA MASNAGA","D112");
        this.put("COSTA SERINA","D111");
        this.put("COSTA VALLE IMAGNA","D103");
        this.put("COSTA VESCOVATO","D102");
        this.put("COSTA VOLPINO","D117");
        this.put("COSTABISSARA","D107");
        this.put("COSTACCIARO","D108");
        this.put("COSTANZANA","D113");
        this.put("COSTARAINERA","D114");
        this.put("COSTERMANO SUL GARDA","D118");
        this.put("COSTIGLIOLE D'ASTI","D119");
        this.put("COSTIGLIOLE SALUZZO","D120");
        this.put("COTIGNOLA","D121");
        this.put("COTRONEI","D123");
        this.put("COTTANELLO","D124");
        this.put("COURMAYEUR","D012");
        this.put("COVO","D126");
        this.put("COZZO","D127");
        this.put("CRACO","D128");
        this.put("CRANDOLA VALSASSINA","D131");
        this.put("CRAVAGLIANA","D132");
        this.put("CRAVANZANA","D133");
        this.put("CRAVEGGIA","D134");
        this.put("CREAZZO","D136");
        this.put("CRECCHIO","D137");
        this.put("CREDARO","D139");
        this.put("CREDERA RUBBIANO","D141");
        this.put("CREMA","D142");
        this.put("CREMELLA","D143");
        this.put("CREMENAGA","D144");
        this.put("CREMENO","D145");
        this.put("CREMIA","D147");
        this.put("CREMOLINO","D149");
        this.put("CREMONA","D150");
        this.put("CREMOSANO","D151");
        this.put("CRESCENTINO","D154");
        this.put("CRESPADORO","D156");
        this.put("CRESPANO DEL GRAPPA","D157");
        this.put("CRESPELLANO","D158");
        this.put("CRESPIATICA","D159");
        this.put("CRESPINA","D160");
        this.put("CRESPINA LORENZANA","M328");
        this.put("CRESPINO","D161");
        this.put("CRESSA","D162");
        this.put("CREVACUORE","D165");
        this.put("CREVALCORE","D166");
        this.put("CREVOLADOSSOLA","D168");
        this.put("CRISPANO","D170");
        this.put("CRISPIANO","D171");
        this.put("CRISSOLO","D172");
        this.put("CROCEFIESCHI","D175");
        this.put("CROCETTA DEL MONTELLO","C670");
        this.put("CRODO","D177");
        this.put("CROGNALETO","D179");
        this.put("CROPALATI","D180");
        this.put("CROPANI","D181");
        this.put("CROSA","D182");
        this.put("CROSIA","D184");
        this.put("CROSIO DELLA VALLE","D185");
        this.put("CROTONE","D122");
        this.put("CROTTA D'ADDA","D186");
        this.put("CROVA","D187");
        this.put("CROVIANA","D188");
        this.put("CRUCOLI","D189");
        this.put("CUASSO AL MONTE","D192");
        this.put("CUCCARO MONFERRATO","D194");
        this.put("CUCCARO VETERE","D195");
        this.put("CUCCIAGO","D196");
        this.put("CUCEGLIO","D197");
        this.put("CUGGIONO","D198");
        this.put("CUGLIATE FABIASCO","D199");
        this.put("CUGLIERI","D200");
        this.put("CUGNOLI","D201");
        this.put("CUMIANA","D202");
        this.put("CUMIGNANO SUL NAVIGLIO","D203");
        this.put("CUNARDO","D204");
        this.put("CUNEO","D205");
        this.put("CUNEVO","D206");
        this.put("CUNICO","D207");
        this.put("CUORGNE'","D208");
        this.put("CUPELLO","D209");
        this.put("CUPRA MARITTIMA","D210");
        this.put("CUPRAMONTANA","D211");
        this.put("CURA CARPIGNANO","B824");
        this.put("CURCURIS","D214");
        this.put("CUREGGIO","D216");
        this.put("CURIGLIA CON MONTEVIASCO","D217");
        this.put("CURINGA","D218");
        this.put("CURINO","D219");
        this.put("CURNO","D221");
        this.put("CURON VENOSTA .GRAUN IM VINSCHGAU.","D222");
        this.put("CURSI","D223");
        this.put("CURSOLO ORASSO","D225");
        this.put("CURTAROLO","D226");
        this.put("CURTATONE","D227");
        this.put("CURTI","D228");
        this.put("CUSAGO","D229");
        this.put("CUSANO MILANINO","D231");
        this.put("CUSANO MUTRI","D230");
        this.put("CUSINO","D232");
        this.put("CUSIO","D233");
        this.put("CUSTONACI","D234");
        this.put("CUTIGLIANO","D235");
        this.put("CUTRO","D236");
        this.put("CUTROFIANO","D237");
        this.put("CUVEGLIO","D238");
        this.put("CUVIO","D239");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
