package libreria_sibilia.codicefiscale.document ;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_LMN extends HashMap<String, String> {

    public CitiesCodes_LMN(){
        this.put("LA CASSA","E394");
        this.put("LA LOGGIA","E423");
        this.put("LA MADDALENA","E425");
        this.put("LA MAGDELEINE","A308");
        this.put("LA MORRA","E430");
        this.put("LA SALLE","E458");
        this.put("LA SPEZIA","E463");
        this.put("LA THUILE","E470");
        this.put("LA VALLE AGORDINA","E490");
        this.put("LA VALLE .WENGEN.","E491");
        this.put("LA VALLETTA BRIANZA","M348");
        this.put("LABICO","E392");
        this.put("LABRO","E393");
        this.put("LACCHIARELLA","E395");
        this.put("LACCO AMENO","E396");
        this.put("LACEDONIA","E397");
        this.put("LACES .LATSCH.","E398");
        this.put("LACONI","E400");
        this.put("LADISPOLI","M212");
        this.put("LAERRU","E401");
        this.put("LAGANADI","E402");
        this.put("LAGHI","E403");
        this.put("LAGLIO","E405");
        this.put("LAGNASCO","E406");
        this.put("LAGO","E407");
        this.put("LAGONEGRO","E409");
        this.put("LAGOSANTO","E410");
        this.put("LAGUNDO .ALGUND.","E412");
        this.put("LAIGUEGLIA","E414");
        this.put("LAINATE","E415");
        this.put("LAINO","E416");
        this.put("LAINO BORGO","E417");
        this.put("LAINO CASTELLO","E419");
        this.put("LAION .LAJEN.","E420");
        this.put("LAIVES .LEIFERS.","E421");
        this.put("LAJATICO","E413");
        this.put("LALLIO","E422");
        this.put("LAMA DEI PELIGNI","E424");
        this.put("LAMA MOCOGNO","E426");
        this.put("LAMBRUGO","E428");
        this.put("LAMEZIA TERME","M208");
        this.put("LAMON","E429");
        this.put("LAMPEDUSA E LINOSA","E431");
        this.put("LAMPORECCHIO","E432");
        this.put("LAMPORO","E433");
        this.put("LANA .LANA.","E434");
        this.put("LANCIANO","E435");
        this.put("LANDIONA","E436");
        this.put("LANDRIANO","E437");
        this.put("LANGHIRANO","E438");
        this.put("LANGOSCO","E439");
        this.put("LANUSEI","E441");
        this.put("LANUVIO","C767");
        this.put("LANZADA","E443");
        this.put("LANZO D'INTELVI","E444");
        this.put("LANZO TORINESE","E445");
        this.put("LAPEDONA","E447");
        this.put("LAPIO","E448");
        this.put("LAPPANO","E450");
        this.put("L'AQUILA","A345");
        this.put("LARCIANO","E451");
        this.put("LARDARO","E452");
        this.put("LARDIRAGO","E454");
        this.put("LARI","E455");
        this.put("LARIANO","M207");
        this.put("LARINO","E456");
        this.put("LAS PLASSAS","E464");
        this.put("LASA .LAAS.","E457");
        this.put("LASCARI","E459");
        this.put("LASINO","E461");
        this.put("LASNIGO","E462");
        this.put("LASTEBASSE","E465");
        this.put("LASTRA A SIGNA","E466");
        this.put("LATERA","E467");
        this.put("LATERINA","E468");
        this.put("LATERINA PERGINE VALDARNO","M392");
        this.put("LATERZA","E469");
        this.put("LATIANO","E471");
        this.put("LATINA","E472");
        this.put("LATISANA","E473");
        this.put("LATRONICO","E474");
        this.put("LATTARICO","E475");
        this.put("LAUCO","E476");
        this.put("LAUREANA CILENTO","E480");
        this.put("LAUREANA DI BORRELLO","E479");
        this.put("LAUREGNO .LAUREIN.","E481");
        this.put("LAURENZANA","E482");
        this.put("LAURIA","E483");
        this.put("LAURIANO","E484");
        this.put("LAURINO","E485");
        this.put("LAURITO","E486");
        this.put("LAURO","E487");
        this.put("LAVAGNA","E488");
        this.put("LAVAGNO","E489");
        this.put("LAVARONE","E492");
        this.put("LAVELLO","E493");
        this.put("LAVENA PONTE TRESA","E494");
        this.put("LAVENO MOMBELLO","E496");
        this.put("LAVENONE","E497");
        this.put("LAVIANO","E498");
        this.put("LAVIS","E500");
        this.put("LAZISE","E502");
        this.put("LAZZATE","E504");
        this.put("LECCE","E506");
        this.put("LECCE NEI MARSI","E505");
        this.put("LECCO","E507");
        this.put("LEDRO","M313");
        this.put("LEFFE","E509");
        this.put("LEGGIUNO","E510");
        this.put("LEGNAGO","E512");
        this.put("LEGNANO","E514");
        this.put("LEGNARO","E515");
        this.put("LEI","E517");
        this.put("LEINI","E518");
        this.put("LEIVI","E519");
        this.put("LEMIE","E520");
        this.put("LENDINARA","E522");
        this.put("LENI","E523");
        this.put("LENNA","E524");
        this.put("LENNO","E525");
        this.put("LENO","E526");
        this.put("LENOLA","E527");
        this.put("LENTA","E528");
        this.put("LENTATE SUL SEVESO","E530");
        this.put("LENTELLA","E531");
        this.put("LENTIAI","C562");
        this.put("LENTINI","E532");
        this.put("LEONESSA","E535");
        this.put("LEONFORTE","E536");
        this.put("LEPORANO","E537");
        this.put("LEQUILE","E538");
        this.put("LEQUIO BERRIA","E540");
        this.put("LEQUIO TANARO","E539");
        this.put("LERCARA FRIDDI","E541");
        this.put("LERICI","E542");
        this.put("LERMA","E543");
        this.put("LESA","E544");
        this.put("LESEGNO","E546");
        this.put("LESIGNANO DE' BAGNI","E547");
        this.put("LESINA","E549");
        this.put("LESMO","E550");
        this.put("LESSOLO","E551");
        this.put("LESSONA","E552");
        this.put("LESSONA","M371");
        this.put("LESTIZZA","E553");
        this.put("LETINO","E554");
        this.put("LETOJANNI","E555");
        this.put("LETTERE","E557");
        this.put("LETTOMANOPPELLO","E558");
        this.put("LETTOPALENA","E559");
        this.put("LEVANTO","E560");
        this.put("LEVATE","E562");
        this.put("LEVERANO","E563");
        this.put("LEVICE","E564");
        this.put("LEVICO TERME","E565");
        this.put("LEVONE","E566");
        this.put("LEZZENO","E569");
        this.put("LIBERI","E570");
        this.put("LIBRIZZI","E571");
        this.put("LICATA","E573");
        this.put("LICCIANA NARDI","E574");
        this.put("LICENZA","E576");
        this.put("LICODIA EUBEA","E578");
        this.put("LIERNA","E581");
        this.put("LIGNANA","E583");
        this.put("LIGNANO SABBIADORO","E584");
        this.put("LIGONCHIO","E585");
        this.put("LIGOSULLO","E586");
        this.put("LILLIANES","E587");
        this.put("LIMANA","E588");
        this.put("LIMATOLA","E589");
        this.put("LIMBADI","E590");
        this.put("LIMBIATE","E591");
        this.put("LIMENA","E592");
        this.put("LIMIDO COMASCO","E593");
        this.put("LIMINA","E594");
        this.put("LIMONE PIEMONTE","E597");
        this.put("LIMONE SUL GARDA","E596");
        this.put("LIMOSANO","E599");
        this.put("LINAROLO","E600");
        this.put("LINGUAGLOSSA","E602");
        this.put("LIONI","E605");
        this.put("LIPARI","E606");
        this.put("LIPOMO","E607");
        this.put("LIRIO","E608");
        this.put("LISCATE","E610");
        this.put("LISCIA","E611");
        this.put("LISCIANO NICCONE","E613");
        this.put("LISIGNAGO","E614");
        this.put("LISIO","E615");
        this.put("LISSONE","E617");
        this.put("LIVERI","E620");
        this.put("LIVIGNO","E621");
        this.put("LIVINALLONGO DEL COL DI LANA","E622");
        this.put("LIVO","E624");
        this.put("LIVO","E623");
        this.put("LIVORNO","E625");
        this.put("LIVORNO FERRARIS","E626");
        this.put("LIVRAGA","E627");
        this.put("LIZZANELLO","E629");
        this.put("LIZZANO","E630");
        this.put("LIZZANO IN BELVEDERE","A771");
        this.put("LOANO","E632");
        this.put("LOAZZOLO","E633");
        this.put("LOCANA","E635");
        this.put("LOCATE DI TRIULZI","E639");
        this.put("LOCATE VARESINO","E638");
        this.put("LOCATELLO","E640");
        this.put("LOCERI","E644");
        this.put("LOCOROTONDO","E645");
        this.put("LOCRI","D976");
        this.put("LOCULI","E646");
        this.put("LODE'","E647");
        this.put("LODI","E648");
        this.put("LODI VECCHIO","E651");
        this.put("LODINE","E649");
        this.put("LODRINO","E652");
        this.put("LOGRATO","E654");
        this.put("LOIANO","E655");
        this.put("LOIRI PORTO SAN PAOLO","M275");
        this.put("LOMAGNA","E656");
        this.put("LOMASO","E658");
        this.put("LOMAZZO","E659");
        this.put("LOMBARDORE","E660");
        this.put("LOMBRIASCO","E661");
        this.put("LOMELLO","E662");
        this.put("LONA LASES","E664");
        this.put("LONATE CEPPINO","E665");
        this.put("LONATE POZZOLO","E666");
        this.put("LONATO","E667");
        this.put("LONATO DEL GARDA","M312");
        this.put("LONDA","E668");
        this.put("LONGANO","E669");
        this.put("LONGARE","E671");
        this.put("LONGARONE","E672");
        this.put("LONGARONE","M342");
        this.put("LONGHENA","E673");
        this.put("LONGI","E674");
        this.put("LONGIANO","E675");
        this.put("LONGOBARDI","E677");
        this.put("LONGOBUCCO","E678");
        this.put("LONGONE AL SEGRINO","E679");
        this.put("LONGONE SABINO","E681");
        this.put("LONIGO","E682");
        this.put("LORANZE'","E683");
        this.put("LOREGGIA","E684");
        this.put("LOREGLIA","E685");
        this.put("LORENZAGO DI CADORE","E687");
        this.put("LORENZANA","E688");
        this.put("LOREO","E689");
        this.put("LORETO","E690");
        this.put("LORETO APRUTINO","E691");
        this.put("LORIA","E692");
        this.put("LORO CIUFFENNA","E693");
        this.put("LORO PICENO","E694");
        this.put("LORSICA","E695");
        this.put("LOSINE","E698");
        this.put("LOTZORAI","E700");
        this.put("LOVERE","E704");
        this.put("LOVERO","E705");
        this.put("LOZIO","E706");
        this.put("LOZZA","E707");
        this.put("LOZZO ATESTINO","E709");
        this.put("LOZZO DI CADORE","E708");
        this.put("LOZZOLO","E711");
        this.put("LU","E712");
        this.put("LU E CUCCARO MONFERRATO","M420");
        this.put("LUBRIANO","E713");
        this.put("LUCCA","E715");
        this.put("LUCCA SICULA","E714");
        this.put("LUCERA","E716");
        this.put("LUCIGNANO","E718");
        this.put("LUCINASCO","E719");
        this.put("LUCITO","E722");
        this.put("LUCO DEI MARSI","E723");
        this.put("LUCOLI","E724");
        this.put("LUGAGNANO VAL D'ARDA","E726");
        this.put("LUGNACCO","E727");
        this.put("LUGNANO IN TEVERINA","E729");
        this.put("LUGO","E730");
        this.put("LUGO DI VICENZA","E731");
        this.put("LUINO","E734");
        this.put("LUISAGO","E735");
        this.put("LULA","E736");
        this.put("LUMARZO","E737");
        this.put("LUMEZZANE","E738");
        this.put("LUNAMATRONA","E742");
        this.put("LUNANO","E743");
        this.put("LUNGAVILLA","B387");
        this.put("LUNGRO","E745");
        this.put("LUNI","G143");
        this.put("LUOGOSANO","E746");
        this.put("LUOGOSANTO","E747");
        this.put("LUPARA","E748");
        this.put("LURAGO D'ERBA","E749");
        this.put("LURAGO MARINONE","E750");
        this.put("LURANO","E751");
        this.put("LURAS","E752");
        this.put("LURATE CACCIVIO","E753");
        this.put("LUSCIANO","E754");
        this.put("LUSERNA","E757");
        this.put("LUSERNA SAN GIOVANNI","E758");
        this.put("LUSERNETTA","E759");
        this.put("LUSEVERA","E760");
        this.put("LUSIA","E761");
        this.put("LUSIANA","E762");
        this.put("LUSIANA CONCO","M427");
        this.put("LUSIGLIE'","E763");
        this.put("LUSON .LUESEN.","E764");
        this.put("LUSTRA","E767");
        this.put("LUVINATE","E769");
        this.put("LUZZANA","E770");
        this.put("LUZZARA","E772");
        this.put("LUZZI","E773");
        this.put("MACCAGNO","E775");
        this.put("MACCAGNO CON PINO E VEDDASCA","M339");
        this.put("MACCASTORNA","E777");
        this.put("MACCHIA D'ISERNIA","E778");
        this.put("MACCHIA VALFORTORE","E780");
        this.put("MACCHIAGODENA","E779");
        this.put("MACELLO","E782");
        this.put("MACERATA","E783");
        this.put("MACERATA CAMPANIA","E784");
        this.put("MACERATA FELTRIA","E785");
        this.put("MACHERIO","E786");
        this.put("MACLODIO","E787");
        this.put("MACOMER","E788");
        this.put("MACRA","E789");
        this.put("MACUGNAGA","E790");
        this.put("MADDALONI","E791");
        this.put("MADESIMO","E342");
        this.put("MADIGNANO","E793");
        this.put("MADONE","E794");
        this.put("MADONNA DEL SASSO","E795");
        this.put("MADRUZZO","M357");
        this.put("MAENZA","E798");
        this.put("MAFALDA","E799");
        this.put("MAGASA","E800");
        this.put("MAGENTA","E801");
        this.put("MAGGIORA","E803");
        this.put("MAGHERNO","E804");
        this.put("MAGIONE","E805");
        this.put("MAGISANO","E806");
        this.put("MAGLIANO ALFIERI","E809");
        this.put("MAGLIANO ALPI","E808");
        this.put("MAGLIANO DE' MARSI","E811");
        this.put("MAGLIANO DI TENNA","E807");
        this.put("MAGLIANO IN TOSCANA","E810");
        this.put("MAGLIANO ROMANO","E813");
        this.put("MAGLIANO SABINA","E812");
        this.put("MAGLIANO VETERE","E814");
        this.put("MAGLIE","E815");
        this.put("MAGLIOLO","E816");
        this.put("MAGLIONE","E817");
        this.put("MAGNACAVALLO","E818");
        this.put("MAGNAGO","E819");
        this.put("MAGNANO","E821");
        this.put("MAGNANO IN RIVIERA","E820");
        this.put("MAGOMADAS","E825");
        this.put("MAGRE' SULLA STRADA DEL VINO .MARGREID AN DE.","E829");
        this.put("MAGREGLIO","E830");
        this.put("MAIDA","E834");
        this.put("MAIERA'","E835");
        this.put("MAIERATO","E836");
        this.put("MAIOLATI SPONTINI","E837");
        this.put("MAIOLO","E838");
        this.put("MAIORI","E839");
        this.put("MAIRAGO","E840");
        this.put("MAIRANO","E841");
        this.put("MAISSANA","E842");
        this.put("MAJANO","E833");
        this.put("MALAGNINO","E843");
        this.put("MALALBERGO","E844");
        this.put("MALBORGHETTO VALBRUNA","E847");
        this.put("MALCESINE","E848");
        this.put("MALE'","E850");
        this.put("MALEGNO","E851");
        this.put("MALEO","E852");
        this.put("MALESCO","E853");
        this.put("MALETTO","E854");
        this.put("MALFA","E855");
        this.put("MALGESSO","E856");
        this.put("MALGRATE","E858");
        this.put("MALITO","E859");
        this.put("MALLARE","E860");
        this.put("MALLES VENOSTA .MALS.","E862");
        this.put("MALNATE","E863");
        this.put("MALO","E864");
        this.put("MALONNO","E865");
        this.put("MALOSCO","E866");
        this.put("MALTIGNANO","E868");
        this.put("MALVAGNA","E869");
        this.put("MALVICINO","E870");
        this.put("MALVITO","E872");
        this.put("MAMMOLA","E873");
        this.put("MAMOIADA","E874");
        this.put("MANCIANO","E875");
        this.put("MANDANICI","E876");
        this.put("MANDAS","E877");
        this.put("MANDATORICCIO","E878");
        this.put("MANDELA","B632");
        this.put("MANDELLO DEL LARIO","E879");
        this.put("MANDELLO VITTA","E880");
        this.put("MANDURIA","E882");
        this.put("MANERBA DEL GARDA","E883");
        this.put("MANERBIO","E884");
        this.put("MANFREDONIA","E885");
        this.put("MANGO","E887");
        this.put("MANGONE","E888");
        this.put("MANIACE","M283");
        this.put("MANIAGO","E889");
        this.put("MANOCALZATI","E891");
        this.put("MANOPPELLO","E892");
        this.put("MANSUE'","E893");
        this.put("MANTA","E894");
        this.put("MANTELLO","E896");
        this.put("MANTOVA","E897");
        this.put("MANZANO","E899");
        this.put("MANZIANA","E900");
        this.put("MAPELLO","E901");
        this.put("MAPPANO","M316");
        this.put("MARA","E902");
        this.put("MARACALAGONIS","E903");
        this.put("MARANELLO","E904");
        this.put("MARANO DI NAPOLI","E906");
        this.put("MARANO DI VALPOLICELLA","E911");
        this.put("MARANO EQUO","E908");
        this.put("MARANO LAGUNARE","E910");
        this.put("MARANO MARCHESATO","E914");
        this.put("MARANO PRINCIPATO","E915");
        this.put("MARANO SUL PANARO","E905");
        this.put("MARANO TICINO","E907");
        this.put("MARANO VICENTINO","E912");
        this.put("MARANZANA","E917");
        this.put("MARATEA","E919");
        this.put("MARCALLO CON CASONE","E921");
        this.put("MARCARIA","E922");
        this.put("MARCEDUSA","E923");
        this.put("MARCELLINA","E924");
        this.put("MARCELLINARA","E925");
        this.put("MARCETELLI","E927");
        this.put("MARCHENO","E928");
        this.put("MARCHIROLO","E929");
        this.put("MARCIANA","E930");
        this.put("MARCIANA MARINA","E931");
        this.put("MARCIANISE","E932");
        this.put("MARCIANO DELLA CHIANA","E933");
        this.put("MARCIGNAGO","E934");
        this.put("MARCON","E936");
        this.put("MAREBBE .ENNEBERG.","E938");
        this.put("MARENE","E939");
        this.put("MARENO DI PIAVE","E940");
        this.put("MARENTINO","E941");
        this.put("MARETTO","E944");
        this.put("MARGARITA","E945");
        this.put("MARGHERITA DI SAVOIA","E946");
        this.put("MARGNO","E947");
        this.put("MARIANA MANTOVANA","E949");
        this.put("MARIANO COMENSE","E951");
        this.put("MARIANO DEL FRIULI","E952");
        this.put("MARIANOPOLI","E953");
        this.put("MARIGLIANELLA","E954");
        this.put("MARIGLIANO","E955");
        this.put("MARINA DI GIOIOSA IONICA","E956");
        this.put("MARINEO","E957");
        this.put("MARINO","E958");
        this.put("MARLENGO .MARLING.","E959");
        this.put("MARLIANA","E960");
        this.put("MARMENTINO","E961");
        this.put("MARMIROLO","E962");
        this.put("MARMORA","E963");
        this.put("MARNATE","E965");
        this.put("MARONE","E967");
        this.put("MAROPATI","E968");
        this.put("MAROSTICA","E970");
        this.put("MARRADI","E971");
        this.put("MARRUBIU","E972");
        this.put("MARSAGLIA","E973");
        this.put("MARSALA","E974");
        this.put("MARSCIANO","E975");
        this.put("MARSICO NUOVO","E976");
        this.put("MARSICOVETERE","E977");
        this.put("MARTA","E978");
        this.put("MARTANO","E979");
        this.put("MARTELLAGO","E980");
        this.put("MARTELLO .MARTELL.","E981");
        this.put("MARTIGNACCO","E982");
        this.put("MARTIGNANA DI PO","E983");
        this.put("MARTIGNANO","E984");
        this.put("MARTINA FRANCA","E986");
        this.put("MARTINENGO","E987");
        this.put("MARTINIANA PO","E988");
        this.put("MARTINSICURO","E989");
        this.put("MARTIRANO","E990");
        this.put("MARTIRANO LOMBARDO","E991");
        this.put("MARTIS","E992");
        this.put("MARTONE","E993");
        this.put("MARUDO","E994");
        this.put("MARUGGIO","E995");
        this.put("MARZABOTTO","B689");
        this.put("MARZANO","E999");
        this.put("MARZANO APPIO","E998");
        this.put("MARZANO DI NOLA","E997");
        this.put("MARZI","F001");
        this.put("MARZIO","F002");
        this.put("MASAINAS","M270");
        this.put("MASATE","F003");
        this.put("MASCALI","F004");
        this.put("MASCALUCIA","F005");
        this.put("MASCHITO","F006");
        this.put("MASCIAGO PRIMO","F007");
        this.put("MASER","F009");
        this.put("MASERA","F010");
        this.put("MASERA' DI PADOVA","F011");
        this.put("MASERADA SUL PIAVE","F012");
        this.put("MASI","F013");
        this.put("MASI TORELLO","F016");
        this.put("MASIO","F015");
        this.put("MASLIANICO","F017");
        this.put("MASON VICENTINO","F019");
        this.put("MASONE","F020");
        this.put("MASSA","F023");
        this.put("MASSA D'ALBE","F022");
        this.put("MASSA DI SOMMA","M289");
        this.put("MASSA E COZZILE","F025");
        this.put("MASSA FERMANA","F021");
        this.put("MASSA FISCAGLIA","F026");
        this.put("MASSA LOMBARDA","F029");
        this.put("MASSA LUBRENSE","F030");
        this.put("MASSA MARITTIMA","F032");
        this.put("MASSA MARTANA","F024");
        this.put("MASSAFRA","F027");
        this.put("MASSALENGO","F028");
        this.put("MASSANZAGO","F033");
        this.put("MASSAROSA","F035");
        this.put("MASSAZZA","F037");
        this.put("MASSELLO","F041");
        this.put("MASSERANO","F042");
        this.put("MASSIGNANO","F044");
        this.put("MASSIMENO","F045");
        this.put("MASSIMINO","F046");
        this.put("MASSINO VISCONTI","F047");
        this.put("MASSIOLA","F048");
        this.put("MASULLAS","F050");
        this.put("MATELICA","F051");
        this.put("MATERA","F052");
        this.put("MATHI","F053");
        this.put("MATINO","F054");
        this.put("MATRICE","F055");
        this.put("MATTIE","F058");
        this.put("MATTINATA","F059");
        this.put("MAZARA DEL VALLO","F061");
        this.put("MAZZANO","F063");
        this.put("MAZZANO ROMANO","F064");
        this.put("MAZZARINO","F065");
        this.put("MAZZARRA' SANT'ANDREA","F066");
        this.put("MAZZARRONE","M271");
        this.put("MAZZE'","F067");
        this.put("MAZZIN","F068");
        this.put("MAZZO DI VALTELLINA","F070");
        this.put("MEANA DI SUSA","F074");
        this.put("MEANA SARDO","F073");
        this.put("MEDA","F078");
        this.put("MEDE","F080");
        this.put("MEDEA","F081");
        this.put("MEDESANO","F082");
        this.put("MEDICINA","F083");
        this.put("MEDIGLIA","F084");
        this.put("MEDOLAGO","F085");
        this.put("MEDOLE","F086");
        this.put("MEDOLLA","F087");
        this.put("MEDUNA DI LIVENZA","F088");
        this.put("MEDUNO","F089");
        this.put("MEGLIADINO SAN FIDENZIO","F091");
        this.put("MEGLIADINO SAN VITALE","F092");
        this.put("MEINA","F093");
        this.put("MEL","F094");
        this.put("MELARA","F095");
        this.put("MELAZZO","F096");
        this.put("MELDOLA","F097");
        this.put("MELE","F098");
        this.put("MELEGNANO","F100");
        this.put("MELENDUGNO","F101");
        this.put("MELETI","F102");
        this.put("MELFI","F104");
        this.put("MELICUCCA'","F105");
        this.put("MELICUCCO","F106");
        this.put("MELILLI","F107");
        this.put("MELISSA","F108");
        this.put("MELISSANO","F109");
        this.put("MELITO DI NAPOLI","F111");
        this.put("MELITO DI PORTO SALVO","F112");
        this.put("MELITO IRPINO","F110");
        this.put("MELIZZANO","F113");
        this.put("MELLE","F114");
        this.put("MELLO","F115");
        this.put("MELPIGNANO","F117");
        this.put("MELTINA .MOELTEN.","F118");
        this.put("MELZO","F119");
        this.put("MENAGGIO","F120");
        this.put("MENAROLA","F121");
        this.put("MENCONICO","F122");
        this.put("MENDATICA","F123");
        this.put("MENDICINO","F125");
        this.put("MENFI","F126");
        this.put("MENTANA","F127");
        this.put("MEOLO","F130");
        this.put("MERANA","F131");
        this.put("MERANO .MERAN.","F132");
        this.put("MERATE","F133");
        this.put("MERCALLO","F134");
        this.put("MERCATELLO SUL METAURO","F135");
        this.put("MERCATINO CONCA","F136");
        this.put("MERCATO SAN SEVERINO","F138");
        this.put("MERCATO SARACENO","F139");
        this.put("MERCENASCO","F140");
        this.put("MERCOGLIANO","F141");
        this.put("MERETO DI TOMBA","F144");
        this.put("MERGO","F145");
        this.put("MERGOZZO","F146");
        this.put("MERI'","F147");
        this.put("MERLARA","F148");
        this.put("MERLINO","F149");
        this.put("MERONE","F151");
        this.put("MESAGNE","F152");
        this.put("MESE","F153");
        this.put("MESENZANA","F154");
        this.put("MESERO","F155");
        this.put("MESOLA","F156");
        this.put("MESORACA","F157");
        this.put("MESSINA","F158");
        this.put("MESTRINO","F161");
        this.put("META","F162");
        this.put("MEUGLIANO","F164");
        this.put("MEZZAGO","F165");
        this.put("MEZZANA","F168");
        this.put("MEZZANA BIGLI","F170");
        this.put("MEZZANA MORTIGLIENGO","F167");
        this.put("MEZZANA RABATTONE","F171");
        this.put("MEZZANE DI SOTTO","F172");
        this.put("MEZZANEGO","F173");
        this.put("MEZZANI","F174");
        this.put("MEZZANINO","F175");
        this.put("MEZZANO","F176");
        this.put("MEZZEGRA","F181");
        this.put("MEZZENILE","F182");
        this.put("MEZZOCORONA","F183");
        this.put("MEZZOJUSO","F184");
        this.put("MEZZOLDO","F186");
        this.put("MEZZOLOMBARDO","F187");
        this.put("MEZZOMERICO","F188");
        this.put("MIAGLIANO","F189");
        this.put("MIANE","F190");
        this.put("MIASINO","F191");
        this.put("MIAZZINA","F192");
        this.put("MICIGLIANO","F193");
        this.put("MIGGIANO","F194");
        this.put("MIGLIANICO","F196");
        this.put("MIGLIARINO","F198");
        this.put("MIGLIARO","F199");
        this.put("MIGLIERINA","F200");
        this.put("MIGLIONICO","F201");
        this.put("MIGNANEGO","F202");
        this.put("MIGNANO MONTE LUNGO","F203");
        this.put("MILANO","F205");
        this.put("MILAZZO","F206");
        this.put("MILENA","E618");
        this.put("MILETO","F207");
        this.put("MILIS","F208");
        this.put("MILITELLO IN VAL DI CATANIA","F209");
        this.put("MILITELLO ROSMARINO","F210");
        this.put("MILLESIMO","F213");
        this.put("MILO","F214");
        this.put("MILZANO","F216");
        this.put("MINEO","F217");
        this.put("MINERBE","F218");
        this.put("MINERBIO","F219");
        this.put("MINERVINO DI LECCE","F221");
        this.put("MINERVINO MURGE","F220");
        this.put("MINORI","F223");
        this.put("MINTURNO","F224");
        this.put("MINUCCIANO","F225");
        this.put("MIOGLIA","F226");
        this.put("MIRA","F229");
        this.put("MIRABELLA ECLANO","F230");
        this.put("MIRABELLA IMBACCARI","F231");
        this.put("MIRABELLO","F235");
        this.put("MIRABELLO MONFERRATO","F232");
        this.put("MIRABELLO SANNITICO","F233");
        this.put("MIRADOLO TERME","F238");
        this.put("MIRANDA","F239");
        this.put("MIRANDOLA","F240");
        this.put("MIRANO","F241");
        this.put("MIRTO","F242");
        this.put("MISANO ADRIATICO","F244");
        this.put("MISANO DI GERA D'ADDA","F243");
        this.put("MISILISCEMI","M432");
        this.put("MISILMERI","F246");
        this.put("MISINTO","F247");
        this.put("MISSAGLIA","F248");
        this.put("MISSANELLO","F249");
        this.put("MISTERBIANCO","F250");
        this.put("MISTRETTA","F251");
        this.put("MOASCA","F254");
        this.put("MOCONESI","F256");
        this.put("MODENA","F257");
        this.put("MODICA","F258");
        this.put("MODIGLIANA","F259");
        this.put("MODOLO","F261");
        this.put("MODUGNO","F262");
        this.put("MOENA","F263");
        this.put("MOGGIO","F265");
        this.put("MOGGIO UDINESE","F266");
        this.put("MOGLIA","F267");
        this.put("MOGLIANO","F268");
        this.put("MOGLIANO VENETO","F269");
        this.put("MOGORELLA","F270");
        this.put("MOGORO","F272");
        this.put("MOIANO","F274");
        this.put("MOIMACCO","F275");
        this.put("MOIO ALCANTARA","F277");
        this.put("MOIO DE' CALVI","F276");
        this.put("MOIO DELLA CIVITELLA","F278");
        this.put("MOIOLA","F279");
        this.put("MOLA DI BARI","F280");
        this.put("MOLARE","F281");
        this.put("MOLAZZANA","F283");
        this.put("MOLFETTA","F284");
        this.put("MOLINA ATERNO","M255");
        this.put("MOLINA DI LEDRO","F286");
        this.put("MOLINARA","F287");
        this.put("MOLINELLA","F288");
        this.put("MOLINI DI TRIORA","F290");
        this.put("MOLINO DEI TORTI","F293");
        this.put("MOLISE","F294");
        this.put("MOLITERNO","F295");
        this.put("MOLLIA","F297");
        this.put("MOLOCHIO","F301");
        this.put("MOLTENO","F304");
        this.put("MOLTRASIO","F305");
        this.put("MOLVENA","F306");
        this.put("MOLVENO","F307");
        this.put("MOMBALDONE","F308");
        this.put("MOMBARCARO","F309");
        this.put("MOMBAROCCIO","F310");
        this.put("MOMBARUZZO","F311");
        this.put("MOMBASIGLIO","F312");
        this.put("MOMBELLO DI TORINO","F315");
        this.put("MOMBELLO MONFERRATO","F313");
        this.put("MOMBERCELLI","F316");
        this.put("MOMO","F317");
        this.put("MOMPANTERO","F318");
        this.put("MOMPEO","F319");
        this.put("MOMPERONE","F320");
        this.put("MONACILIONI","F322");
        this.put("MONALE","F323");
        this.put("MONASTERACE","F324");
        this.put("MONASTERO BORMIDA","F325");
        this.put("MONASTERO DI LANZO","F327");
        this.put("MONASTERO DI VASCO","F326");
        this.put("MONASTEROLO CASOTTO","F329");
        this.put("MONASTEROLO DEL CASTELLO","F328");
        this.put("MONASTEROLO DI SAVIGLIANO","F330");
        this.put("MONASTIER DI TREVISO","F332");
        this.put("MONASTIR","F333");
        this.put("MONCALIERI","F335");
        this.put("MONCALVO","F336");
        this.put("MONCENISIO","D553");
        this.put("MONCESTINO","F337");
        this.put("MONCHIERO","F338");
        this.put("MONCHIO DELLE CORTI","F340");
        this.put("MONCLASSICO","F341");
        this.put("MONCRIVELLO","F342");
        this.put("MONCUCCO TORINESE","F343");
        this.put("MONDAINO","F346");
        this.put("MONDAVIO","F347");
        this.put("MONDOLFO","F348");
        this.put("MONDOVI'","F351");
        this.put("MONDRAGONE","F352");
        this.put("MONEGLIA","F354");
        this.put("MONESIGLIO","F355");
        this.put("MONFALCONE","F356");
        this.put("MONFORTE D'ALBA","F358");
        this.put("MONFORTE SAN GIORGIO","F359");
        this.put("MONFUMO","F360");
        this.put("MONGARDINO","F361");
        this.put("MONGHIDORO","F363");
        this.put("MONGIANA","F364");
        this.put("MONGIARDINO LIGURE","F365");
        this.put("MONGIUFFI MELIA","F368");
        this.put("MONGRANDO","F369");
        this.put("MONGRASSANO","F370");
        this.put("MONGUELFO TESIDO WELSBERG TAISTEN","F371");
        this.put("MONGUZZO","F372");
        this.put("MONIGA DEL GARDA","F373");
        this.put("MONLEALE","F374");
        this.put("MONNO","F375");
        this.put("MONOPOLI","F376");
        this.put("MONREALE","F377");
        this.put("MONRUPINO","F378");
        this.put("MONSAMPIETRO MORICO","F379");
        this.put("MONSAMPOLO DEL TRONTO","F380");
        this.put("MONSANO","F381");
        this.put("MONSELICE","F382");
        this.put("MONSERRATO","F383");
        this.put("MONSUMMANO TERME","F384");
        this.put("MONTA'","F385");
        this.put("MONTABONE","F386");
        this.put("MONTACUTO","F387");
        this.put("MONTAFIA","F390");
        this.put("MONTAGANO","F391");
        this.put("MONTAGNA IN VALTELLINA","F393");
        this.put("MONTAGNA .MONTAN.","F392");
        this.put("MONTAGNANA","F394");
        this.put("MONTAGNAREALE","F395");
        this.put("MONTAGNE","F396");
        this.put("MONTAGUTO","F397");
        this.put("MONTAIONE","F398");
        this.put("MONTALBANO ELICONA","F400");
        this.put("MONTALBANO JONICO","F399");
        this.put("MONTALCINO","F402");
        this.put("MONTALCINO","M378");
        this.put("MONTALDEO","F403");
        this.put("MONTALDO BORMIDA","F404");
        this.put("MONTALDO DI MONDOVI'","F405");
        this.put("MONTALDO ROERO","F408");
        this.put("MONTALDO SCARAMPI","F409");
        this.put("MONTALDO TORINESE","F407");
        this.put("MONTALE","F410");
        this.put("MONTALENGHE","F411");
        this.put("MONTALLEGRO","F414");
        this.put("MONTALTO CARPASIO","M387");
        this.put("MONTALTO DELLE MARCHE","F415");
        this.put("MONTALTO DI CASTRO","F419");
        this.put("MONTALTO DORA","F420");
        this.put("MONTALTO LIGURE","F406");
        this.put("MONTALTO PAVESE","F417");
        this.put("MONTALTO UFFUGO","F416");
        this.put("MONTANARO","F422");
        this.put("MONTANASO LOMBARDO","F423");
        this.put("MONTANERA","F424");
        this.put("MONTANO ANTILIA","F426");
        this.put("MONTANO LUCINO","F427");
        this.put("MONTAPPONE","F428");
        this.put("MONTAQUILA","F429");
        this.put("MONTASOLA","F430");
        this.put("MONTAURO","F432");
        this.put("MONTAZZOLI","F433");
        this.put("MONTE ARGENTARIO","F437");
        this.put("MONTE CASTELLO DI VIBIO","F456");
        this.put("MONTE CAVALLO","F460");
        this.put("MONTE CERIGNONE","F467");
        this.put("MONTE COLOMBO","F476");
        this.put("MONTE COMPATRI","F477");
        this.put("MONTE CREMASCO","F434");
        this.put("MONTE DI MALO","F486");
        this.put("MONTE DI PROCIDA","F488");
        this.put("MONTE GIBERTO","F517");
        this.put("MONTE GRIMANO TERME","F524");
        this.put("MONTE ISOLA","F532");
        this.put("MONTE MARENZO","F561");
        this.put("MONTE PORZIO","F589");
        this.put("MONTE PORZIO CATONE","F590");
        this.put("MONTE RINALDO","F599");
        this.put("MONTE ROBERTO","F600");
        this.put("MONTE ROMANO","F603");
        this.put("MONTE SAN BIAGIO","F616");
        this.put("MONTE SAN GIACOMO","F618");
        this.put("MONTE SAN GIOVANNI CAMPANO","F620");
        this.put("MONTE SAN GIOVANNI IN SABINA","F619");
        this.put("MONTE SAN GIUSTO","F621");
        this.put("MONTE SAN MARTINO","F622");
        this.put("MONTE SAN PIETRANGELI","F626");
        this.put("MONTE SAN PIETRO","F627");
        this.put("MONTE SAN SAVINO","F628");
        this.put("MONTE SAN VITO","F634");
        this.put("MONTE SANTA MARIA TIBERINA","F629");
        this.put("MONTE SANT'ANGELO","F631");
        this.put("MONTE URANO","F653");
        this.put("MONTE VIDON COMBATTE","F664");
        this.put("MONTE VIDON CORRADO","F665");
        this.put("MONTEBELLO DELLA BATTAGLIA","F440");
        this.put("MONTEBELLO DI BERTONA","F441");
        this.put("MONTEBELLO JONICO","D746");
        this.put("MONTEBELLO SUL SANGRO","B268");
        this.put("MONTEBELLO VICENTINO","F442");
        this.put("MONTEBELLUNA","F443");
        this.put("MONTEBRUNO","F445");
        this.put("MONTEBUONO","F446");
        this.put("MONTECALVO IN FOGLIA","F450");
        this.put("MONTECALVO IRPINO","F448");
        this.put("MONTECALVO VERSIGGIA","F449");
        this.put("MONTECARLO","F452");
        this.put("MONTECAROTTO","F453");
        this.put("MONTECASSIANO","F454");
        this.put("MONTECASTELLO","F455");
        this.put("MONTECASTRILLI","F457");
        this.put("MONTECATINI VAL DI CECINA","F458");
        this.put("MONTECATINI TERME","A561");
        this.put("MONTECCHIA DI CROSARA","F461");
        this.put("MONTECCHIO","F462");
        this.put("MONTECCHIO EMILIA","F463");
        this.put("MONTECCHIO MAGGIORE","F464");
        this.put("MONTECCHIO PRECALCINO","F465");
        this.put("MONTECHIARO D'ACQUI","F469");
        this.put("MONTECHIARO D'ASTI","F468");
        this.put("MONTECHIARUGOLO","F473");
        this.put("MONTECICCARDO","F474");
        this.put("MONTECILFONE","F475");
        this.put("MONTECOPIOLO","F478");
        this.put("MONTECORICE","F479");
        this.put("MONTECORVINO PUGLIANO","F480");
        this.put("MONTECORVINO ROVELLA","F481");
        this.put("MONTECOSARO","F482");
        this.put("MONTECRESTESE","F483");
        this.put("MONTECRETO","F484");
        this.put("MONTEDINOVE","F487");
        this.put("MONTEDORO","F489");
        this.put("MONTEFALCIONE","F491");
        this.put("MONTEFALCO","F492");
        this.put("MONTEFALCONE APPENNINO","F493");
        this.put("MONTEFALCONE DI VAL FORTORE","F494");
        this.put("MONTEFALCONE NEL SANNIO","F495");
        this.put("MONTEFANO","F496");
        this.put("MONTEFELCINO","F497");
        this.put("MONTEFERRANTE","F498");
        this.put("MONTEFIASCONE","F499");
        this.put("MONTEFINO","F500");
        this.put("MONTEFIORE CONCA","F502");
        this.put("MONTEFIORE DELL'ASO","F501");
        this.put("MONTEFIORINO","F503");
        this.put("MONTEFLAVIO","F504");
        this.put("MONTEFORTE CILENTO","F507");
        this.put("MONTEFORTE D'ALPONE","F508");
        this.put("MONTEFORTE IRPINO","F506");
        this.put("MONTEFORTINO","F509");
        this.put("MONTEFRANCO","F510");
        this.put("MONTEFREDANE","F511");
        this.put("MONTEFUSCO","F512");
        this.put("MONTEGABBIONE","F513");
        this.put("MONTEGALDA","F514");
        this.put("MONTEGALDELLA","F515");
        this.put("MONTEGALLO","F516");
        this.put("MONTEGIOCO","F518");
        this.put("MONTEGIORDANO","F519");
        this.put("MONTEGIORGIO","F520");
        this.put("MONTEGRANARO","F522");
        this.put("MONTEGRIDOLFO","F523");
        this.put("MONTEGRINO VALTRAVAGLIA","F526");
        this.put("MONTEGROSSO D'ASTI","F527");
        this.put("MONTEGROSSO PIAN LATTE","F528");
        this.put("MONTEGROTTO TERME","F529");
        this.put("MONTEIASI","F531");
        this.put("MONTELABBATE","F533");
        this.put("MONTELANICO","F534");
        this.put("MONTELAPIANO","F535");
        this.put("MONTELEONE DI FERMO","F536");
        this.put("MONTELEONE DI PUGLIA","F538");
        this.put("MONTELEONE DI SPOLETO","F540");
        this.put("MONTELEONE D'ORVIETO","F543");
        this.put("MONTELEONE ROCCA DORIA","F542");
        this.put("MONTELEONE SABINO","F541");
        this.put("MONTELEPRE","F544");
        this.put("MONTELIBRETTI","F545");
        this.put("MONTELLA","F546");
        this.put("MONTELLO","F547");
        this.put("MONTELONGO","F548");
        this.put("MONTELPARO","F549");
        this.put("MONTELUPO ALBESE","F550");
        this.put("MONTELUPO FIORENTINO","F551");
        this.put("MONTELUPONE","F552");
        this.put("MONTEMAGGIORE AL METAURO","F555");
        this.put("MONTEMAGGIORE BELSITO","F553");
        this.put("MONTEMAGNO","F556");
        this.put("MONTEMALE DI CUNEO","F558");
        this.put("MONTEMARANO","F559");
        this.put("MONTEMARCIANO","F560");
        this.put("MONTEMARZINO","F562");
        this.put("MONTEMESOLA","F563");
        this.put("MONTEMEZZO","F564");
        this.put("MONTEMIGNAIO","F565");
        this.put("MONTEMILETTO","F566");
        this.put("MONTEMILONE","F568");
        this.put("MONTEMITRO","F569");
        this.put("MONTEMONACO","F570");
        this.put("MONTEMURLO","F572");
        this.put("MONTEMURRO","F573");
        this.put("MONTENARS","F574");
        this.put("MONTENERO DI BISACCIA","F576");
        this.put("MONTENERO SABINO","F579");
        this.put("MONTENERO VAL COCCHIARA","F580");
        this.put("MONTENERODOMO","F578");
        this.put("MONTEODORISIO","F582");
        this.put("MONTEPAONE","F586");
        this.put("MONTEPARANO","F587");
        this.put("MONTEPRANDONE","F591");
        this.put("MONTEPULCIANO","F592");
        this.put("MONTERADO","F593");
        this.put("MONTERCHI","F594");
        this.put("MONTEREALE","F595");
        this.put("MONTEREALE VALCELLINA","F596");
        this.put("MONTERENZIO","F597");
        this.put("MONTERIGGIONI","F598");
        this.put("MONTERODUNI","F601");
        this.put("MONTERONI D'ARBIA","F605");
        this.put("MONTERONI DI LECCE","F604");
        this.put("MONTEROSI","F606");
        this.put("MONTEROSSO AL MARE","F609");
        this.put("MONTEROSSO ALMO","F610");
        this.put("MONTEROSSO CALABRO","F607");
        this.put("MONTEROSSO GRANA","F608");
        this.put("MONTEROTONDO","F611");
        this.put("MONTEROTONDO MARITTIMO","F612");
        this.put("MONTERUBBIANO","F614");
        this.put("MONTESANO SALENTINO","F623");
        this.put("MONTESANO SULLA MARCELLANA","F625");
        this.put("MONTESARCHIO","F636");
        this.put("MONTESCAGLIOSO","F637");
        this.put("MONTESCANO","F638");
        this.put("MONTESCHENO","F639");
        this.put("MONTESCUDAIO","F640");
        this.put("MONTESCUDO","F641");
        this.put("MONTESCUDO MONTE COLOMBO","M368");
        this.put("MONTESE","F642");
        this.put("MONTESEGALE","F644");
        this.put("MONTESILVANO","F646");
        this.put("MONTESPERTOLI","F648");
        this.put("MONTEU DA PO","F651");
        this.put("MONTEU ROERO","F654");
        this.put("MONTEVAGO","F655");
        this.put("MONTEVARCHI","F656");
        this.put("MONTEVECCHIA","F657");
        this.put("MONTEVEGLIO","F659");
        this.put("MONTEVERDE","F660");
        this.put("MONTEVERDI MARITTIMO","F661");
        this.put("MONTEVIALE","F662");
        this.put("MONTEZEMOLO","F666");
        this.put("MONTI","F667");
        this.put("MONTIANO","F668");
        this.put("MONTICELLI BRUSATI","F672");
        this.put("MONTICELLI D'ONGINA","F671");
        this.put("MONTICELLI PAVESE","F670");
        this.put("MONTICELLO BRIANZA","F674");
        this.put("MONTICELLO CONTE OTTO","F675");
        this.put("MONTICELLO D'ALBA","F669");
        this.put("MONTICHIARI","F471");
        this.put("MONTICIANO","F676");
        this.put("MONTIERI","F677");
        this.put("MONTIGLIO MONFERRATO","M302");
        this.put("MONTIGNOSO","F679");
        this.put("MONTIRONE","F680");
        this.put("MONTJOVET","F367");
        this.put("MONTODINE","F681");
        this.put("MONTOGGIO","F682");
        this.put("MONTONE","F685");
        this.put("MONTOPOLI DI SABINA","F687");
        this.put("MONTOPOLI IN VAL D'ARNO","F686");
        this.put("MONTORFANO","F688");
        this.put("MONTORIO AL VOMANO","F690");
        this.put("MONTORIO NEI FRENTANI","F689");
        this.put("MONTORIO ROMANO","F692");
        this.put("MONTORO","M330");
        this.put("MONTORO INFERIORE","F693");
        this.put("MONTORO SUPERIORE","F694");
        this.put("MONTORSO VICENTINO","F696");
        this.put("MONTOTTONE","F697");
        this.put("MONTRESTA","F698");
        this.put("MONTU' BECCARIA","F701");
        this.put("MONVALLE","F703");
        this.put("MONZA","F704");
        this.put("MONZAMBANO","F705");
        this.put("MONZUNO","F706");
        this.put("MORANO CALABRO","F708");
        this.put("MORANO SUL PO","F707");
        this.put("MORANSENGO","F709");
        this.put("MORANSENGO TONENGO","M434");
        this.put("MORARO","F710");
        this.put("MORAZZONE","F711");
        this.put("MORBEGNO","F712");
        this.put("MORBELLO","F713");
        this.put("MORCIANO DI LEUCA","F716");
        this.put("MORCIANO DI ROMAGNA","F715");
        this.put("MORCONE","F717");
        this.put("MORDANO","F718");
        this.put("MORENGO","F720");
        this.put("MORES","F721");
        this.put("MORESCO","F722");
        this.put("MORETTA","F723");
        this.put("MORFASSO","F724");
        this.put("MORGANO","F725");
        this.put("MORGEX","F726");
        this.put("MORGONGIORI","F727");
        this.put("MORI","F728");
        this.put("MORIAGO DELLA BATTAGLIA","F729");
        this.put("MORICONE","F730");
        this.put("MORIGERATI","F731");
        this.put("MORIMONDO","D033");
        this.put("MORINO","F732");
        this.put("MORIONDO TORINESE","F733");
        this.put("MORLUPO","F734");
        this.put("MORMANNO","F735");
        this.put("MORNAGO","F736");
        this.put("MORNESE","F737");
        this.put("MORNICO AL SERIO","F738");
        this.put("MORNICO LOSANA","F739");
        this.put("MOROLO","F740");
        this.put("MOROZZO","F743");
        this.put("MORRA DE SANCTIS","F744");
        this.put("MORRO D'ALBA","F745");
        this.put("MORRO D'ORO","F747");
        this.put("MORRO REATINO","F746");
        this.put("MORRONE DEL SANNIO","F748");
        this.put("MORROVALLE","F749");
        this.put("MORSANO AL TAGLIAMENTO","F750");
        this.put("MORSASCO","F751");
        this.put("MORTARA","F754");
        this.put("MORTEGLIANO","F756");
        this.put("MORTERONE","F758");
        this.put("MORUZZO","F760");
        this.put("MOSCAZZANO","F761");
        this.put("MOSCHIANO","F762");
        this.put("MOSCIANO SANT'ANGELO","F764");
        this.put("MOSCUFO","F765");
        this.put("MOSO IN PASSIRIA .MOOS IN PASSEIER.","F766");
        this.put("MOSSA","F767");
        this.put("MOSSANO","F768");
        this.put("MOSSO","M304");
        this.put("MOTTA BALUFFI","F771");
        this.put("MOTTA CAMASTRA","F772");
        this.put("MOTTA D'AFFERMO","F773");
        this.put("MOTTA DE' CONTI","F774");
        this.put("MOTTA DI LIVENZA","F770");
        this.put("MOTTA MONTECORVINO","F777");
        this.put("MOTTA SAN GIOVANNI","F779");
        this.put("MOTTA SANTA LUCIA","F780");
        this.put("MOTTA SANT'ANASTASIA","F781");
        this.put("MOTTA VISCONTI","F783");
        this.put("MOTTAFOLLONE","F775");
        this.put("MOTTALCIATA","F776");
        this.put("MOTTEGGIANA","B012");
        this.put("MOTTOLA","F784");
        this.put("MOZZAGROGNA","F785");
        this.put("MOZZANICA","F786");
        this.put("MOZZATE","F788");
        this.put("MOZZECANE","F789");
        this.put("MOZZO","F791");
        this.put("MUCCIA","F793");
        this.put("MUGGIA","F795");
        this.put("MUGGIO'","F797");
        this.put("MUGNANO DEL CARDINALE","F798");
        this.put("MUGNANO DI NAPOLI","F799");
        this.put("MULAZZANO","F801");
        this.put("MULAZZO","F802");
        this.put("MURA","F806");
        this.put("MURAVERA","F808");
        this.put("MURAZZANO","F809");
        this.put("MURELLO","F811");
        this.put("MURIALDO","F813");
        this.put("MURISENGO","F814");
        this.put("MURLO","F815");
        this.put("MURO LECCESE","F816");
        this.put("MURO LUCANO","F817");
        this.put("MUROS","F818");
        this.put("MUSCOLINE","F820");
        this.put("MUSEI","F822");
        this.put("MUSILE DI PIAVE","F826");
        this.put("MUSSO","F828");
        this.put("MUSSOLENTE","F829");
        this.put("MUSSOMELI","F830");
        this.put("MUZZANA DEL TURGNANO","F832");
        this.put("MUZZANO","F833");
        this.put("NAGO TORBOLE","F835");
        this.put("NALLES .NALS.","F836");
        this.put("NANNO","F837");
        this.put("NANTO","F838");
        this.put("NAPOLI","F839");
        this.put("NARBOLIA","F840");
        this.put("NARCAO","F841");
        this.put("NARDO'","F842");
        this.put("NARDODIPACE","F843");
        this.put("NARNI","F844");
        this.put("NARO","F845");
        this.put("NARZOLE","F846");
        this.put("NASINO","F847");
        this.put("NASO","F848");
        this.put("NATURNO .NATURNS.","F849");
        this.put("NAVE","F851");
        this.put("NAVE SAN ROCCO","F853");
        this.put("NAVELLI","F852");
        this.put("NAZ SCIAVES NATZ SCHABS.","F856");
        this.put("NAZZANO","F857");
        this.put("NE","F858");
        this.put("NEBBIUNO","F859");
        this.put("NEGRAR DI VALPOLICELLA","F861");
        this.put("NEIRONE","F862");
        this.put("NEIVE","F863");
        this.put("NEMBRO","F864");
        this.put("NEMI","F865");
        this.put("NEMOLI","F866");
        this.put("NEONELI","F867");
        this.put("NEPI","F868");
        this.put("NERETO","F870");
        this.put("NEROLA","F871");
        this.put("NERVESA DELLA BATTAGLIA","F872");
        this.put("NERVIANO","F874");
        this.put("NESPOLO","F876");
        this.put("NESSO","F877");
        this.put("NETRO","F878");
        this.put("NETTUNO","F880");
        this.put("NEVIANO","F881");
        this.put("NEVIANO DEGLI ARDUINI","F882");
        this.put("NEVIGLIE","F883");
        this.put("NIARDO","F884");
        this.put("NIBBIANO","F885");
        this.put("NIBBIOLA","F886");
        this.put("NIBIONNO","F887");
        this.put("NICHELINO","F889");
        this.put("NICOLOSI","F890");
        this.put("NICORVO","F891");
        this.put("NICOSIA","F892");
        this.put("NICOTERA","F893");
        this.put("NIELLA BELBO","F894");
        this.put("NIELLA TANARO","F895");
        this.put("NIMIS","F898");
        this.put("NISCEMI","F899");
        this.put("NISSORIA","F900");
        this.put("NIZZA DI SICILIA","F901");
        this.put("NIZZA MONFERRATO","F902");
        this.put("NOALE","F904");
        this.put("NOASCA","F906");
        this.put("NOCARA","F907");
        this.put("NOCCIANO","F908");
        this.put("NOCERA INFERIORE","F912");
        this.put("NOCERA SUPERIORE","F913");
        this.put("NOCERA TERINESE","F910");
        this.put("NOCERA UMBRA","F911");
        this.put("NOCETO","F914");
        this.put("NOCI","F915");
        this.put("NOCIGLIA","F916");
        this.put("NOEPOLI","F917");
        this.put("NOGARA","F918");
        this.put("NOGAREDO","F920");
        this.put("NOGAROLE ROCCA","F921");
        this.put("NOGAROLE VICENTINO","F922");
        this.put("NOICATTARO","F923");
        this.put("NOLA","F924");
        this.put("NOLE","F925");
        this.put("NOLI","F926");
        this.put("NOMAGLIO","F927");
        this.put("NOMI","F929");
        this.put("NONANTOLA","F930");
        this.put("NONE","F931");
        this.put("NONIO","F932");
        this.put("NORAGUGUME","F933");
        this.put("NORBELLO","F934");
        this.put("NORCIA","F935");
        this.put("NORMA","F937");
        this.put("NOSATE","F939");
        this.put("NOTARESCO","F942");
        this.put("NOTO","F943");
        this.put("NOVA LEVANTE .WELSCHNOFEN.","F949");
        this.put("NOVA MILANESE","F944");
        this.put("NOVA PONENTE .DEUTSCHNOFEN.","F950");
        this.put("NOVA SIRI","A942");
        this.put("NOVAFELTRIA","F137");
        this.put("NOVALEDO","F947");
        this.put("NOVALESA","F948");
        this.put("NOVARA","F952");
        this.put("NOVARA DI SICILIA","F951");
        this.put("NOVATE MEZZOLA","F956");
        this.put("NOVATE MILANESE","F955");
        this.put("NOVE","F957");
        this.put("NOVEDRATE","F958");
        this.put("NOVELLA","M430");
        this.put("NOVELLARA","F960");
        this.put("NOVELLO","F961");
        this.put("NOVENTA DI PIAVE","F963");
        this.put("NOVENTA PADOVANA","F962");
        this.put("NOVENTA VICENTINA","F964");
        this.put("NOVI DI MODENA","F966");
        this.put("NOVI LIGURE","F965");
        this.put("NOVI VELIA","F967");
        this.put("NOVIGLIO","F968");
        this.put("NOVOLI","F970");
        this.put("NUCETTO","F972");
        this.put("NUGHEDU SAN NICOLO'","F975");
        this.put("NUGHEDU SANTA VITTORIA","F974");
        this.put("NULE","F976");
        this.put("NULVI","F977");
        this.put("NUMANA","F978");
        this.put("NUORO","F979");
        this.put("NURACHI","F980");
        this.put("NURAGUS","F981");
        this.put("NURALLAO","F982");
        this.put("NURAMINIS","F983");
        this.put("NURECI","F985");
        this.put("NURRI","F986");
        this.put("NUS","F987");
        this.put("NUSCO","F988");
        this.put("NUVOLENTO","F989");
        this.put("NUVOLERA","F990");
        this.put("NUXIS","F991");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
