package libreria_sibilia.codicefiscale.document ;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_UVZ extends HashMap<String, String> {

    public CitiesCodes_UVZ(){
        this.put("UBIALE CLANEZZO","C789");
        this.put("UBOLDO","L480");
        this.put("UCRIA","L482");
        this.put("UDINE","L483");
        this.put("UGENTO","L484");
        this.put("UGGIANO LA CHIESA","L485");
        this.put("UGGIATE TREVANO","L487");
        this.put("ULA' TIRSO","L488");
        this.put("ULASSAI","L489");
        this.put("ULTIMO .ULTEN.","L490");
        this.put("UMBERTIDE","D786");
        this.put("UMBRIATICO","L492");
        this.put("URAGO D'OGLIO","L494");
        this.put("URAS","L496");
        this.put("URBANA","L497");
        this.put("URBANIA","L498");
        this.put("URBE","L499");
        this.put("URBINO","L500");
        this.put("URBISAGLIA","L501");
        this.put("URGNANO","L502");
        this.put("URI","L503");
        this.put("URURI","L505");
        this.put("URZULEI","L506");
        this.put("USCIO","L507");
        this.put("USELLUS","L508");
        this.put("USINI","L509");
        this.put("USMATE VELATE","L511");
        this.put("USSANA","L512");
        this.put("USSARAMANNA","L513");
        this.put("USSASSAI","L514");
        this.put("USSEAUX","L515");
        this.put("USSEGLIO","L516");
        this.put("USSITA","L517");
        this.put("USTICA","L519");
        this.put("UTA","L521");
        this.put("UZZANO","L522");
        this.put("VACCARIZZO ALBANESE","L524");
        this.put("VACONE","L525");
        this.put("VACRI","L526");
        this.put("VADENA .PFATTEN.","L527");
        this.put("VADO LIGURE","L528");
        this.put("VAGLI SOTTO","L533");
        this.put("VAGLIA","L529");
        this.put("VAGLIO BASILICATA","L532");
        this.put("VAGLIO SERRA","L531");
        this.put("VAIANO","L537");
        this.put("VAIANO CREMASCO","L535");
        this.put("VAIE","L538");
        this.put("VAILATE","L539");
        this.put("VAIRANO PATENORA","L540");
        this.put("VAJONT","M265");
        this.put("VAL BREMBILLA","M334");
        this.put("VAL DELLA TORRE","L555");
        this.put("VAL DI CHY","M405");
        this.put("VAL DI NIZZA","L562");
        this.put("VAL DI VIZZE .PFITSCH.","L564");
        this.put("VAL DI ZOLDO","M374");
        this.put("VAL LIONA","M384");
        this.put("VAL MASINO","L638");
        this.put("VAL REZZO","H259");
        this.put("VALBONDIONE","L544");
        this.put("VALBREMBO","L545");
        this.put("VALBRENTA","M423");
        this.put("VALBREVENNA","L546");
        this.put("VALBRONA","L547");
        this.put("VALCHIUSA","M415");
        this.put("VALDA","L550");
        this.put("VALDAGNO","L551");
        this.put("VALDAONE","M343");
        this.put("VALDAORA .OLANG.","L552");
        this.put("VALDASTICO","L554");
        this.put("VALDENGO","L556");
        this.put("VALDERICE","G319");
        this.put("VALDIDENTRO","L557");
        this.put("VALDIERI","L558");
        this.put("VALDILANA","M417");
        this.put("VALDINA","L561");
        this.put("VALDISOTTO","L563");
        this.put("VALDOBBIADENE","L565");
        this.put("VALDUGGIA","L566");
        this.put("VALEGGIO","L568");
        this.put("VALEGGIO SUL MINCIO","L567");
        this.put("VALENTANO","L569");
        this.put("VALENZA","L570");
        this.put("VALENZANO","L571");
        this.put("VALERA FRATTA","L572");
        this.put("VALFABBRICA","L573");
        this.put("VALFENERA","L574");
        this.put("VALFLORIANA","L575");
        this.put("VALFORNACE","M382");
        this.put("VALFURVA","L576");
        this.put("VALGANNA","L577");
        this.put("VALGIOIE","L578");
        this.put("VALGOGLIO","L579");
        this.put("VALGRANA","L580");
        this.put("VALGREGHENTINO","L581");
        this.put("VALGRISENCHE","L582");
        this.put("VALGUARNERA CAROPEPE","L583");
        this.put("VALLADA AGORDINA","L584");
        this.put("VALLANZENGO","L586");
        this.put("VALLARSA","L588");
        this.put("VALLATA","L589");
        this.put("VALLE AGRICOLA","L594");
        this.put("VALLE AURINA .AHRNTAL.","L595");
        this.put("VALLE CANNOBINA","M404");
        this.put("VALLE CASTELLANA","L597");
        this.put("VALLE DELL'ANGELO","G540");
        this.put("VALLE DI CADORE","L590");
        this.put("VALLE DI CASIES .GSIES.","L601");
        this.put("VALLE DI MADDALONI","L591");
        this.put("VALLE LOMELLINA","L593");
        this.put("VALLE MOSSO","L606");
        this.put("VALLE SALIMBENE","L617");
        this.put("VALLE SAN NICOLAO","L620");
        this.put("VALLEBONA","L596");
        this.put("VALLECORSA","L598");
        this.put("VALLECROSIA","L599");
        this.put("VALLEDOLMO","L603");
        this.put("VALLEDORIA","L604");
        this.put("VALLEFIORITA","I322");
        this.put("VALLEFOGLIA","M331");
        this.put("VALLELAGHI","M362");
        this.put("VALLELONGA","L607");
        this.put("VALLELUNGA PRATAMENO","L609");
        this.put("VALLEMAIO","L605");
        this.put("VALLEPIETRA","L611");
        this.put("VALLERANO","L612");
        this.put("VALLERMOSA","L613");
        this.put("VALLEROTONDA","L614");
        this.put("VALLESACCARDA","L616");
        this.put("VALLEVE","L623");
        this.put("VALLI DEL PASUBIO","L624");
        this.put("VALLINFREDA","L625");
        this.put("VALLIO TERME","L626");
        this.put("VALLO DELLA LUCANIA","L628");
        this.put("VALLO DI NERA","L627");
        this.put("VALLO TORINESE","L629");
        this.put("VALLORIATE","L631");
        this.put("VALMACCA","L633");
        this.put("VALMADRERA","L634");
        this.put("VALMALA","L636");
        this.put("VALMONTONE","L639");
        this.put("VALMOREA","L640");
        this.put("VALMOZZOLA","L641");
        this.put("VALNEGRA","L642");
        this.put("VALPELLINE","L643");
        this.put("VALPERGA","L644");
        this.put("VALPRATO SOANA","B510");
        this.put("VALSAMOGGIA","M320");
        this.put("VALSAVARENCHE","L647");
        this.put("VALSECCA","L649");
        this.put("VALSINNI","D513");
        this.put("VALSOLDA","C936");
        this.put("VALSTAGNA","L650");
        this.put("VALSTRONA","L651");
        this.put("VALTOPINA","L653");
        this.put("VALTORTA","L655");
        this.put("VALTOURNENCHE","L654");
        this.put("VALVA","L656");
        this.put("VALVARRONE","M395");
        this.put("VALVASONE","L657");
        this.put("VALVASONE ARZENE","M346");
        this.put("VALVERDE","L658");
        this.put("VALVERDE","L659");
        this.put("VALVESTINO","L468");
        this.put("VANDOIES .VINTL.","L660");
        this.put("VANZAGHELLO","L664");
        this.put("VANZAGO","L665");
        this.put("VANZONE CON SAN CARLO","L666");
        this.put("VAPRIO D'ADDA","L667");
        this.put("VAPRIO D'AGOGNA","L668");
        this.put("VARALLO","L669");
        this.put("VARALLO POMBIA","L670");
        this.put("VARANO BORGHI","L671");
        this.put("VARANO DE' MELEGARI","L672");
        this.put("VARAPODIO","L673");
        this.put("VARAZZE","L675");
        this.put("VARCO SABINO","L676");
        this.put("VAREDO","L677");
        this.put("VARENA","L678");
        this.put("VARENNA","L680");
        this.put("VARESE","L682");
        this.put("VARESE LIGURE","L681");
        this.put("VARISELLA","L685");
        this.put("VARMO","L686");
        this.put("VARNA .VAHRN.","L687");
        this.put("VARSI","L689");
        this.put("VARZI","L690");
        this.put("VARZO","L691");
        this.put("VAS","L692");
        this.put("VASANELLO","A701");
        this.put("VASIA","L693");
        this.put("VASTO","E372");
        this.put("VASTOGIRARDI","L696");
        this.put("VATTARO","L697");
        this.put("VAUDA CANAVESE","L698");
        this.put("VAZZANO","L699");
        this.put("VAZZOLA","L700");
        this.put("VECCHIANO","L702");
        this.put("VEDANO AL LAMBRO","L704");
        this.put("VEDANO OLONA","L703");
        this.put("VEDDASCA","L705");
        this.put("VEDELAGO","L706");
        this.put("VEDESETA","L707");
        this.put("VEDUGGIO CON COLZANO","L709");
        this.put("VEGGIANO","L710");
        this.put("VEGLIE","L711");
        this.put("VEGLIO","L712");
        this.put("VEJANO","L713");
        this.put("VELESO","L715");
        this.put("VELEZZO LOMELLINA","L716");
        this.put("VELLETRI","L719");
        this.put("VELLEZZO BELLINI","L720");
        this.put("VELO D'ASTICO","L723");
        this.put("VELO VERONESE","L722");
        this.put("VELTURNO .FELDTHURNS.","L724");
        this.put("VENAFRO","L725");
        this.put("VENARIA REALE","L727");
        this.put("VENAROTTA","L728");
        this.put("VENASCA","L729");
        this.put("VENAUS","L726");
        this.put("VENDONE","L730");
        this.put("VENDROGNO","L731");
        this.put("VENEGONO INFERIORE","L733");
        this.put("VENEGONO SUPERIORE","L734");
        this.put("VENETICO","L735");
        this.put("VENEZIA","L736");
        this.put("VENIANO","L737");
        this.put("VENOSA","L738");
        this.put("VENTASSO","M364");
        this.put("VENTICANO","L739");
        this.put("VENTIMIGLIA","L741");
        this.put("VENTIMIGLIA DI SICILIA","L740");
        this.put("VENTOTENE","L742");
        this.put("VENZONE","L743");
        this.put("VERANO BRIANZA","L744");
        this.put("VERANO .VOERAN.","L745");
        this.put("VERBANIA","L746");
        this.put("VERBICARO","L747");
        this.put("VERCANA","L748");
        this.put("VERCEIA","L749");
        this.put("VERCELLI","L750");
        this.put("VERCURAGO","L751");
        this.put("VERDELLINO","L752");
        this.put("VERDELLO","L753");
        this.put("VERDERIO","M337");
        this.put("VERDERIO INFERIORE","L755");
        this.put("VERDERIO SUPERIORE","L756");
        this.put("VERDUNO","L758");
        this.put("VERGATO","L762");
        this.put("VERGEMOLI","L763");
        this.put("VERGHERETO","L764");
        this.put("VERGIATE","L765");
        this.put("VERMEZZO","L768");
        this.put("VERMEZZO CON ZELO","M424");
        this.put("VERMIGLIO","L769");
        this.put("VERNANTE","L771");
        this.put("VERNASCA","L772");
        this.put("VERNATE","L773");
        this.put("VERNAZZA","L774");
        this.put("VERNIO","L775");
        this.put("VERNOLE","L776");
        this.put("VEROLANUOVA","L777");
        this.put("VEROLAVECCHIA","L778");
        this.put("VEROLENGO","L779");
        this.put("VEROLI","L780");
        this.put("VERONA","L781");
        this.put("VERONELLA","D193");
        this.put("VERRAYES","L783");
        this.put("VERRES","C282");
        this.put("VERRETTO","L784");
        this.put("VERRONE","L785");
        this.put("VERRUA PO","L788");
        this.put("VERRUA SAVOIA","L787");
        this.put("VERTEMATE CON MINOPRIO","L792");
        this.put("VERTOVA","L795");
        this.put("VERUCCHIO","L797");
        this.put("VERUNO","L798");
        this.put("VERVIO","L799");
        this.put("VERVO'","L800");
        this.put("VERZEGNIS","L801");
        this.put("VERZINO","L802");
        this.put("VERZUOLO","L804");
        this.put("VESCOVANA","L805");
        this.put("VESCOVATO","L806");
        this.put("VESIME","L807");
        this.put("VESPOLATE","L808");
        this.put("VESSALICO","L809");
        this.put("VESTENANOVA","L810");
        this.put("VESTIGNE'","L811");
        this.put("VESTONE","L812");
        this.put("VESTRENO","L813");
        this.put("VETRALLA","L814");
        this.put("VETTO","L815");
        this.put("VEZZA D'ALBA","L817");
        this.put("VEZZA D'OGLIO","L816");
        this.put("VEZZANO","L821");
        this.put("VEZZANO LIGURE","L819");
        this.put("VEZZANO SUL CROSTOLO","L820");
        this.put("VEZZI PORTIO","L823");
        this.put("VIADANA","L826");
        this.put("VIADANICA","L827");
        this.put("VIAGRANDE","L828");
        this.put("VIALE","L829");
        this.put("VIALFRE'","L830");
        this.put("VIANO","L831");
        this.put("VIAREGGIO","L833");
        this.put("VIARIGI","L834");
        this.put("VIBO VALENTIA","F537");
        this.put("VIBONATI","L835");
        this.put("VICALVI","L836");
        this.put("VICARI","L837");
        this.put("VICCHIO","L838");
        this.put("VICENZA","L840");
        this.put("VICO CANAVESE","L548");
        this.put("VICO DEL GARGANO","L842");
        this.put("VICO EQUENSE","L845");
        this.put("VICO NEL LAZIO","L843");
        this.put("VICOFORTE","L841");
        this.put("VICOLI","L846");
        this.put("VICOLUNGO","L847");
        this.put("VICOPISANO","L850");
        this.put("VICOVARO","L851");
        this.put("VIDDALBA","M259");
        this.put("VIDIGULFO","L854");
        this.put("VIDOR","L856");
        this.put("VIDRACCO","L857");
        this.put("VIESTE","L858");
        this.put("VIETRI DI POTENZA","L859");
        this.put("VIETRI SUL MARE","L860");
        this.put("VIGANELLA","L864");
        this.put("VIGANO'","L866");
        this.put("VIGANO SAN MARTINO","L865");
        this.put("VIGARANO MAINARDA","L868");
        this.put("VIGASIO","L869");
        this.put("VIGEVANO","L872");
        this.put("VIGGIANELLO","L873");
        this.put("VIGGIANO","L874");
        this.put("VIGGIU'","L876");
        this.put("VIGHIZZOLO D'ESTE","L878");
        this.put("VIGLIANO BIELLESE","L880");
        this.put("VIGLIANO D'ASTI","L879");
        this.put("VIGNALE MONFERRATO","L881");
        this.put("VIGNANELLO","L882");
        this.put("VIGNATE","L883");
        this.put("VIGNOLA","L885");
        this.put("VIGNOLA FALESINA","L886");
        this.put("VIGNOLE BORBERA","L887");
        this.put("VIGNOLO","L888");
        this.put("VIGNONE","L889");
        this.put("VIGO DI CADORE","L890");
        this.put("VIGO DI FASSA","L893");
        this.put("VIGO RENDENA","L903");
        this.put("VIGODARZERE","L892");
        this.put("VIGOLO","L894");
        this.put("VIGOLO VATTARO","L896");
        this.put("VIGOLZONE","L897");
        this.put("VIGONE","L898");
        this.put("VIGONOVO","L899");
        this.put("VIGONZA","L900");
        this.put("VIGUZZOLO","L904");
        this.put("VILLA AGNEDO","L910");
        this.put("VILLA BARTOLOMEA","L912");
        this.put("VILLA BASILICA","L913");
        this.put("VILLA BISCOSSI","L917");
        this.put("VILLA CARCINA","L919");
        this.put("VILLA CASTELLI","L920");
        this.put("VILLA CELIERA","L922");
        this.put("VILLA COLLEMANDINA","L926");
        this.put("VILLA CORTESE","L928");
        this.put("VILLA D'ADDA","L929");
        this.put("VILLA D'ALME'","A215");
        this.put("VILLA DEL BOSCO","L933");
        this.put("VILLA DEL CONTE","L934");
        this.put("VILLA DI BRIANO","D801");
        this.put("VILLA DI CHIAVENNA","L907");
        this.put("VILLA DI SERIO","L936");
        this.put("VILLA DI TIRANO","L908");
        this.put("VILLA D'OGNA","L938");
        this.put("VILLA ESTENSE","L937");
        this.put("VILLA FARALDI","L943");
        this.put("VILLA GUARDIA","L956");
        this.put("VILLA LAGARINA","L957");
        this.put("VILLA LATINA","A081");
        this.put("VILLA LITERNO","L844");
        this.put("VILLA MINOZZO","L969");
        this.put("VILLA POMA","F804");
        this.put("VILLA RENDENA","M006");
        this.put("VILLA SAN GIOVANNI","M018");
        this.put("VILLA SAN GIOVANNI IN TUSCIA","H913");
        this.put("VILLA SAN PIETRO","I118");
        this.put("VILLA SAN SECONDO","M019");
        this.put("VILLA SANTA LUCIA","L905");
        this.put("VILLA SANTA LUCIA DEGLI ABRUZZI","M021");
        this.put("VILLA SANTA MARIA","M022");
        this.put("VILLA SANT'ANGELO","M023");
        this.put("VILLA SANT'ANTONIO","I298");
        this.put("VILLA SANTINA","L909");
        this.put("VILLA SANTO STEFANO","I364");
        this.put("VILLA VERDE","A609");
        this.put("VILLA VICENTINA","M034");
        this.put("VILLABASSA .NIEDERDORF.","L915");
        this.put("VILLABATE","L916");
        this.put("VILLACHIARA","L923");
        this.put("VILLACIDRO","L924");
        this.put("VILLADEATI","L931");
        this.put("VILLADOSE","L939");
        this.put("VILLADOSSOLA","L906");
        this.put("VILLAFALLETTO","L942");
        this.put("VILLAFRANCA D'ASTI","L945");
        this.put("VILLAFRANCA DI VERONA","L949");
        this.put("VILLAFRANCA IN LUNIGIANA","L946");
        this.put("VILLAFRANCA PADOVANA","L947");
        this.put("VILLAFRANCA PIEMONTE","L948");
        this.put("VILLAFRANCA SICULA","L944");
        this.put("VILLAFRANCA TIRRENA","L950");
        this.put("VILLAFRATI","L951");
        this.put("VILLAGA","L952");
        this.put("VILLAGRANDE STRISAILI","L953");
        this.put("VILLALAGO","L958");
        this.put("VILLALBA","L959");
        this.put("VILLALFONSINA","L961");
        this.put("VILLALVERNIA","L963");
        this.put("VILLAMAGNA","L964");
        this.put("VILLAMAINA","L965");
        this.put("VILLAMAR","L966");
        this.put("VILLAMARZANA","L967");
        this.put("VILLAMASSARGIA","L968");
        this.put("VILLAMIROGLIO","L970");
        this.put("VILLANDRO .VILLANDERS.","L971");
        this.put("VILLANOVA BIELLESE","L978");
        this.put("VILLANOVA CANAVESE","L982");
        this.put("VILLANOVA D'ALBENGA","L975");
        this.put("VILLANOVA D'ARDENGHI","L983");
        this.put("VILLANOVA D'ASTI","L984");
        this.put("VILLANOVA DEL BATTISTA","L973");
        this.put("VILLANOVA DEL GHEBBO","L985");
        this.put("VILLANOVA DEL SILLARO","L977");
        this.put("VILLANOVA DI CAMPOSAMPIERO","L979");
        this.put("VILLANOVA MARCHESANA","L988");
        this.put("VILLANOVA MONDOVI'","L974");
        this.put("VILLANOVA MONFERRATO","L972");
        this.put("VILLANOVA MONTELEONE","L989");
        this.put("VILLANOVA SOLARO","L990");
        this.put("VILLANOVA SULL'ARDA","L980");
        this.put("VILLANOVA TRUSCHEDU","L991");
        this.put("VILLANOVA TULO","L992");
        this.put("VILLANOVAFORRU","L986");
        this.put("VILLANOVAFRANCA","L987");
        this.put("VILLANTERIO","L994");
        this.put("VILLANUOVA SUL CLISI","L995");
        this.put("VILLAPERUCCIO","M278");
        this.put("VILLAPIANA","B903");
        this.put("VILLAPUTZU","L998");
        this.put("VILLAR DORA","L999");
        this.put("VILLAR FOCCHIARDO","M007");
        this.put("VILLAR PELLICE","M013");
        this.put("VILLAR PEROSA","M014");
        this.put("VILLAR SAN COSTANZO","M015");
        this.put("VILLARBASSE","M002");
        this.put("VILLARBOIT","M003");
        this.put("VILLAREGGIA","M004");
        this.put("VILLARICCA","G309");
        this.put("VILLAROMAGNANO","M009");
        this.put("VILLAROSA","M011");
        this.put("VILLASALTO","M016");
        this.put("VILLASANTA","M017");
        this.put("VILLASIMIUS","B738");
        this.put("VILLASOR","M025");
        this.put("VILLASPECIOSA","M026");
        this.put("VILLASTELLONE","M027");
        this.put("VILLATA","M028");
        this.put("VILLAURBANA","M030");
        this.put("VILLAVALLELONGA","M031");
        this.put("VILLAVERLA","M032");
        this.put("VILLE D'ANAUNIA","M363");
        this.put("VILLE DI FIEMME","M431");
        this.put("VILLENEUVE","L981");
        this.put("VILLESSE","M043");
        this.put("VILLETTA BARREA","M041");
        this.put("VILLETTE","M042");
        this.put("VILLIMPENTA","M044");
        this.put("VILLONGO","M045");
        this.put("VILLORBA","M048");
        this.put("VILMINORE DI SCALVE","M050");
        this.put("VIMERCATE","M052");
        this.put("VIMODRONE","M053");
        this.put("VINADIO","M055");
        this.put("VINCHIATURO","M057");
        this.put("VINCHIO","M058");
        this.put("VINCI","M059");
        this.put("VINOVO","M060");
        this.put("VINZAGLIO","M062");
        this.put("VIOLA","M063");
        this.put("VIONE","M065");
        this.put("VIPITENO .STERZING.","M067");
        this.put("VIRGILIO","H123");
        this.put("VIRLE PIEMONTE","M069");
        this.put("VISANO","M070");
        this.put("VISCHE","M071");
        this.put("VISCIANO","M072");
        this.put("VISCO","M073");
        this.put("VISONE","M077");
        this.put("VISSO","M078");
        this.put("VISTARINO","M079");
        this.put("VISTRORIO","M080");
        this.put("VITA","M081");
        this.put("VITERBO","M082");
        this.put("VITICUSO","M083");
        this.put("VITO D'ASIO","M085");
        this.put("VITORCHIANO","M086");
        this.put("VITTORIA","M088");
        this.put("VITTORIO VENETO","M089");
        this.put("VITTORITO","M090");
        this.put("VITTUONE","M091");
        this.put("VITULANO","M093");
        this.put("VITULAZIO","M092");
        this.put("VIU'","M094");
        this.put("VIVARO","M096");
        this.put("VIVARO ROMANO","M095");
        this.put("VIVERONE","M098");
        this.put("VIZZINI","M100");
        this.put("VIZZOLA TICINO","M101");
        this.put("VIZZOLO PREDABISSI","M102");
        this.put("VO'","M103");
        this.put("VOBARNO","M104");
        this.put("VOBBIA","M105");
        this.put("VOCCA","M106");
        this.put("VODO CADORE","M108");
        this.put("VOGHERA","M109");
        this.put("VOGHIERA","M110");
        this.put("VOGOGNA","M111");
        this.put("VOLANO","M113");
        this.put("VOLLA","M115");
        this.put("VOLONGO","M116");
        this.put("VOLPAGO DEL MONTELLO","M118");
        this.put("VOLPARA","M119");
        this.put("VOLPEDO","M120");
        this.put("VOLPEGLINO","M121");
        this.put("VOLPIANO","M122");
        this.put("VOLTA MANTOVANA","M125");
        this.put("VOLTAGGIO","M123");
        this.put("VOLTAGO AGORDINO","M124");
        this.put("VOLTERRA","M126");
        this.put("VOLTIDO","M127");
        this.put("VOLTURARA APPULA","M131");
        this.put("VOLTURARA IRPINA","M130");
        this.put("VOLTURINO","M132");
        this.put("VOLVERA","M133");
        this.put("VOTTIGNASCO","M136");
        this.put("ZACCANOPOLI","M138");
        this.put("ZAFFERANA ETNEA","M139");
        this.put("ZAGARISE","M140");
        this.put("ZAGAROLO","M141");
        this.put("ZAMBANA","M142");
        this.put("ZAMBRONE","M143");
        this.put("ZANDOBBIO","M144");
        this.put("ZANE'","M145");
        this.put("ZANICA","M147");
        this.put("ZAPPONETA","M267");
        this.put("ZAVATTARELLO","M150");
        this.put("ZECCONE","M152");
        this.put("ZEDDIANI","M153");
        this.put("ZELBIO","M156");
        this.put("ZELO BUON PERSICO","M158");
        this.put("ZELO SURRIGONE","M160");
        this.put("ZEME","M161");
        this.put("ZENEVREDO","M162");
        this.put("ZENSON DI PIAVE","M163");
        this.put("ZERBA","M165");
        this.put("ZERBO","M166");
        this.put("ZERBOLO'","M167");
        this.put("ZERFALIU","M168");
        this.put("ZERI","M169");
        this.put("ZERMEGHEDO","M170");
        this.put("ZERO BRANCO","M171");
        this.put("ZEVIO","M172");
        this.put("ZIANO DI FIEMME","M173");
        this.put("ZIANO PIACENTINO","L848");
        this.put("ZIBELLO","M174");
        this.put("ZIBIDO SAN GIACOMO","M176");
        this.put("ZIGNAGO","M177");
        this.put("ZIMELLA","M178");
        this.put("ZIMONE","M179");
        this.put("ZINASCO","M180");
        this.put("ZOAGLI","M182");
        this.put("ZOCCA","M183");
        this.put("ZOGNO","M184");
        this.put("ZOLA PREDOSA","M185");
        this.put("ZOLDO ALTO","I345");
        this.put("ZOLLINO","M187");
        this.put("ZONE","M188");
        this.put("ZOPPE' DI CADORE","M189");
        this.put("ZOPPOLA","M190");
        this.put("ZOVENCEDO","M194");
        this.put("ZUBIENA","M196");
        this.put("ZUCCARELLO","M197");
        this.put("ZUCLO","M198");
        this.put("ZUGLIANO","M199");
        this.put("ZUGLIO","M200");
        this.put("ZUMAGLIA","M201");
        this.put("ZUMPANO","M202");
        this.put("ZUNGOLI","M203");
        this.put("ZUNGRI","M204");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
