package libreria_sibilia.codicefiscale.document ;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_F extends HashMap<String, String> {

    public CitiesCodes_F(){
        this.put("FABBRICA CURONE","D447");
        this.put("FABBRICHE DI VALLICO","D449");
        this.put("FABBRICHE DI VERGEMOLI","M319");
        this.put("FABBRICO","D450");
        this.put("FABRIANO","D451");
        this.put("FABRICA DI ROMA","D452");
        this.put("FABRIZIA","D453");
        this.put("FABRO","D454");
        this.put("FAEDIS","D455");
        this.put("FAEDO","D457");
        this.put("FAEDO VALTELLINO","D456");
        this.put("FAENZA","D458");
        this.put("FAETO","D459");
        this.put("FAGAGNA","D461");
        this.put("FAGGETO LARIO","D462");
        this.put("FAGGIANO","D463");
        this.put("FAGNANO ALTO","D465");
        this.put("FAGNANO CASTELLO","D464");
        this.put("FAGNANO OLONA","D467");
        this.put("FAI DELLA PAGANELLA","D468");
        this.put("FAICCHIO","D469");
        this.put("FALCADE","D470");
        this.put("FALCIANO DEL MASSICO","D471");
        this.put("FALCONARA ALBANESE","D473");
        this.put("FALCONARA MARITTIMA","D472");
        this.put("FALCONE","D474");
        this.put("FALERIA","D475");
        this.put("FALERNA","D476");
        this.put("FALERONE","D477");
        this.put("FALLO","D480");
        this.put("FALMENTA","D481");
        this.put("FALOPPIO","D482");
        this.put("FALVATERRA","D483");
        this.put("FALZES .PFALZEN.","D484");
        this.put("FANANO","D486");
        this.put("FANNA","D487");
        this.put("FANO","D488");
        this.put("FANO ADRIANO","D489");
        this.put("FARA FILIORUM PETRI","D494");
        this.put("FARA GERA D'ADDA","D490");
        this.put("FARA IN SABINA","D493");
        this.put("FARA NOVARESE","D492");
        this.put("FARA OLIVANA CON SOLA","D491");
        this.put("FARA SAN MARTINO","D495");
        this.put("FARA VICENTINO","D496");
        this.put("FARDELLA","D497");
        this.put("FARIGLIANO","D499");
        this.put("FARINDOLA","D501");
        this.put("FARINI","D502");
        this.put("FARNESE","D503");
        this.put("FARRA D'ALPAGO","D506");
        this.put("FARRA DI SOLIGO","D505");
        this.put("FARRA D'ISONZO","D504");
        this.put("FASANO","D508");
        this.put("FASCIA","D509");
        this.put("FAUGLIA","D510");
        this.put("FAULE","D511");
        this.put("FAVALE DI MALVARO","D512");
        this.put("FAVARA","D514");
        this.put("FAVER","D516");
        this.put("FAVIGNANA","D518");
        this.put("FAVRIA","D520");
        this.put("FEISOGLIO","D523");
        this.put("FELETTO","D524");
        this.put("FELINO","D526");
        this.put("FELITTO","D527");
        this.put("FELIZZANO","D528");
        this.put("FELONICA","D529");
        this.put("FELTRE","D530");
        this.put("FENEGRO'","D531");
        this.put("FENESTRELLE","D532");
        this.put("FENIS","D537");
        this.put("FERENTILLO","D538");
        this.put("FERENTINO","D539");
        this.put("FERLA","D540");
        this.put("FERMIGNANO","D541");
        this.put("FERMO","D542");
        this.put("FERNO","D543");
        this.put("FEROLETO ANTICO","D544");
        this.put("FEROLETO DELLA CHIESA","D545");
        this.put("FERRANDINA","D547");
        this.put("FERRARA","D548");
        this.put("FERRARA DI MONTE BALDO","D549");
        this.put("FERRAZZANO","D550");
        this.put("FERRERA DI VARESE","D551");
        this.put("FERRERA ERBOGNONE","D552");
        this.put("FERRERE","D554");
        this.put("FERRIERE","D555");
        this.put("FERRUZZANO","D557");
        this.put("FIAMIGNANO","D560");
        this.put("FIANO","D562");
        this.put("FIANO ROMANO","D561");
        this.put("FIASTRA","D564");
        this.put("FIAVE'","D565");
        this.put("FICARAZZI","D567");
        this.put("FICAROLO","D568");
        this.put("FICARRA","D569");
        this.put("FICULLE","D570");
        this.put("FIDENZA","B034");
        this.put("FIE' ALLO SCILIAR .VOELS AM SCHLERN.","D571");
        this.put("FIERA DI PRIMIERO","D572");
        this.put("FIEROZZO","D573");
        this.put("FIESCO","D574");
        this.put("FIESOLE","D575");
        this.put("FIESSE","D576");
        this.put("FIESSO D'ARTICO","D578");
        this.put("FIESSO UMBERTIANO","D577");
        this.put("FIGINO SERENZA","D579");
        this.put("FIGLINE E INCISA VALDARNO","M321");
        this.put("FIGLINE VALDARNO","D583");
        this.put("FIGLINE VEGLIATURO","D582");
        this.put("FILACCIANO","D586");
        this.put("FILADELFIA","D587");
        this.put("FILAGO","D588");
        this.put("FILANDARI","D589");
        this.put("FILATTIERA","D590");
        this.put("FILETTINO","D591");
        this.put("FILETTO","D592");
        this.put("FILIANO","D593");
        this.put("FILIGHERA","D594");
        this.put("FILIGNANO","D595");
        this.put("FILOGASO","D596");
        this.put("FILOTTRANO","D597");
        this.put("FINALE EMILIA","D599");
        this.put("FINALE LIGURE","D600");
        this.put("FINO DEL MONTE","D604");
        this.put("FINO MORNASCO","D605");
        this.put("FIORANO AL SERIO","D606");
        this.put("FIORANO CANAVESE","D608");
        this.put("FIORANO MODENESE","D607");
        this.put("FIORDIMONTE","D609");
        this.put("FIORENZUOLA D'ARDA","D611");
        this.put("FIRENZE","D612");
        this.put("FIRENZUOLA","D613");
        this.put("FIRMO","D614");
        this.put("FISCAGLIA","M323");
        this.put("FISCIANO","D615");
        this.put("FIUGGI","A310");
        this.put("FIUMALBO","D617");
        this.put("FIUMARA","D619");
        this.put("FIUME VENETO","D621");
        this.put("FIUMEDINISI","D622");
        this.put("FIUMEFREDDO BRUZIO","D624");
        this.put("FIUMEFREDDO DI SICILIA","D623");
        this.put("FIUMICELLO","D627");
        this.put("FIUMICELLO VILLA VICENTINA","M400");
        this.put("FIUMICINO","M297");
        this.put("FIUMINATA","D628");
        this.put("FIVIZZANO","D629");
        this.put("FLAIBANO","D630");
        this.put("FLAVON","D631");
        this.put("FLERO","D634");
        this.put("FLORESTA","D635");
        this.put("FLORIDIA","D636");
        this.put("FLORINAS","D637");
        this.put("FLUMERI","D638");
        this.put("FLUMINIMAGGIORE","D639");
        this.put("FLUSSIO","D640");
        this.put("FOBELLO","D641");
        this.put("FOGGIA","D643");
        this.put("FOGLIANISE","D644");
        this.put("FOGLIANO REDIPUGLIA","D645");
        this.put("FOGLIZZO","D646");
        this.put("FOIANO DELLA CHIANA","D649");
        this.put("FOIANO DI VAL FORTORE","D650");
        this.put("FOLGARIA","D651");
        this.put("FOLIGNANO","D652");
        this.put("FOLIGNO","D653");
        this.put("FOLLINA","D654");
        this.put("FOLLO","D655");
        this.put("FOLLONICA","D656");
        this.put("FOMBIO","D660");
        this.put("FONDACHELLI FANTINA","D661");
        this.put("FONDI","D662");
        this.put("FONDO","D663");
        this.put("FONNI","D665");
        this.put("FONTAINEMORE","D666");
        this.put("FONTANA LIRI","D667");
        this.put("FONTANAFREDDA","D670");
        this.put("FONTANAROSA","D671");
        this.put("FONTANELICE","D668");
        this.put("FONTANELLA","D672");
        this.put("FONTANELLATO","D673");
        this.put("FONTANELLE","D674");
        this.put("FONTANETO D'AGOGNA","D675");
        this.put("FONTANETTO PO","D676");
        this.put("FONTANIGORDA","D677");
        this.put("FONTANILE","D678");
        this.put("FONTANIVA","D679");
        this.put("FONTE","D680");
        this.put("FONTE NUOVA","M309");
        this.put("FONTECCHIO","D681");
        this.put("FONTECHIARI","D682");
        this.put("FONTEGRECA","D683");
        this.put("FONTENO","D684");
        this.put("FONTEVIVO","D685");
        this.put("FONZASO","D686");
        this.put("FOPPOLO","D688");
        this.put("FORANO","D689");
        this.put("FORCE","D691");
        this.put("FORCHIA","D693");
        this.put("FORCOLA","D694");
        this.put("FORDONGIANUS","D695");
        this.put("FORENZA","D696");
        this.put("FORESTO SPARSO","D697");
        this.put("FORGARIA NEL FRIULI","D700");
        this.put("FORINO","D701");
        this.put("FORIO","D702");
        this.put("FORLI'","D704");
        this.put("FORLI' DEL SANNIO","D703");
        this.put("FORLIMPOPOLI","D705");
        this.put("FORMAZZA","D706");
        this.put("FORMELLO","D707");
        this.put("FORMIA","D708");
        this.put("FORMICOLA","D709");
        this.put("FORMIGARA","D710");
        this.put("FORMIGINE","D711");
        this.put("FORMIGLIANA","D712");
        this.put("FORMIGNANA","D713");
        this.put("FORNACE","D714");
        this.put("FORNELLI","D715");
        this.put("FORNI AVOLTRI","D718");
        this.put("FORNI DI SOPRA","D719");
        this.put("FORNI DI SOTTO","D720");
        this.put("FORNO CANAVESE","D725");
        this.put("FORNO DI ZOLDO","D726");
        this.put("FORNOVO DI TARO","D728");
        this.put("FORNOVO SAN GIOVANNI","D727");
        this.put("FORTE DEI MARMI","D730");
        this.put("FORTEZZA .FRANZENSFESTE.","D731");
        this.put("FORTUNAGO","D732");
        this.put("FORZA D'AGRO'","D733");
        this.put("FOSCIANDORA","D734");
        this.put("FOSDINOVO","D735");
        this.put("FOSSA","D736");
        this.put("FOSSACESIA","D738");
        this.put("FOSSALTA DI PIAVE","D740");
        this.put("FOSSALTA DI PORTOGRUARO","D741");
        this.put("FOSSALTO","D737");
        this.put("FOSSANO","D742");
        this.put("FOSSATO DI VICO","D745");
        this.put("FOSSATO SERRALTA","D744");
        this.put("FOSSO'","D748");
        this.put("FOSSOMBRONE","D749");
        this.put("FOZA","D750");
        this.put("FRABOSA SOPRANA","D751");
        this.put("FRABOSA SOTTANA","D752");
        this.put("FRACONALTO","D559");
        this.put("FRAGAGNANO","D754");
        this.put("FRAGNETO L'ABATE","D755");
        this.put("FRAGNETO MONFORTE","D756");
        this.put("FRAINE","D757");
        this.put("FRAMURA","D758");
        this.put("FRANCAVILLA AL MARE","D763");
        this.put("FRANCAVILLA ANGITOLA","D762");
        this.put("FRANCAVILLA BISIO","D759");
        this.put("FRANCAVILLA D'ETE","D760");
        this.put("FRANCAVILLA DI SICILIA","D765");
        this.put("FRANCAVILLA FONTANA","D761");
        this.put("FRANCAVILLA IN SINNI","D766");
        this.put("FRANCAVILLA MARITTIMA","D764");
        this.put("FRANCICA","D767");
        this.put("FRANCOFONTE","D768");
        this.put("FRANCOLISE","D769");
        this.put("FRASCARO","D770");
        this.put("FRASCAROLO","D771");
        this.put("FRASCATI","D773");
        this.put("FRASCINETO","D774");
        this.put("FRASSILONGO","D775");
        this.put("FRASSINELLE POLESINE","D776");
        this.put("FRASSINELLO MONFERRATO","D777");
        this.put("FRASSINETO PO","D780");
        this.put("FRASSINETTO","D781");
        this.put("FRASSINO","D782");
        this.put("FRASSINORO","D783");
        this.put("FRASSO SABINO","D785");
        this.put("FRASSO TELESINO","D784");
        this.put("FRATTA POLESINE","D788");
        this.put("FRATTA TODINA","D787");
        this.put("FRATTAMAGGIORE","D789");
        this.put("FRATTAMINORE","D790");
        this.put("FRATTE ROSA","D791");
        this.put("FRAZZANO'","D793");
        this.put("FREGONA","D794");
        this.put("FRESAGRANDINARIA","D796");
        this.put("FRESONARA","D797");
        this.put("FRIGENTO","D798");
        this.put("FRIGNANO","D799");
        this.put("FRINCO","D802");
        this.put("FRISA","D803");
        this.put("FRISANCO","D804");
        this.put("FRONT","D805");
        this.put("FRONTINO","D807");
        this.put("FRONTONE","D808");
        this.put("FROSINONE","D810");
        this.put("FROSOLONE","D811");
        this.put("FROSSASCO","D812");
        this.put("FRUGAROLO","D813");
        this.put("FUBINE MONFERRATO","D814");
        this.put("FUCECCHIO","D815");
        this.put("FUIPIANO VALLE IMAGNA","D817");
        this.put("FUMANE","D818");
        this.put("FUMONE","D819");
        this.put("FUNES .VILLNOESS.","D821");
        this.put("FURCI","D823");
        this.put("FURCI SICULO","D824");
        this.put("FURNARI","D825");
        this.put("FURORE","D826");
        this.put("FURTEI","D827");
        this.put("FUSCALDO","D828");
        this.put("FUSIGNANO","D829");
        this.put("FUSINE","D830");
        this.put("FUTANI","D832");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
