package libreria_sibilia.codicefiscale.document ;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_RST extends HashMap<String, String> {

    public CitiesCodes_RST(){
        this.put("RABBI","H146");
        this.put("RACALE","H147");
        this.put("RACALMUTO","H148");
        this.put("RACCONIGI","H150");
        this.put("RACCUJA","H151");
        this.put("RACINES .RATSCHINGS.","H152");
        this.put("RADDA IN CHIANTI","H153");
        this.put("RADDUSA","H154");
        this.put("RADICOFANI","H156");
        this.put("RADICONDOLI","H157");
        this.put("RAFFADALI","H159");
        this.put("RAGALNA","M287");
        this.put("RAGOGNA","H161");
        this.put("RAGOLI","H162");
        this.put("RAGUSA","H163");
        this.put("RAIANO","H166");
        this.put("RAMACCA","H168");
        this.put("RAMISETO","G654");
        this.put("RAMPONIO VERNA","H171");
        this.put("RANCIO VALCUVIA","H173");
        this.put("RANCO","H174");
        this.put("RANDAZZO","H175");
        this.put("RANICA","H176");
        this.put("RANZANICO","H177");
        this.put("RANZO","H180");
        this.put("RAPAGNANO","H182");
        this.put("RAPALLO","H183");
        this.put("RAPINO","H184");
        this.put("RAPOLANO TERME","H185");
        this.put("RAPOLLA","H186");
        this.put("RAPONE","H187");
        this.put("RASSA","H188");
        this.put("RASUN ANTERSELVA .RASEN ANTHOLZ.","H189");
        this.put("RASURA","H192");
        this.put("RAVANUSA","H194");
        this.put("RAVARINO","H195");
        this.put("RAVASCLETTO","H196");
        this.put("RAVELLO","H198");
        this.put("RAVENNA","H199");
        this.put("RAVEO","H200");
        this.put("RAVISCANINA","H202");
        this.put("RE","H203");
        this.put("REA","H204");
        this.put("REALMONTE","H205");
        this.put("REANA DEL ROJALE","H206");
        this.put("REANO","H207");
        this.put("RECALE","H210");
        this.put("RECANATI","H211");
        this.put("RECCO","H212");
        this.put("RECETTO","H213");
        this.put("RECOARO TERME","H214");
        this.put("REDAVALLE","H216");
        this.put("REDONDESCO","H218");
        this.put("REFRANCORE","H219");
        this.put("REFRONTOLO","H220");
        this.put("REGALBUTO","H221");
        this.put("REGGELLO","H222");
        this.put("REGGIO DI CALABRIA","H224");
        this.put("REGGIO NELL'EMILIA","H223");
        this.put("REGGIOLO","H225");
        this.put("REINO","H227");
        this.put("REITANO","H228");
        this.put("REMANZACCO","H229");
        this.put("REMEDELLO","H230");
        this.put("RENATE","H233");
        this.put("RENDE","H235");
        this.put("RENON .RITTEN.","H236");
        this.put("RESANA","H238");
        this.put("RESCALDINA","H240");
        this.put("RESIA","H242");
        this.put("RESIUTTA","H244");
        this.put("RESUTTANO","H245");
        this.put("RETORBIDO","H246");
        this.put("REVELLO","H247");
        this.put("REVERE","H248");
        this.put("REVIGLIASCO D'ASTI","H250");
        this.put("REVINE LAGO","H253");
        this.put("REVO'","H254");
        this.put("REZZAGO","H255");
        this.put("REZZATO","H256");
        this.put("REZZO","H257");
        this.put("REZZOAGLIO","H258");
        this.put("RHEMES-NOTRE-DAME","H262");
        this.put("RHEMES-SAINT-GEORGES","H263");
        this.put("RHO","H264");
        this.put("RIACE","H265");
        this.put("RIALTO","H266");
        this.put("RIANO","H267");
        this.put("RIARDO","H268");
        this.put("RIBERA","H269");
        this.put("RIBORDONE","H270");
        this.put("RICADI","H271");
        this.put("RICALDONE","H272");
        this.put("RICCIA","H273");
        this.put("RICCIONE","H274");
        this.put("RICCO' DEL GOLFO DI SPEZIA","H275");
        this.put("RICENGO","H276");
        this.put("RICIGLIANO","H277");
        this.put("RIESE PIO X","H280");
        this.put("RIESI","H281");
        this.put("RIETI","H282");
        this.put("RIFIANO .RIFFIAN.","H284");
        this.put("RIFREDDO","H285");
        this.put("RIGNANO FLAMINIO","H288");
        this.put("RIGNANO GARGANICO","H287");
        this.put("RIGNANO SULL'ARNO","H286");
        this.put("RIGOLATO","H289");
        this.put("RIMA SAN GIUSEPPE","H291");
        this.put("RIMASCO","H292");
        this.put("RIMELLA","H293");
        this.put("RIMINI","H294");
        this.put("RIO","M391");
        this.put("RIO DI PUSTERIA .MUEHLBACH.","H299");
        this.put("RIO MARINA","H305");
        this.put("RIO NELL'ELBA","H297");
        this.put("RIO SALICETO","H298");
        this.put("RIOFREDDO","H300");
        this.put("RIOLA SARDO","H301");
        this.put("RIOLO TERME","H302");
        this.put("RIOLUNATO","H303");
        this.put("RIOMAGGIORE","H304");
        this.put("RIONERO IN VULTURE","H307");
        this.put("RIONERO SANNITICO","H308");
        this.put("RIPA TEATINA","H320");
        this.put("RIPABOTTONI","H311");
        this.put("RIPACANDIDA","H312");
        this.put("RIPALIMOSANI","H313");
        this.put("RIPALTA ARPINA","H314");
        this.put("RIPALTA CREMASCA","H315");
        this.put("RIPALTA GUERINA","H316");
        this.put("RIPARBELLA","H319");
        this.put("RIPATRANSONE","H321");
        this.put("RIPE","H322");
        this.put("RIPE SAN GINESIO","H323");
        this.put("RIPI","H324");
        this.put("RIPOSTO","H325");
        this.put("RITTANA","H326");
        this.put("RIVA DEL GARDA","H330");
        this.put("RIVA DEL PO","M410");
        this.put("RIVA DI SOLTO","H331");
        this.put("RIVA LIGURE","H328");
        this.put("RIVA PRESSO CHIERI","H337");
        this.put("RIVA VALDOBBIA","H329");
        this.put("RIVALBA","H333");
        this.put("RIVALTA BORMIDA","H334");
        this.put("RIVALTA DI TORINO","H335");
        this.put("RIVAMONTE AGORDINO","H327");
        this.put("RIVANAZZANO TERME","H336");
        this.put("RIVARA","H338");
        this.put("RIVAROLO CANAVESE","H340");
        this.put("RIVAROLO DEL RE ED UNITI","H341");
        this.put("RIVAROLO MANTOVANO","H342");
        this.put("RIVARONE","H343");
        this.put("RIVAROSSA","H344");
        this.put("RIVE","H346");
        this.put("RIVE D'ARCANO","H347");
        this.put("RIVELLO","H348");
        this.put("RIVERGARO","H350");
        this.put("RIVIGNANO","H352");
        this.put("RIVIGNANO TEOR","M317");
        this.put("RIVISONDOLI","H353");
        this.put("RIVODUTRI","H354");
        this.put("RIVOLI","H355");
        this.put("RIVOLI VERONESE","H356");
        this.put("RIVOLTA D'ADDA","H357");
        this.put("RIZZICONI","H359");
        this.put("RO","H360");
        this.put("ROANA","H361");
        this.put("ROASCHIA","H362");
        this.put("ROASCIO","H363");
        this.put("ROASIO","H365");
        this.put("ROATTO","H366");
        this.put("ROBASSOMERO","H367");
        this.put("ROBBIATE","G223");
        this.put("ROBBIO","H369");
        this.put("ROBECCHETTO CON INDUNO","H371");
        this.put("ROBECCO D'OGLIO","H372");
        this.put("ROBECCO PAVESE","H375");
        this.put("ROBECCO SUL NAVIGLIO","H373");
        this.put("ROBELLA","H376");
        this.put("ROBILANTE","H377");
        this.put("ROBURENT","H378");
        this.put("ROCCA CANAVESE","H386");
        this.put("ROCCA CANTERANO","H387");
        this.put("ROCCA CIGLIE'","H391");
        this.put("ROCCA D'ARAZZO","H392");
        this.put("ROCCA D'ARCE","H393");
        this.put("ROCCA DE' BALDI","H395");
        this.put("ROCCA DE' GIORGI","H396");
        this.put("ROCCA D'EVANDRO","H398");
        this.put("ROCCA DI BOTTE","H399");
        this.put("ROCCA DI CAMBIO","H400");
        this.put("ROCCA DI CAVE","H401");
        this.put("ROCCA DI MEZZO","H402");
        this.put("ROCCA DI NETO","H403");
        this.put("ROCCA DI PAPA","H404");
        this.put("ROCCA GRIMALDA","H414");
        this.put("ROCCA IMPERIALE","H416");
        this.put("ROCCA MASSIMA","H421");
        this.put("ROCCA PIA","H429");
        this.put("ROCCA PIETORE","H379");
        this.put("ROCCA PRIORA","H432");
        this.put("ROCCA SAN CASCIANO","H437");
        this.put("ROCCA SAN FELICE","H438");
        this.put("ROCCA SAN GIOVANNI","H439");
        this.put("ROCCA SANTA MARIA","H440");
        this.put("ROCCA SANTO STEFANO","H441");
        this.put("ROCCA SINIBALDA","H446");
        this.put("ROCCA SUSELLA","H450");
        this.put("ROCCABASCERANA","H382");
        this.put("ROCCABERNARDA","H383");
        this.put("ROCCABIANCA","H384");
        this.put("ROCCABRUNA","H385");
        this.put("ROCCACASALE","H389");
        this.put("ROCCADASPIDE","H394");
        this.put("ROCCAFIORITA","H405");
        this.put("ROCCAFLUVIONE","H390");
        this.put("ROCCAFORTE DEL GRECO","H408");
        this.put("ROCCAFORTE LIGURE","H406");
        this.put("ROCCAFORTE MONDOVI'","H407");
        this.put("ROCCAFORZATA","H409");
        this.put("ROCCAFRANCA","H410");
        this.put("ROCCAGIOVINE","H411");
        this.put("ROCCAGLORIOSA","H412");
        this.put("ROCCAGORGA","H413");
        this.put("ROCCALBEGNA","H417");
        this.put("ROCCALUMERA","H418");
        this.put("ROCCAMANDOLFI","H420");
        this.put("ROCCAMENA","H422");
        this.put("ROCCAMONFINA","H423");
        this.put("ROCCAMONTEPIANO","H424");
        this.put("ROCCAMORICE","H425");
        this.put("ROCCANOVA","H426");
        this.put("ROCCANTICA","H427");
        this.put("ROCCAPALUMBA","H428");
        this.put("ROCCAPIEMONTE","H431");
        this.put("ROCCARAINOLA","H433");
        this.put("ROCCARASO","H434");
        this.put("ROCCAROMANA","H436");
        this.put("ROCCASCALEGNA","H442");
        this.put("ROCCASECCA","H443");
        this.put("ROCCASECCA DEI VOLSCI","H444");
        this.put("ROCCASICURA","H445");
        this.put("ROCCASPARVERA","H447");
        this.put("ROCCASPINALVETI","H448");
        this.put("ROCCASTRADA","H449");
        this.put("ROCCAVALDINA","H380");
        this.put("ROCCAVERANO","H451");
        this.put("ROCCAVIGNALE","H452");
        this.put("ROCCAVIONE","H453");
        this.put("ROCCAVIVARA","H454");
        this.put("ROCCELLA IONICA","H456");
        this.put("ROCCELLA VALDEMONE","H455");
        this.put("ROCCHETTA A VOLTURNO","H458");
        this.put("ROCCHETTA BELBO","H462");
        this.put("ROCCHETTA DI VARA","H461");
        this.put("ROCCHETTA E CROCE","H459");
        this.put("ROCCHETTA LIGURE","H465");
        this.put("ROCCHETTA NERVINA","H460");
        this.put("ROCCHETTA PALAFEA","H466");
        this.put("ROCCHETTA SANT'ANTONIO","H467");
        this.put("ROCCHETTA TANARO","H468");
        this.put("RODANO","H470");
        this.put("RODDI","H472");
        this.put("RODDINO","H473");
        this.put("RODELLO","H474");
        this.put("RODENGO .RODENECK.","H475");
        this.put("RODENGO SAIANO","H477");
        this.put("RODERO","H478");
        this.put("RODI GARGANICO","H480");
        this.put("RODI' MILICI","H479");
        this.put("RODIGO","H481");
        this.put("ROE' VOLCIANO","H484");
        this.put("ROFRANO","H485");
        this.put("ROGENO","H486");
        this.put("ROGGIANO GRAVINA","H488");
        this.put("ROGHUDI","H489");
        this.put("ROGLIANO","H490");
        this.put("ROGNANO","H491");
        this.put("ROGNO","H492");
        this.put("ROGOLO","H493");
        this.put("ROIATE","H494");
        this.put("ROIO DEL SANGRO","H495");
        this.put("ROISAN","H497");
        this.put("ROLETTO","H498");
        this.put("ROLO","H500");
        this.put("ROMA","H501");
        this.put("ROMAGNANO AL MONTE","H503");
        this.put("ROMAGNANO SESIA","H502");
        this.put("ROMAGNESE","H505");
        this.put("ROMALLO","H506");
        this.put("ROMANA","H507");
        this.put("ROMANENGO","H508");
        this.put("ROMANO CANAVESE","H511");
        this.put("ROMANO D'EZZELINO","H512");
        this.put("ROMANO DI LOMBARDIA","H509");
        this.put("ROMANS D'ISONZO","H514");
        this.put("ROMBIOLO","H516");
        this.put("ROMENO","H517");
        this.put("ROMENTINO","H518");
        this.put("ROMETTA","H519");
        this.put("RONAGO","H521");
        this.put("RONCA'","H522");
        this.put("RONCADE","H523");
        this.put("RONCADELLE","H525");
        this.put("RONCARO","H527");
        this.put("RONCEGNO TERME","H528");
        this.put("RONCELLO","H529");
        this.put("RONCHI DEI LEGIONARI","H531");
        this.put("RONCHI VALSUGANA","H532");
        this.put("RONCHIS","H533");
        this.put("RONCIGLIONE","H534");
        this.put("RONCO ALL'ADIGE","H540");
        this.put("RONCO BIELLESE","H538");
        this.put("RONCO BRIANTINO","H537");
        this.put("RONCO CANAVESE","H539");
        this.put("RONCO SCRIVIA","H536");
        this.put("RONCOBELLO","H535");
        this.put("RONCOFERRARO","H541");
        this.put("RONCOFREDDO","H542");
        this.put("RONCOLA","H544");
        this.put("RONCONE","H545");
        this.put("RONDANINA","H546");
        this.put("RONDISSONE","H547");
        this.put("RONSECCO","H549");
        this.put("RONZO-CHIENIS","M303");
        this.put("RONZONE","H552");
        this.put("ROPPOLO","H553");
        this.put("RORA'","H554");
        this.put("ROSA'","H556");
        this.put("ROSARNO","H558");
        this.put("ROSASCO","H559");
        this.put("ROSATE","H560");
        this.put("ROSAZZA","H561");
        this.put("ROSCIANO","H562");
        this.put("ROSCIGNO","H564");
        this.put("ROSE","H565");
        this.put("ROSELLO","H566");
        this.put("ROSETO CAPO SPULICO","H572");
        this.put("ROSETO DEGLI ABRUZZI","F585");
        this.put("ROSETO VALFORTORE","H568");
        this.put("ROSIGNANO MARITTIMO","H570");
        this.put("ROSIGNANO MONFERRATO","H569");
        this.put("ROSOLINA","H573");
        this.put("ROSOLINI","H574");
        this.put("ROSORA","H575");
        this.put("ROSSA","H577");
        this.put("ROSSANA","H578");
        this.put("ROSSANO","H579");
        this.put("ROSSANO VENETO","H580");
        this.put("ROSSIGLIONE","H581");
        this.put("ROSTA","H583");
        this.put("ROTA D'IMAGNA","H584");
        this.put("ROTA GRECA","H585");
        this.put("ROTELLA","H588");
        this.put("ROTELLO","H589");
        this.put("ROTONDA","H590");
        this.put("ROTONDELLA","H591");
        this.put("ROTONDI","H592");
        this.put("ROTTOFRENO","H593");
        this.put("ROTZO","H594");
        this.put("ROURE","H555");
        this.put("ROVAGNATE","H596");
        this.put("ROVASENDA","H364");
        this.put("ROVATO","H598");
        this.put("ROVEGNO","H599");
        this.put("ROVELLASCA","H601");
        this.put("ROVELLO PORRO","H602");
        this.put("ROVERBELLA","H604");
        this.put("ROVERCHIARA","H606");
        this.put("ROVERE' DELLA LUNA","H607");
        this.put("ROVERE' VERONESE","H608");
        this.put("ROVEREDO DI GUA'","H610");
        this.put("ROVEREDO IN PIANO","H609");
        this.put("ROVERETO","H612");
        this.put("ROVESCALA","H614");
        this.put("ROVETTA","H615");
        this.put("ROVIANO","H618");
        this.put("ROVIGO","H620");
        this.put("ROVITO","H621");
        this.put("ROVOLON","H622");
        this.put("ROZZANO","H623");
        this.put("RUBANO","H625");
        this.put("RUBIANA","H627");
        this.put("RUBIERA","H628");
        this.put("RUDA","H629");
        this.put("RUDIANO","H630");
        this.put("RUEGLIO","H631");
        this.put("RUFFANO","H632");
        this.put("RUFFIA","H633");
        this.put("RUFFRE'-MENDOLA","H634");
        this.put("RUFINA","H635");
        this.put("RUINAS","F271");
        this.put("RUINO","H637");
        this.put("RUMO","H639");
        this.put("RUOTI","H641");
        this.put("RUSSI","H642");
        this.put("RUTIGLIANO","H643");
        this.put("RUTINO","H644");
        this.put("RUVIANO","H165");
        this.put("RUVO DEL MONTE","H646");
        this.put("RUVO DI PUGLIA","H645");
        this.put("SABAUDIA","H647");
        this.put("SABBIA","H648");
        this.put("SABBIO CHIESE","H650");
        this.put("SABBIONETA","H652");
        this.put("SACCO","H654");
        this.put("SACCOLONGO","H655");
        this.put("SACILE","H657");
        this.put("SACROFANO","H658");
        this.put("SADALI","H659");
        this.put("SAGAMA","H661");
        this.put("SAGLIANO MICCA","H662");
        this.put("SAGRADO","H665");
        this.put("SAGRON MIS","H666");
        this.put("SAINT-CHRISTOPHE","H669");
        this.put("SAINT-DENIS","H670");
        this.put("SAINT-MARCEL","H671");
        this.put("SAINT-NICOLAS","H672");
        this.put("SAINT-OYEN","H673");
        this.put("SAINT-PIERRE","H674");
        this.put("SAINT-RHEMY-EN-BOSSES","H675");
        this.put("SAINT-VINCENT","H676");
        this.put("SALA BAGANZA","H682");
        this.put("SALA BIELLESE","H681");
        this.put("SALA BOLOGNESE","H678");
        this.put("SALA COMACINA","H679");
        this.put("SALA CONSILINA","H683");
        this.put("SALA MONFERRATO","H677");
        this.put("SALANDRA","H687");
        this.put("SALAPARUTA","H688");
        this.put("SALARA","H689");
        this.put("SALASCO","H690");
        this.put("SALASSA","H691");
        this.put("SALBERTRAND","H684");
        this.put("SALCEDO","F810");
        this.put("SALCITO","H693");
        this.put("SALE","H694");
        this.put("SALE DELLE LANGHE","H695");
        this.put("SALE MARASINO","H699");
        this.put("SALE SAN GIOVANNI","H704");
        this.put("SALEMI","H700");
        this.put("SALENTO","H686");
        this.put("SALERANO CANAVESE","H702");
        this.put("SALERANO SUL LAMBRO","H701");
        this.put("SALERNO","H703");
        this.put("SALETTO","H705");
        this.put("SALGAREDA","H706");
        this.put("SALI VERCELLESE","H707");
        this.put("SALICE SALENTINO","H708");
        this.put("SALICETO","H710");
        this.put("SALISANO","H713");
        this.put("SALIZZOLE","H714");
        this.put("SALLE","H715");
        this.put("SALMOUR","H716");
        this.put("SALO'","H717");
        this.put("SALORNO SULLA STRADA DEL VINO .SALURN AN DER","H719");
        this.put("SALSOMAGGIORE TERME","H720");
        this.put("SALTARA","H721");
        this.put("SALTRIO","H723");
        this.put("SALUDECIO","H724");
        this.put("SALUGGIA","H725");
        this.put("SALUSSOLA","H726");
        this.put("SALUZZO","H727");
        this.put("SALVE","H729");
        this.put("SALVIROLA","H731");
        this.put("SALVITELLE","H732");
        this.put("SALZA DI PINEROLO","H734");
        this.put("SALZA IRPINA","H733");
        this.put("SALZANO","H735");
        this.put("SAMARATE","H736");
        this.put("SAMASSI","H738");
        this.put("SAMATZAI","H739");
        this.put("SAMBUCA DI SICILIA","H743");
        this.put("SAMBUCA PISTOIESE","H744");
        this.put("SAMBUCI","H745");
        this.put("SAMBUCO","H746");
        this.put("SAMMICHELE DI BARI","H749");
        this.put("SAMO","H013");
        this.put("SAMOLACO","H752");
        this.put("SAMONE","H753");
        this.put("SAMONE","H754");
        this.put("SAMPEYRE","H755");
        this.put("SAMUGHEO","H756");
        this.put("SAN BARTOLOMEO AL MARE","H763");
        this.put("SAN BARTOLOMEO IN GALDO","H764");
        this.put("SAN BARTOLOMEO VAL CAVARGNA","H760");
        this.put("SAN BASILE","H765");
        this.put("SAN BASILIO","H766");
        this.put("SAN BASSANO","H767");
        this.put("SAN BELLINO","H768");
        this.put("SAN BENEDETTO BELBO","H770");
        this.put("SAN BENEDETTO DEI MARSI","H772");
        this.put("SAN BENEDETTO DEL TRONTO","H769");
        this.put("SAN BENEDETTO IN PERILLIS","H773");
        this.put("SAN BENEDETTO PO","H771");
        this.put("SAN BENEDETTO ULLANO","H774");
        this.put("SAN BENEDETTO VAL DI SAMBRO","G566");
        this.put("SAN BENIGNO CANAVESE","H775");
        this.put("SAN BERNARDINO VERBANO","H777");
        this.put("SAN BIAGIO DELLA CIMA","H780");
        this.put("SAN BIAGIO DI CALLALTA","H781");
        this.put("SAN BIAGIO PLATANI","H778");
        this.put("SAN BIAGIO SARACINISCO","H779");
        this.put("SAN BIASE","H782");
        this.put("SAN BONIFACIO","H783");
        this.put("SAN BUONO","H784");
        this.put("SAN CALOGERO","H785");
        this.put("SAN CANDIDO .INNICHEN.","H786");
        this.put("SAN CANZIAN D'ISONZO","H787");
        this.put("SAN CARLO CANAVESE","H789");
        this.put("SAN CASCIANO DEI BAGNI","H790");
        this.put("SAN CASCIANO IN VAL DI PESA","H791");
        this.put("SAN CASSIANO","M264");
        this.put("SAN CATALDO","H792");
        this.put("SAN CESAREO","M295");
        this.put("SAN CESARIO DI LECCE","H793");
        this.put("SAN CESARIO SUL PANARO","H794");
        this.put("SAN CHIRICO NUOVO","H795");
        this.put("SAN CHIRICO RAPARO","H796");
        this.put("SAN CIPIRELLO","H797");
        this.put("SAN CIPRIANO D'AVERSA","H798");
        this.put("SAN CIPRIANO PICENTINO","H800");
        this.put("SAN CIPRIANO PO","H799");
        this.put("SAN CLEMENTE","H801");
        this.put("SAN COLOMBANO AL LAMBRO","H803");
        this.put("SAN COLOMBANO BELMONTE","H804");
        this.put("SAN COLOMBANO CERTENOLI","H802");
        this.put("SAN CONO","H805");
        this.put("SAN COSMO ALBANESE","H806");
        this.put("SAN COSTANTINO ALBANESE","H808");
        this.put("SAN COSTANTINO CALABRO","H807");
        this.put("SAN COSTANZO","H809");
        this.put("SAN CRISTOFORO","H810");
        this.put("SAN DAMIANO AL COLLE","H814");
        this.put("SAN DAMIANO D'ASTI","H811");
        this.put("SAN DAMIANO MACRA","H812");
        this.put("SAN DANIELE DEL FRIULI","H816");
        this.put("SAN DANIELE PO","H815");
        this.put("SAN DEMETRIO CORONE","H818");
        this.put("SAN DEMETRIO NE' VESTINI","H819");
        this.put("SAN DIDERO","H820");
        this.put("SAN DONA' DI PIAVE","H823");
        this.put("SAN DONACI","H822");
        this.put("SAN DONATO DI LECCE","H826");
        this.put("SAN DONATO DI NINEA","H825");
        this.put("SAN DONATO MILANESE","H827");
        this.put("SAN DONATO VAL DI COMINO","H824");
        this.put("SAN DORLIGO DELLA VALLE","D324");
        this.put("SAN FEDELE INTELVI","H830");
        this.put("SAN FELE","H831");
        this.put("SAN FELICE A CANCELLO","H834");
        this.put("SAN FELICE CIRCEO","H836");
        this.put("SAN FELICE DEL BENACO","H838");
        this.put("SAN FELICE DEL MOLISE","H833");
        this.put("SAN FELICE SUL PANARO","H835");
        this.put("SAN FERDINANDO","M277");
        this.put("SAN FERDINANDO DI PUGLIA","H839");
        this.put("SAN FERMO DELLA BATTAGLIA","H840");
        this.put("SAN FILI","H841");
        this.put("SAN FILIPPO DEL MELA","H842");
        this.put("SAN FIOR","H843");
        this.put("SAN FIORANO","H844");
        this.put("SAN FLORIANO DEL COLLIO","H845");
        this.put("SAN FLORO","H846");
        this.put("SAN FRANCESCO AL CAMPO","H847");
        this.put("SAN FRATELLO","H850");
        this.put("SAN GAVINO MONREALE","H856");
        this.put("SAN GEMINI","H857");
        this.put("SAN GENESIO ATESINO .JENESIEN.","H858");
        this.put("SAN GENESIO ED UNITI","H859");
        this.put("SAN GENNARO VESUVIANO","H860");
        this.put("SAN GERMANO CHISONE","H862");
        this.put("SAN GERMANO DEI BERICI","H863");
        this.put("SAN GERMANO VERCELLESE","H861");
        this.put("SAN GERVASIO BRESCIANO","H865");
        this.put("SAN GIACOMO DEGLI SCHIAVONI","H867");
        this.put("SAN GIACOMO DELLE SEGNATE","H870");
        this.put("SAN GIACOMO FILIPPO","H868");
        this.put("SAN GIACOMO VERCELLESE","B952");
        this.put("SAN GILLIO","H873");
        this.put("SAN GIMIGNANO","H875");
        this.put("SAN GINESIO","H876");
        this.put("SAN GIORGIO A CREMANO","H892");
        this.put("SAN GIORGIO A LIRI","H880");
        this.put("SAN GIORGIO ALBANESE","H881");
        this.put("SAN GIORGIO BIGARELLO","H883");
        this.put("SAN GIORGIO CANAVESE","H890");
        this.put("SAN GIORGIO DEL SANNIO","H894");
        this.put("SAN GIORGIO DELLA RICHINVELDA","H891");
        this.put("SAN GIORGIO DELLE PERTICHE","H893");
        this.put("SAN GIORGIO DI LOMELLINA","H885");
        this.put("SAN GIORGIO DI NOGARO","H895");
        this.put("SAN GIORGIO DI PESARO","H886");
        this.put("SAN GIORGIO DI PIANO","H896");
        this.put("SAN GIORGIO IN BOSCO","H897");
        this.put("SAN GIORGIO IONICO","H882");
        this.put("SAN GIORGIO LA MOLARA","H898");
        this.put("SAN GIORGIO LUCANO","H888");
        this.put("SAN GIORGIO MONFERRATO","H878");
        this.put("SAN GIORGIO MORGETO","H889");
        this.put("SAN GIORGIO PIACENTINO","H887");
        this.put("SAN GIORGIO SCARAMPI","H899");
        this.put("SAN GIORGIO SU LEGNANO","H884");
        this.put("SAN GIORIO DI SUSA","H900");
        this.put("SAN GIOVANNI A PIRO","H907");
        this.put("SAN GIOVANNI AL NATISONE","H906");
        this.put("SAN GIOVANNI BIANCO","H910");
        this.put("SAN GIOVANNI D'ASSO","H911");
        this.put("SAN GIOVANNI DEL DOSSO","H912");
        this.put("SAN GIOVANNI DI FASSA-SEN JAN","M390");
        this.put("SAN GIOVANNI DI GERACE","H903");
        this.put("SAN GIOVANNI GEMINI","H914");
        this.put("SAN GIOVANNI ILARIONE","H916");
        this.put("SAN GIOVANNI IN CROCE","H918");
        this.put("SAN GIOVANNI IN FIORE","H919");
        this.put("SAN GIOVANNI IN GALDO","H920");
        this.put("SAN GIOVANNI IN MARIGNANO","H921");
        this.put("SAN GIOVANNI IN PERSICETO","G467");
        this.put("SAN GIOVANNI INCARICO","H917");
        this.put("SAN GIOVANNI LA PUNTA","H922");
        this.put("SAN GIOVANNI LIPIONI","H923");
        this.put("SAN GIOVANNI LUPATOTO","H924");
        this.put("SAN GIOVANNI ROTONDO","H926");
        this.put("SAN GIOVANNI SUERGIU","G287");
        this.put("SAN GIOVANNI TEATINO","D690");
        this.put("SAN GIOVANNI VALDARNO","H901");
        this.put("SAN GIULIANO DEL SANNIO","H928");
        this.put("SAN GIULIANO DI PUGLIA","H929");
        this.put("SAN GIULIANO MILANESE","H930");
        this.put("SAN GIULIANO TERME","A562");
        this.put("SAN GIUSEPPE JATO","H933");
        this.put("SAN GIUSEPPE VESUVIANO","H931");
        this.put("SAN GIUSTINO","H935");
        this.put("SAN GIUSTO CANAVESE","H936");
        this.put("SAN GODENZO","H937");
        this.put("SAN GREGORIO DA SASSOLA","H942");
        this.put("SAN GREGORIO DI CATANIA","H940");
        this.put("SAN GREGORIO D'IPPONA","H941");
        this.put("SAN GREGORIO MAGNO","H943");
        this.put("SAN GREGORIO MATESE","H939");
        this.put("SAN GREGORIO NELLE ALPI","H938");
        this.put("SAN LAZZARO DI SAVENA","H945");
        this.put("SAN LEO","H949");
        this.put("SAN LEONARDO","H951");
        this.put("SAN LEONARDO IN PASSIRIA .ST LEONHARD IN PAS.","H952");
        this.put("SAN LEUCIO DEL SANNIO","H953");
        this.put("SAN LORENZELLO","H955");
        this.put("SAN LORENZO","H959");
        this.put("SAN LORENZO AL MARE","H957");
        this.put("SAN LORENZO BELLIZZI","H961");
        this.put("SAN LORENZO DEL VALLO","H962");
        this.put("SAN LORENZO DI SEBATO .ST LORENZEN.","H956");
        this.put("SAN LORENZO DORSINO","M345");
        this.put("SAN LORENZO IN BANALE","H966");
        this.put("SAN LORENZO IN CAMPO","H958");
        this.put("SAN LORENZO ISONTINO","H964");
        this.put("SAN LORENZO MAGGIORE","H967");
        this.put("SAN LORENZO NUOVO","H969");
        this.put("SAN LUCA","H970");
        this.put("SAN LUCIDO","H971");
        this.put("SAN LUPO","H973");
        this.put("SAN MANGO D'AQUINO","H976");
        this.put("SAN MANGO PIEMONTE","H977");
        this.put("SAN MANGO SUL CALORE","H975");
        this.put("SAN MARCELLINO","H978");
        this.put("SAN MARCELLO","H979");
        this.put("SAN MARCELLO PISTOIESE","H980");
        this.put("SAN MARCELLO PITEGLIO","M377");
        this.put("SAN MARCO ARGENTANO","H981");
        this.put("SAN MARCO D'ALUNZIO","H982");
        this.put("SAN MARCO DEI CAVOTI","H984");
        this.put("SAN MARCO EVANGELISTA","F043");
        this.put("SAN MARCO IN LAMIS","H985");
        this.put("SAN MARCO LA CATOLA","H986");
        this.put("SAN MARTINO AL TAGLIAMENTO","H999");
        this.put("SAN MARTINO ALFIERI","H987");
        this.put("SAN MARTINO BUON ALBERGO","I003");
        this.put("SAN MARTINO CANAVESE","H997");
        this.put("SAN MARTINO D'AGRI","H994");
        this.put("SAN MARTINO DALL'ARGINE","I005");
        this.put("SAN MARTINO DEL LAGO","I007");
        this.put("SAN MARTINO DI FINITA","H992");
        this.put("SAN MARTINO DI LUPARI","I008");
        this.put("SAN MARTINO DI VENEZZE","H996");
        this.put("SAN MARTINO IN BADIA .ST MARTIN IN THURN.","H988");
        this.put("SAN MARTINO IN PASSIRIA .ST MARTIN IN PASSEI.","H989");
        this.put("SAN MARTINO IN PENSILIS","H990");
        this.put("SAN MARTINO IN RIO","I011");
        this.put("SAN MARTINO IN STRADA","I012");
        this.put("SAN MARTINO SANNITA","I002");
        this.put("SAN MARTINO SICCOMARIO","I014");
        this.put("SAN MARTINO SULLA MARRUCINA","H991");
        this.put("SAN MARTINO VALLE CAUDINA","I016");
        this.put("SAN MARZANO DI SAN GIUSEPPE","I018");
        this.put("SAN MARZANO OLIVETO","I017");
        this.put("SAN MARZANO SUL SARNO","I019");
        this.put("SAN MASSIMO","I023");
        this.put("SAN MAURIZIO CANAVESE","I024");
        this.put("SAN MAURIZIO D'OPAGLIO","I025");
        this.put("SAN MAURO CASTELVERDE","I028");
        this.put("SAN MAURO CILENTO","I031");
        this.put("SAN MAURO DI SALINE","H712");
        this.put("SAN MAURO FORTE","I029");
        this.put("SAN MAURO LA BRUCA","I032");
        this.put("SAN MAURO MARCHESATO","I026");
        this.put("SAN MAURO PASCOLI","I027");
        this.put("SAN MAURO TORINESE","I030");
        this.put("SAN MICHELE AL TAGLIAMENTO","I040");
        this.put("SAN MICHELE ALL'ADIGE","I042");
        this.put("SAN MICHELE DI GANZARIA","I035");
        this.put("SAN MICHELE DI SERINO","I034");
        this.put("SAN MICHELE MONDOVI'","I037");
        this.put("SAN MICHELE SALENTINO","I045");
        this.put("SAN MINIATO","I046");
        this.put("SAN NAZARIO","I047");
        this.put("SAN NAZZARO","I049");
        this.put("SAN NAZZARO SESIA","I052");
        this.put("SAN NAZZARO VAL CAVARGNA","I051");
        this.put("SAN NICANDRO GARGANICO","I054");
        this.put("SAN NICOLA ARCELLA","I060");
        this.put("SAN NICOLA BARONIA","I061");
        this.put("SAN NICOLA DA CRISSA","I058");
        this.put("SAN NICOLA DELL'ALTO","I057");
        this.put("SAN NICOLA LA STRADA","I056");
        this.put("SAN NICOLA MANFREDI","I062");
        this.put("SAN NICOLO' D'ARCIDANO","A368");
        this.put("SAN NICOLO' DI COMELICO","I063");
        this.put("SAN NICOLO' GERREI","G383");
        this.put("SAN PANCRAZIO SALENTINO","I066");
        this.put("SAN PANCRAZIO .ST PANKRAZ.","I065");
        this.put("SAN PAOLO","G407");
        this.put("SAN PAOLO ALBANESE","B906");
        this.put("SAN PAOLO BEL SITO","I073");
        this.put("SAN PAOLO CERVO","I074");
        this.put("SAN PAOLO D'ARGON","B310");
        this.put("SAN PAOLO DI CIVITATE","I072");
        this.put("SAN PAOLO DI JESI","I071");
        this.put("SAN PAOLO SOLBRITO","I076");
        this.put("SAN PELLEGRINO TERME","I079");
        this.put("SAN PIER D'ISONZO","I082");
        this.put("SAN PIER NICETO","I084");
        this.put("SAN PIERO A SIEVE","I085");
        this.put("SAN PIERO PATTI","I086");
        this.put("SAN PIETRO A MAIDA","I093");
        this.put("SAN PIETRO AL NATISONE","I092");
        this.put("SAN PIETRO AL TANAGRO","I089");
        this.put("SAN PIETRO APOSTOLO","I095");
        this.put("SAN PIETRO AVELLANA","I096");
        this.put("SAN PIETRO CLARENZA","I098");
        this.put("SAN PIETRO DI CADORE","I088");
        this.put("SAN PIETRO DI CARIDA'","I102");
        this.put("SAN PIETRO DI FELETTO","I103");
        this.put("SAN PIETRO DI MORUBIO","I105");
        this.put("SAN PIETRO IN AMANTEA","I108");
        this.put("SAN PIETRO IN CARIANO","I109");
        this.put("SAN PIETRO IN CASALE","I110");
        this.put("SAN PIETRO IN CERRO","G788");
        this.put("SAN PIETRO IN GU","I107");
        this.put("SAN PIETRO IN GUARANO","I114");
        this.put("SAN PIETRO IN LAMA","I115");
        this.put("SAN PIETRO INFINE","I113");
        this.put("SAN PIETRO MOSEZZO","I116");
        this.put("SAN PIETRO MUSSOLINO","I117");
        this.put("SAN PIETRO VAL LEMINA","I090");
        this.put("SAN PIETRO VERNOTICO","I119");
        this.put("SAN PIETRO VIMINARIO","I120");
        this.put("SAN PIO DELLE CAMERE","I121");
        this.put("SAN POLO DEI CAVALIERI","I125");
        this.put("SAN POLO D'ENZA","I123");
        this.put("SAN POLO DI PIAVE","I124");
        this.put("SAN POLO MATESE","I122");
        this.put("SAN PONSO","I126");
        this.put("SAN POSSIDONIO","I128");
        this.put("SAN POTITO SANNITICO","I130");
        this.put("SAN POTITO ULTRA","I129");
        this.put("SAN PRISCO","I131");
        this.put("SAN PROCOPIO","I132");
        this.put("SAN PROSPERO","I133");
        this.put("SAN QUIRICO D'ORCIA","I135");
        this.put("SAN QUIRINO","I136");
        this.put("SAN RAFFAELE CIMENA","I137");
        this.put("SAN ROBERTO","I139");
        this.put("SAN ROCCO AL PORTO","I140");
        this.put("SAN ROMANO IN GARFAGNANA","I142");
        this.put("SAN RUFO","I143");
        this.put("SAN SALVATORE DI FITALIA","I147");
        this.put("SAN SALVATORE MONFERRATO","I144");
        this.put("SAN SALVATORE TELESINO","I145");
        this.put("SAN SALVO","I148");
        this.put("SAN SEBASTIANO AL VESUVIO","I151");
        this.put("SAN SEBASTIANO CURONE","I150");
        this.put("SAN SEBASTIANO DA PO","I152");
        this.put("SAN SECONDO DI PINEROLO","I154");
        this.put("SAN SECONDO PARMENSE","I153");
        this.put("SAN SEVERINO LUCANO","I157");
        this.put("SAN SEVERINO MARCHE","I156");
        this.put("SAN SEVERO","I158");
        this.put("SAN SIRO","I162");
        this.put("SAN SOSSIO BARONIA","I163");
        this.put("SAN SOSTENE","I164");
        this.put("SAN SOSTI","I165");
        this.put("SAN SPERATE","I166");
        this.put("SAN STINO DI LIVENZA","I373");
        this.put("SAN TAMMARO","I261");
        this.put("SAN TEODORO","I329");
        this.put("SAN TEODORO","I328");
        this.put("SAN TOMASO AGORDINO","I347");
        this.put("SAN VALENTINO IN ABRUZZO CITERIORE","I376");
        this.put("SAN VALENTINO TORIO","I377");
        this.put("SAN VENANZO","I381");
        this.put("SAN VENDEMIANO","I382");
        this.put("SAN VERO MILIS","I384");
        this.put("SAN VINCENZO","I390");
        this.put("SAN VINCENZO LA COSTA","I388");
        this.put("SAN VINCENZO VALLE ROVETO","I389");
        this.put("SAN VITALIANO","I391");
        this.put("SAN VITO","I402");
        this.put("SAN VITO AL TAGLIAMENTO","I403");
        this.put("SAN VITO AL TORRE","I404");
        this.put("SAN VITO CHIETINO","I394");
        this.put("SAN VITO DEI NORMANNI","I396");
        this.put("SAN VITO DI CADORE","I392");
        this.put("SAN VITO DI FAGAGNA","I405");
        this.put("SAN VITO DI LEGUZZANO","I401");
        this.put("SAN VITO LO CAPO","I407");
        this.put("SAN VITO ROMANO","I400");
        this.put("SAN VITO SULLO IONIO","I393");
        this.put("SAN VITTORE DEL LAZIO","I408");
        this.put("SAN VITTORE OLONA","I409");
        this.put("SAN ZENO DI MONTAGNA","I414");
        this.put("SAN ZENO NAVIGLIO","I412");
        this.put("SAN ZENONE AL LAMBRO","I415");
        this.put("SAN ZENONE AL PO","I416");
        this.put("SAN ZENONE DEGLI EZZELINI","I417");
        this.put("SANARICA","H757");
        this.put("SANDIGLIANO","H821");
        this.put("SANDRIGO","H829");
        this.put("SANFRE'","H851");
        this.put("SANFRONT","H852");
        this.put("SANGANO","H855");
        this.put("SANGIANO","H872");
        this.put("SANGINETO","H877");
        this.put("SANGUINETTO","H944");
        this.put("SANLURI","H974");
        this.put("SANNAZZARO DE' BURGONDI","I048");
        this.put("SANNICANDRO DI BARI","I053");
        this.put("SANNICOLA","I059");
        this.put("SANREMO","I138");
        this.put("SANSEPOLCRO","I155");
        this.put("SANTA BRIGIDA","I168");
        this.put("SANTA CATERINA ALBANESE","I171");
        this.put("SANTA CATERINA DELLO IONIO","I170");
        this.put("SANTA CATERINA VILLARMOSA","I169");
        this.put("SANTA CESAREA TERME","I172");
        this.put("SANTA CRISTINA D'ASPROMONTE","I176");
        this.put("SANTA CRISTINA E BISSONE","I175");
        this.put("SANTA CRISTINA GELA","I174");
        this.put("SANTA CRISTINA VALGARDENA .ST CHRISTINA IN G.","I173");
        this.put("SANTA CROCE CAMERINA","I178");
        this.put("SANTA CROCE DEL SANNIO","I179");
        this.put("SANTA CROCE DI MAGLIANO","I181");
        this.put("SANTA CROCE SULL'ARNO","I177");
        this.put("SANTA DOMENICA TALAO","I183");
        this.put("SANTA DOMENICA VITTORIA","I184");
        this.put("SANTA ELISABETTA","I185");
        this.put("SANTA FIORA","I187");
        this.put("SANTA FLAVIA","I188");
        this.put("SANTA GIULETTA","I203");
        this.put("SANTA GIUSTA","I205");
        this.put("SANTA GIUSTINA","I206");
        this.put("SANTA GIUSTINA IN COLLE","I207");
        this.put("SANTA LUCE","I217");
        this.put("SANTA LUCIA DEL MELA","I220");
        this.put("SANTA LUCIA DI PIAVE","I221");
        this.put("SANTA LUCIA DI SERINO","I219");
        this.put("SANTA MARGHERITA D'ADIGE","I226");
        this.put("SANTA MARGHERITA DI BELICE","I224");
        this.put("SANTA MARGHERITA DI STAFFORA","I230");
        this.put("SANTA MARGHERITA LIGURE","I225");
        this.put("SANTA MARIA A MONTE","I232");
        this.put("SANTA MARIA A VICO","I233");
        this.put("SANTA MARIA CAPUA VETERE","I234");
        this.put("SANTA MARIA COGHINAS","M284");
        this.put("SANTA MARIA DEL CEDRO","C717");
        this.put("SANTA MARIA DEL MOLISE","I238");
        this.put("SANTA MARIA DELLA VERSA","I237");
        this.put("SANTA MARIA DI LICODIA","I240");
        this.put("SANTA MARIA DI SALA","I242");
        this.put("SANTA MARIA HOE'","I243");
        this.put("SANTA MARIA IMBARO","I244");
        this.put("SANTA MARIA LA CARITA'","M273");
        this.put("SANTA MARIA LA FOSSA","I247");
        this.put("SANTA MARIA LA LONGA","I248");
        this.put("SANTA MARIA MAGGIORE","I249");
        this.put("SANTA MARIA NUOVA","I251");
        this.put("SANTA MARINA","I253");
        this.put("SANTA MARINA SALINA","I254");
        this.put("SANTA MARINELLA","I255");
        this.put("SANTA NINFA","I291");
        this.put("SANTA PAOLINA","I301");
        this.put("SANTA SEVERINA","I308");
        this.put("SANTA SOFIA","I310");
        this.put("SANTA SOFIA D'EPIRO","I309");
        this.put("SANTA TERESA DI RIVA","I311");
        this.put("SANTA TERESA GALLURA","I312");
        this.put("SANTA VENERINA","I314");
        this.put("SANTA VITTORIA D'ALBA","I316");
        this.put("SANTA VITTORIA IN MATENANO","I315");
        this.put("SANTADI","I182");
        this.put("SANT'AGAPITO","I189");
        this.put("SANT'AGATA BOLOGNESE","I191");
        this.put("SANT'AGATA DE' GOTI","I197");
        this.put("SANT'AGATA DEL BIANCO","I198");
        this.put("SANT'AGATA DI ESARO","I192");
        this.put("SANT'AGATA DI MILITELLO","I199");
        this.put("SANT'AGATA DI PUGLIA","I193");
        this.put("SANT'AGATA FELTRIA","I201");
        this.put("SANT'AGATA FOSSILI","I190");
        this.put("SANT'AGATA LI BATTIATI","I202");
        this.put("SANT'AGATA SUL SANTERNO","I196");
        this.put("SANT'AGNELLO","I208");
        this.put("SANT'AGOSTINO","I209");
        this.put("SANT'ALBANO STURA","I210");
        this.put("SANT'ALESSIO CON VIALONE","I213");
        this.put("SANT'ALESSIO IN ASPROMONTE","I214");
        this.put("SANT'ALESSIO SICULO","I215");
        this.put("SANT'ALFIO","I216");
        this.put("SANT'AMBROGIO DI TORINO","I258");
        this.put("SANT'AMBROGIO DI VALPOLICELLA","I259");
        this.put("SANT'AMBROGIO SUL GARIGLIANO","I256");
        this.put("SANT'ANASTASIA","I262");
        this.put("SANT'ANATOLIA DI NARCO","I263");
        this.put("SANT'ANDREA APOSTOLO DELLO IONIO","I266");
        this.put("SANT'ANDREA DEL GARIGLIANO","I265");
        this.put("SANT'ANDREA DI CONZA","I264");
        this.put("SANT'ANDREA FRIUS","I271");
        this.put("SANT'ANGELO A CUPOLO","I277");
        this.put("SANT'ANGELO A FASANELLA","I278");
        this.put("SANT'ANGELO A SCALA","I280");
        this.put("SANT'ANGELO ALL'ESCA","I279");
        this.put("SANT'ANGELO D'ALIFE","I273");
        this.put("SANT'ANGELO DEI LOMBARDI","I281");
        this.put("SANT'ANGELO DEL PESCO","I282");
        this.put("SANT'ANGELO DI BROLO","I283");
        this.put("SANT'ANGELO DI PIOVE DI SACCO","I275");
        this.put("SANT'ANGELO IN LIZZOLA","I285");
        this.put("SANT'ANGELO IN PONTANO","I286");
        this.put("SANT'ANGELO IN VADO","I287");
        this.put("SANT'ANGELO LE FRATTE","I288");
        this.put("SANT'ANGELO LIMOSANO","I289");
        this.put("SANT'ANGELO LODIGIANO","I274");
        this.put("SANT'ANGELO LOMELLINA","I276");
        this.put("SANT'ANGELO MUXARO","I290");
        this.put("SANT'ANGELO ROMANO","I284");
        this.put("SANT'ANNA ARRESI","M209");
        this.put("SANT'ANNA D'ALFAEDO","I292");
        this.put("SANT'ANTIMO","I293");
        this.put("SANT'ANTIOCO","I294");
        this.put("SANT'ANTONINO DI SUSA","I296");
        this.put("SANT'ANTONIO ABATE","I300");
        this.put("SANT'ANTONIO DI GALLURA","M276");
        this.put("SANT'APOLLINARE","I302");
        this.put("SANT'ARCANGELO","I305");
        this.put("SANTARCANGELO DI ROMAGNA","I304");
        this.put("SANT'ARCANGELO TRIMONTE","F557");
        this.put("SANT'ARPINO","I306");
        this.put("SANT'ARSENIO","I307");
        this.put("SANTE MARIE","I326");
        this.put("SANT'EGIDIO ALLA VIBRATA","I318");
        this.put("SANT'EGIDIO DEL MONTE ALBINO","I317");
        this.put("SANT'ELENA","I319");
        this.put("SANT'ELENA SANNITA","B466");
        this.put("SANT'ELIA A PIANISI","I320");
        this.put("SANT'ELIA FIUMERAPIDO","I321");
        this.put("SANT'ELPIDIO A MARE","I324");
        this.put("SANTENA","I327");
        this.put("SANTERAMO IN COLLE","I330");
        this.put("SANT'EUFEMIA A MAIELLA","I332");
        this.put("SANT'EUFEMIA D'ASPROMONTE","I333");
        this.put("SANT'EUSANIO DEL SANGRO","I335");
        this.put("SANT'EUSANIO FORCONESE","I336");
        this.put("SANTHIA'","I337");
        this.put("SANTI COSMA E DAMIANO","I339");
        this.put("SANT'ILARIO DELLO IONIO","I341");
        this.put("SANT'ILARIO D'ENZA","I342");
        this.put("SANT'IPPOLITO","I344");
        this.put("SANTO STEFANO AL MARE","I365");
        this.put("SANTO STEFANO BELBO","I367");
        this.put("SANTO STEFANO D'AVETO","I368");
        this.put("SANTO STEFANO DEL SOLE","I357");
        this.put("SANTO STEFANO DI CADORE","C919");
        this.put("SANTO STEFANO DI CAMASTRA","I370");
        this.put("SANTO STEFANO DI MAGRA","I363");
        this.put("SANTO STEFANO DI ROGLIANO","I359");
        this.put("SANTO STEFANO DI SESSANIO","I360");
        this.put("SANTO STEFANO IN ASPROMONTE","I371");
        this.put("SANTO STEFANO LODIGIANO","I362");
        this.put("SANTO STEFANO QUISQUINA","I356");
        this.put("SANTO STEFANO ROERO","I372");
        this.put("SANTO STEFANO TICINO","I361");
        this.put("SANT'OLCESE","I346");
        this.put("SANTOMENNA","I260");
        this.put("SANT'OMERO","I348");
        this.put("SANT'OMOBONO TERME","I349");
        this.put("SANT'OMOBONO TERME","M333");
        this.put("SANT'ONOFRIO","I350");
        this.put("SANTOPADRE","I351");
        this.put("SANT'ORESTE","I352");
        this.put("SANTORSO","I353");
        this.put("SANT'ORSOLA TERME","I354");
        this.put("SANTU LUSSURGIU","I374");
        this.put("SANT'URBANO","I375");
        this.put("SANZA","I410");
        this.put("SANZENO","I411");
        this.put("SAONARA","I418");
        this.put("SAPONARA","I420");
        this.put("SAPPADA","I421");
        this.put("SAPRI","I422");
        this.put("SARACENA","I423");
        this.put("SARACINESCO","I424");
        this.put("SARCEDO","I425");
        this.put("SARCONI","I426");
        this.put("SARDARA","I428");
        this.put("SARDIGLIANO","I429");
        this.put("SAREGO","I430");
        this.put("SARENTINO .SARNTAL.","I431");
        this.put("SAREZZANO","I432");
        this.put("SAREZZO","I433");
        this.put("SARMATO","I434");
        this.put("SARMEDE","I435");
        this.put("SARNANO","I436");
        this.put("SARNICO","I437");
        this.put("SARNO","I438");
        this.put("SARNONICO","I439");
        this.put("SARONNO","I441");
        this.put("SARRE","I442");
        this.put("SARROCH","I443");
        this.put("SARSINA","I444");
        this.put("SARTEANO","I445");
        this.put("SARTIRANA LOMELLINA","I447");
        this.put("SARULE","I448");
        this.put("SARZANA","I449");
        this.put("SASSANO","I451");
        this.put("SASSARI","I452");
        this.put("SASSELLO","I453");
        this.put("SASSETTA","I454");
        this.put("SASSINORO","I455");
        this.put("SASSO DI CASTALDA","I457");
        this.put("SASSO MARCONI","G972");
        this.put("SASSOCORVARO","I459");
        this.put("SASSOCORVARO AUDITORE","M413");
        this.put("SASSOFELTRIO","I460");
        this.put("SASSOFERRATO","I461");
        this.put("SASSUOLO","I462");
        this.put("SATRIANO","I463");
        this.put("SATRIANO DI LUCANIA","G614");
        this.put("SAURIS","I464");
        this.put("SAUZE DI CESANA","I465");
        this.put("SAUZE D'OULX","I466");
        this.put("SAVA","I467");
        this.put("SAVELLI","I468");
        this.put("SAVIANO","I469");
        this.put("SAVIGLIANO","I470");
        this.put("SAVIGNANO IRPINO","I471");
        this.put("SAVIGNANO SUL PANARO","I473");
        this.put("SAVIGNANO SUL RUBICONE","I472");
        this.put("SAVIGNO","I474");
        this.put("SAVIGNONE","I475");
        this.put("SAVIORE DELL'ADAMELLO","I476");
        this.put("SAVOCA","I477");
        this.put("SAVOGNA","I478");
        this.put("SAVOGNA D'ISONZO","I479");
        this.put("SAVOIA DI LUCANIA","H730");
        this.put("SAVONA","I480");
        this.put("SCAFA","I482");
        this.put("SCAFATI","I483");
        this.put("SCAGNELLO","I484");
        this.put("SCALA","I486");
        this.put("SCALA COELI","I485");
        this.put("SCALDASOLE","I487");
        this.put("SCALEA","I489");
        this.put("SCALENGHE","I490");
        this.put("SCALETTA ZANCLEA","I492");
        this.put("SCAMPITELLA","I493");
        this.put("SCANDALE","I494");
        this.put("SCANDIANO","I496");
        this.put("SCANDICCI","B962");
        this.put("SCANDOLARA RAVARA","I497");
        this.put("SCANDOLARA RIPA D'OGLIO","I498");
        this.put("SCANDRIGLIA","I499");
        this.put("SCANNO","I501");
        this.put("SCANO DI MONTIFERRO","I503");
        this.put("SCANSANO","I504");
        this.put("SCANZANO JONICO","M256");
        this.put("SCANZOROSCIATE","I506");
        this.put("SCAPOLI","I507");
        this.put("SCARLINO","I510");
        this.put("SCARMAGNO","I511");
        this.put("SCARNAFIGI","I512");
        this.put("SCARPERIA","I514");
        this.put("SCARPERIA E SAN PIERO","M326");
        this.put("SCENA .SCHENNA.","I519");
        this.put("SCERNI","I520");
        this.put("SCHEGGIA E PASCELUPO","I522");
        this.put("SCHEGGINO","I523");
        this.put("SCHIAVI DI ABRUZZO","I526");
        this.put("SCHIAVON","I527");
        this.put("SCHIGNANO","I529");
        this.put("SCHILPARIO","I530");
        this.put("SCHIO","I531");
        this.put("SCHIVENOGLIA","I532");
        this.put("SCIACCA","I533");
        this.put("SCIARA","I534");
        this.put("SCICLI","I535");
        this.put("SCIDO","I536");
        this.put("SCIGLIANO","D290");
        this.put("SCILLA","I537");
        this.put("SCILLATO","I538");
        this.put("SCIOLZE","I539");
        this.put("SCISCIANO","I540");
        this.put("SCLAFANI BAGNI","I541");
        this.put("SCONTRONE","I543");
        this.put("SCOPA","I544");
        this.put("SCOPELLO","I545");
        this.put("SCOPPITO","I546");
        this.put("SCORDIA","I548");
        this.put("SCORRANO","I549");
        this.put("SCORZE'","I551");
        this.put("SCURCOLA MARSICANA","I553");
        this.put("SCURELLE","I554");
        this.put("SCURZOLENGO","I555");
        this.put("SEBORGA","I556");
        this.put("SECINARO","I558");
        this.put("SECLI'","I559");
        this.put("SECUGNAGO","I561");
        this.put("SEDEGLIANO","I562");
        this.put("SEDICO","I563");
        this.put("SEDILO","I564");
        this.put("SEDINI","I565");
        this.put("SEDRIANO","I566");
        this.put("SEDRINA","I567");
        this.put("SEFRO","I569");
        this.put("SEGARIU","I570");
        this.put("SEGGIANO","I571");
        this.put("SEGNI","I573");
        this.put("SEGONZANO","I576");
        this.put("SEGRATE","I577");
        this.put("SEGUSINO","I578");
        this.put("SELARGIUS","I580");
        this.put("SELCI","I581");
        this.put("SELEGAS","I582");
        this.put("SELLA GIUDICARIE","M360");
        this.put("SELLANO","I585");
        this.put("SELLERO","I588");
        this.put("SELLIA","I589");
        this.put("SELLIA MARINA","I590");
        this.put("SELVA DEI MOLINI .MUEHLWALD.","I593");
        this.put("SELVA DI CADORE","I592");
        this.put("SELVA DI PROGNO","I594");
        this.put("SELVA DI VAL GARDENA .WOLKENSTEIN IN GROEDEN.","I591");
        this.put("SELVAZZANO DENTRO","I595");
        this.put("SELVE MARCONE","I596");
        this.put("SELVINO","I597");
        this.put("SEMESTENE","I598");
        this.put("SEMIANA","I599");
        this.put("SEMINARA","I600");
        this.put("SEMPRONIANO","I601");
        this.put("SENAGO","I602");
        this.put("SENALES .SCHNALS.","I604");
        this.put("SENALE-SAN FELICE-UNSERE LIEBE FRAU IM WALD","I603");
        this.put("SENEGHE","I605");
        this.put("SENERCHIA","I606");
        this.put("SENIGA","I607");
        this.put("SENIGALLIA","I608");
        this.put("SENIS","I609");
        this.put("SENISE","I610");
        this.put("SENNA COMASCO","I611");
        this.put("SENNA LODIGIANA","I612");
        this.put("SENNARIOLO","I613");
        this.put("SENNORI","I614");
        this.put("SENORBI'","I615");
        this.put("SEPINO","I618");
        this.put("SEPPIANA","I619");
        this.put("SEQUALS","I621");
        this.put("SERAVEZZA","I622");
        this.put("SERDIANA","I624");
        this.put("SEREGNO","I625");
        this.put("SEREN DEL GRAPPA","I626");
        this.put("SERGNANO","I627");
        this.put("SERIATE","I628");
        this.put("SERINA","I629");
        this.put("SERINO","I630");
        this.put("SERLE","I631");
        this.put("SERMIDE E FELONICA","I632");
        this.put("SERMONETA","I634");
        this.put("SERNAGLIA DELLA BATTAGLIA","I635");
        this.put("SERNIO","I636");
        this.put("SEROLE","I637");
        this.put("SERRA D'AIELLO","I642");
        this.put("SERRA DE' CONTI","I643");
        this.put("SERRA PEDACE","I650");
        this.put("SERRA RICCO'","I640");
        this.put("SERRA SAN BRUNO","I639");
        this.put("SERRA SAN QUIRICO","I653");
        this.put("SERRA SANT'ABBONDIO","I654");
        this.put("SERRACAPRIOLA","I641");
        this.put("SERRADIFALCO","I644");
        this.put("SERRALUNGA D'ALBA","I646");
        this.put("SERRALUNGA DI CREA","I645");
        this.put("SERRAMANNA","I647");
        this.put("SERRAMAZZONI","F357");
        this.put("SERRAMEZZANA","I648");
        this.put("SERRAMONACESCA","I649");
        this.put("SERRAPETRONA","I651");
        this.put("SERRARA FONTANA","I652");
        this.put("SERRASTRETTA","I655");
        this.put("SERRATA","I656");
        this.put("SERRAVALLE A PO","I662");
        this.put("SERRAVALLE DI CHIENTI","I661");
        this.put("SERRAVALLE LANGHE","I659");
        this.put("SERRAVALLE PISTOIESE","I660");
        this.put("SERRAVALLE SCRIVIA","I657");
        this.put("SERRAVALLE SESIA","I663");
        this.put("SERRE","I666");
        this.put("SERRENTI","I667");
        this.put("SERRI","I668");
        this.put("SERRONE","I669");
        this.put("SERRUNGARINA","I670");
        this.put("SERSALE","I671");
        this.put("SERVIGLIANO","C070");
        this.put("SESSA AURUNCA","I676");
        this.put("SESSA CILENTO","I677");
        this.put("SESSAME","I678");
        this.put("SESSANO DEL MOLISE","I679");
        this.put("SESTA GODANO","E070");
        this.put("SESTINO","I681");
        this.put("SESTO AL REGHENA","I686");
        this.put("SESTO CALENDE","I688");
        this.put("SESTO CAMPANO","I682");
        this.put("SESTO ED UNITI","I683");
        this.put("SESTO FIORENTINO","I684");
        this.put("SESTO SAN GIOVANNI","I690");
        this.put("SESTO .SEXTEN.","I687");
        this.put("SESTOLA","I689");
        this.put("SESTRI LEVANTE","I693");
        this.put("SESTRIERE","I692");
        this.put("SESTU","I695");
        this.put("SETTALA","I696");
        this.put("SETTEFRATI","I697");
        this.put("SETTIME","I698");
        this.put("SETTIMO MILANESE","I700");
        this.put("SETTIMO ROTTARO","I701");
        this.put("SETTIMO SAN PIETRO","I699");
        this.put("SETTIMO TORINESE","I703");
        this.put("SETTIMO VITTONE","I702");
        this.put("SETTINGIANO","I704");
        this.put("SETZU","I705");
        this.put("SEUI","I706");
        this.put("SEULO","I707");
        this.put("SEVESO","I709");
        this.put("SEZZADIO","I711");
        this.put("SEZZE","I712");
        this.put("SFRUZ","I714");
        this.put("SGONICO","I715");
        this.put("SGURGOLA","I716");
        this.put("SIAMAGGIORE","I717");
        this.put("SIAMANNA","I718");
        this.put("SIANO","I720");
        this.put("SIAPICCIA","I721");
        this.put("SICIGNANO DEGLI ALBURNI","M253");
        this.put("SICULIANA","I723");
        this.put("SIDDI","I724");
        this.put("SIDERNO","I725");
        this.put("SIENA","I726");
        this.put("SIGILLO","I727");
        this.put("SIGNA","I728");
        this.put("SILANDRO .SCHLANDERS.","I729");
        this.put("SILANUS","I730");
        this.put("SILEA","F116");
        this.put("SILIGO","I732");
        this.put("SILIQUA","I734");
        this.put("SILIUS","I735");
        this.put("SILLANO","I737");
        this.put("SILLANO GIUNCUGNANO","M347");
        this.put("SILLAVENGO","I736");
        this.put("SILVANO D'ORBA","I738");
        this.put("SILVANO PIETRA","I739");
        this.put("SILVI","I741");
        this.put("SIMALA","I742");
        this.put("SIMAXIS","I743");
        this.put("SIMBARIO","I744");
        this.put("SIMERI CRICHI","I745");
        this.put("SINAGRA","I747");
        this.put("SINALUNGA","A468");
        this.put("SINDIA","I748");
        this.put("SINI","I749");
        this.put("SINIO","I750");
        this.put("SINISCOLA","I751");
        this.put("SINNAI","I752");
        this.put("SINOPOLI","I753");
        this.put("SIRACUSA","I754");
        this.put("SIRIGNANO","I756");
        this.put("SIRIS","I757");
        this.put("SIRMIONE","I633");
        this.put("SIROLO","I758");
        this.put("SIRONE","I759");
        this.put("SIROR","I760");
        this.put("SIRTORI","I761");
        this.put("SISSA","I763");
        this.put("SISSA TRECASALI","M325");
        this.put("SIURGUS DONIGALA","I765");
        this.put("SIZIANO","E265");
        this.put("SIZZANO","I767");
        this.put("SLUDERNO .SCHLUDERNS.","I771");
        this.put("SMARANO","I772");
        this.put("SMERILLO","I774");
        this.put("SOAVE","I775");
        this.put("SOCCHIEVE","I777");
        this.put("SODDI'","I778");
        this.put("SOGLIANO AL RUBICONE","I779");
        this.put("SOGLIANO CAVOUR","I780");
        this.put("SOGLIO","I781");
        this.put("SOIANO DEL LAGO","I782");
        this.put("SOLAGNA","I783");
        this.put("SOLARINO","I785");
        this.put("SOLARO","I786");
        this.put("SOLAROLO","I787");
        this.put("SOLAROLO RAINERIO","I790");
        this.put("SOLARUSSA","I791");
        this.put("SOLBIATE","I792");
        this.put("SOLBIATE ARNO","I793");
        this.put("SOLBIATE CON CAGNO","M412");
        this.put("SOLBIATE OLONA","I794");
        this.put("SOLDANO","I796");
        this.put("SOLEMINIS","I797");
        this.put("SOLERO","I798");
        this.put("SOLESINO","I799");
        this.put("SOLETO","I800");
        this.put("SOLFERINO","I801");
        this.put("SOLIERA","I802");
        this.put("SOLIGNANO","I803");
        this.put("SOLOFRA","I805");
        this.put("SOLONGHELLO","I808");
        this.put("SOLOPACA","I809");
        this.put("SOLTO COLLINA","I812");
        this.put("SOLZA","I813");
        this.put("SOMAGLIA","I815");
        this.put("SOMANO","I817");
        this.put("SOMMA LOMBARDO","I819");
        this.put("SOMMA VESUVIANA","I820");
        this.put("SOMMACAMPAGNA","I821");
        this.put("SOMMARIVA DEL BOSCO","I822");
        this.put("SOMMARIVA PERNO","I823");
        this.put("SOMMATINO","I824");
        this.put("SOMMO","I825");
        this.put("SONA","I826");
        this.put("SONCINO","I827");
        this.put("SONDALO","I828");
        this.put("SONDRIO","I829");
        this.put("SONGAVAZZO","I830");
        this.put("SONICO","I831");
        this.put("SONNINO","I832");
        this.put("SOPRANA","I835");
        this.put("SORA","I838");
        this.put("SORAGA DI FASSA","I839");
        this.put("SORAGNA","I840");
        this.put("SORANO","I841");
        this.put("SORBO SAN BASILE","I844");
        this.put("SORBO SERPICO","I843");
        this.put("SORBOLO","I845");
        this.put("SORBOLO MEZZANI","M411");
        this.put("SORDEVOLO","I847");
        this.put("SORDIO","I848");
        this.put("SORESINA","I849");
        this.put("SORGA'","I850");
        this.put("SORGONO","I851");
        this.put("SORI","I852");
        this.put("SORIANELLO","I853");
        this.put("SORIANO CALABRO","I854");
        this.put("SORIANO NEL CIMINO","I855");
        this.put("SORICO","I856");
        this.put("SORISO","I857");
        this.put("SORISOLE","I858");
        this.put("SORMANO","I860");
        this.put("SORRADILE","I861");
        this.put("SORRENTO","I862");
        this.put("SORSO","I863");
        this.put("SORTINO","I864");
        this.put("SOSPIRO","I865");
        this.put("SOSPIROLO","I866");
        this.put("SOSSANO","I867");
        this.put("SOSTEGNO","I868");
        this.put("SOTTO IL MONTE GIOVANNI XXIII","I869");
        this.put("SOVER","I871");
        this.put("SOVERATO","I872");
        this.put("SOVERE","I873");
        this.put("SOVERIA MANNELLI","I874");
        this.put("SOVERIA SIMERI","I875");
        this.put("SOVERZENE","I876");
        this.put("SOVICILLE","I877");
        this.put("SOVICO","I878");
        this.put("SOVIZZO","I879");
        this.put("SOVRAMONTE","I673");
        this.put("SOZZAGO","I880");
        this.put("SPADAFORA","I881");
        this.put("SPADOLA","I884");
        this.put("SPARANISE","I885");
        this.put("SPARONE","I886");
        this.put("SPECCHIA","I887");
        this.put("SPELLO","I888");
        this.put("SPERA","I889");
        this.put("SPERLINGA","I891");
        this.put("SPERLONGA","I892");
        this.put("SPERONE","I893");
        this.put("SPESSA","I894");
        this.put("SPEZZANO ALBANESE","I895");
        this.put("SPEZZANO DELLA SILA","I896");
        this.put("SPEZZANO PICCOLO","I898");
        this.put("SPIAZZO","I899");
        this.put("SPIGNO MONFERRATO","I901");
        this.put("SPIGNO SATURNIA","I902");
        this.put("SPILAMBERTO","I903");
        this.put("SPILIMBERGO","I904");
        this.put("SPILINGA","I905");
        this.put("SPINADESCO","I906");
        this.put("SPINAZZOLA","I907");
        this.put("SPINEA","I908");
        this.put("SPINEDA","I909");
        this.put("SPINETE","I910");
        this.put("SPINETO SCRIVIA","I911");
        this.put("SPINETOLI","I912");
        this.put("SPINO D'ADDA","I914");
        this.put("SPINONE AL LAGO","I916");
        this.put("SPINOSO","I917");
        this.put("SPIRANO","I919");
        this.put("SPOLETO","I921");
        this.put("SPOLTORE","I922");
        this.put("SPONGANO","I923");
        this.put("SPORMAGGIORE","I924");
        this.put("SPORMINORE","I925");
        this.put("SPOTORNO","I926");
        this.put("SPRESIANO","I927");
        this.put("SPRIANA","I928");
        this.put("SQUILLACE","I929");
        this.put("SQUINZANO","I930");
        this.put("STAFFOLO","I932");
        this.put("STAGNO LOMBARDO","I935");
        this.put("STAITI","I936");
        this.put("STALETTI'","I937");
        this.put("STANGHELLA","I938");
        this.put("STARANZANO","I939");
        this.put("STATTE","M298");
        this.put("STAZZANO","I941");
        this.put("STAZZEMA","I942");
        this.put("STAZZONA","I943");
        this.put("STEFANACONI","I945");
        this.put("STELLA","I946");
        this.put("STELLA CILENTO","G887");
        this.put("STELLANELLO","I947");
        this.put("STELVIO .STILFS.","I948");
        this.put("STENICO","I949");
        this.put("STERNATIA","I950");
        this.put("STEZZANO","I951");
        this.put("STIA","I952");
        this.put("STIENTA","I953");
        this.put("STIGLIANO","I954");
        this.put("STIGNANO","I955");
        this.put("STILO","I956");
        this.put("STIMIGLIANO","I959");
        this.put("STINTINO","M290");
        this.put("STIO","I960");
        this.put("STORNARA","I962");
        this.put("STORNARELLA","I963");
        this.put("STORO","I964");
        this.put("STRA","I965");
        this.put("STRADELLA","I968");
        this.put("STRAMBINELLO","I969");
        this.put("STRAMBINO","I970");
        this.put("STRANGOLAGALLI","I973");
        this.put("STREGNA","I974");
        this.put("STREMBO","I975");
        this.put("STRESA","I976");
        this.put("STREVI","I977");
        this.put("STRIANO","I978");
        this.put("STRIGNO","I979");
        this.put("STRONA","I980");
        this.put("STRONCONE","I981");
        this.put("STRONGOLI","I982");
        this.put("STROPPIANA","I984");
        this.put("STROPPO","I985");
        this.put("STROZZA","I986");
        this.put("STURNO","I990");
        this.put("SUARDI","B014");
        this.put("SUBBIANO","I991");
        this.put("SUBIACO","I992");
        this.put("SUCCIVO","I993");
        this.put("SUEGLIO","I994");
        this.put("SUELLI","I995");
        this.put("SUELLO","I996");
        this.put("SUISIO","I997");
        this.put("SULBIATE","I998");
        this.put("SULMONA","I804");
        this.put("SULZANO","L002");
        this.put("SUMIRAGO","L003");
        this.put("SUMMONTE","L004");
        this.put("SUNI","L006");
        this.put("SUNO","L007");
        this.put("SUPERSANO","L008");
        this.put("SUPINO","L009");
        this.put("SURANO","L010");
        this.put("SURBO","L011");
        this.put("SUSA","L013");
        this.put("SUSEGANA","L014");
        this.put("SUSTINENTE","L015");
        this.put("SUTERA","L016");
        this.put("SUTRI","L017");
        this.put("SUTRIO","L018");
        this.put("SUVERETO","L019");
        this.put("SUZZARA","L020");
        this.put("TACENO","L022");
        this.put("TADASUNI","L023");
        this.put("TAGGIA","L024");
        this.put("TAGLIACOZZO","L025");
        this.put("TAGLIO DI PO","L026");
        this.put("TAGLIOLO MONFERRATO","L027");
        this.put("TAIBON AGORDINO","L030");
        this.put("TAINO","L032");
        this.put("TAIO","L033");
        this.put("TAIPANA","G736");
        this.put("TALAMELLO","L034");
        this.put("TALAMONA","L035");
        this.put("TALANA","L036");
        this.put("TALEGGIO","L037");
        this.put("TALLA","L038");
        this.put("TALMASSONS","L039");
        this.put("TAMBRE","L040");
        this.put("TAORMINA","L042");
        this.put("TAPOGLIANO","L044");
        this.put("TARANO","L046");
        this.put("TARANTA PELIGNA","L047");
        this.put("TARANTASCA","L048");
        this.put("TARANTO","L049");
        this.put("TARCENTO","L050");
        this.put("TARQUINIA","D024");
        this.put("TARSIA","L055");
        this.put("TARTANO","L056");
        this.put("TARVISIO","L057");
        this.put("TARZO","L058");
        this.put("TASSAROLO","L059");
        this.put("TASSULLO","L060");
        this.put("TAURANO","L061");
        this.put("TAURASI","L062");
        this.put("TAURIANOVA","L063");
        this.put("TAURISANO","L064");
        this.put("TAVAGNACCO","L065");
        this.put("TAVAGNASCO","L066");
        this.put("TAVARNELLE VAL DI PESA","L067");
        this.put("TAVAZZANO CON VILLAVESCO","F260");
        this.put("TAVENNA","L069");
        this.put("TAVERNA","L070");
        this.put("TAVERNERIO","L071");
        this.put("TAVERNOLA BERGAMASCA","L073");
        this.put("TAVERNOLE SUL MELLA","C698");
        this.put("TAVIANO","L074");
        this.put("TAVIGLIANO","L075");
        this.put("TAVOLETO","L078");
        this.put("TAVULLIA","L081");
        this.put("TEANA","L082");
        this.put("TEANO","L083");
        this.put("TEGGIANO","D292");
        this.put("TEGLIO","L084");
        this.put("TEGLIO VENETO","L085");
        this.put("TELESE TERME","L086");
        this.put("TELGATE","L087");
        this.put("TELTI","L088");
        this.put("TELVE","L089");
        this.put("TELVE DI SOPRA","L090");
        this.put("TEMPIO PAUSANIA","L093");
        this.put("TEMU'","L094");
        this.put("TENNA","L096");
        this.put("TENNO","L097");
        this.put("TEOLO","L100");
        this.put("TEOR","L101");
        this.put("TEORA","L102");
        this.put("TERAMO","L103");
        this.put("TERDOBBIATE","L104");
        this.put("TERELLE","L105");
        this.put("TERENTO .TERENTEN.","L106");
        this.put("TERENZO","E548");
        this.put("TERGU","M282");
        this.put("TERLAGO","L107");
        this.put("TERLANO .TERLAN.","L108");
        this.put("TERLIZZI","L109");
        this.put("TERME VIGLIATORE","M210");
        this.put("TERMENO SULLA STRADA DEL VINO .TRAMIN AN DER.","L111");
        this.put("TERMINI IMERESE","L112");
        this.put("TERMOLI","L113");
        this.put("TERNATE","L115");
        this.put("TERNENGO","L116");
        this.put("TERNI","L117");
        this.put("TERNO D'ISOLA","L118");
        this.put("TERRACINA","L120");
        this.put("TERRAGNOLO","L121");
        this.put("TERRALBA","L122");
        this.put("TERRANOVA DA SIBARI","L124");
        this.put("TERRANOVA DEI PASSERINI","L125");
        this.put("TERRANOVA DI POLLINO","L126");
        this.put("TERRANOVA SAPPO MINULIO","L127");
        this.put("TERRANUOVA BRACCIOLINI","L123");
        this.put("TERRASINI","L131");
        this.put("TERRASSA PADOVANA","L132");
        this.put("TERRAVECCHIA","L134");
        this.put("TERRAZZO","L136");
        this.put("TERRE D'ADIGE","M407");
        this.put("TERRE DEL RENO","M381");
        this.put("TERRE ROVERESCHE","M379");
        this.put("TERRES","L137");
        this.put("TERRICCIOLA","L138");
        this.put("TERRUGGIA","L139");
        this.put("TERTENIA","L140");
        this.put("TERZIGNO","L142");
        this.put("TERZO","L143");
        this.put("TERZO DI AQUILEIA","L144");
        this.put("TERZOLAS","L145");
        this.put("TERZORIO","L146");
        this.put("TESERO","L147");
        this.put("TESIMO .TISENS.","L149");
        this.put("TESSENNANO","L150");
        this.put("TESTICO","L152");
        this.put("TETI","L153");
        this.put("TEULADA","L154");
        this.put("TEVEROLA","L155");
        this.put("TEZZE SUL BRENTA","L156");
        this.put("THIENE","L157");
        this.put("THIESI","L158");
        this.put("TIANA","L160");
        this.put("TIARNO DI SOPRA","L162");
        this.put("TIARNO DI SOTTO","L163");
        this.put("TICENGO","L164");
        this.put("TICINETO","L165");
        this.put("TIGGIANO","L166");
        this.put("TIGLIETO","L167");
        this.put("TIGLIOLE","L168");
        this.put("TIGNALE","L169");
        this.put("TINNURA","L172");
        this.put("TIONE DEGLI ABRUZZI","L173");
        this.put("TIONE DI TRENTO","L174");
        this.put("TIRANO","L175");
        this.put("TIRES .TIERS.","L176");
        this.put("TIRIOLO","L177");
        this.put("TIROLO .TIROL.","L178");
        this.put("TISSI","L180");
        this.put("TITO","L181");
        this.put("TIVOLI","L182");
        this.put("TIZZANO VAL PARMA","L183");
        this.put("TOANO","L184");
        this.put("TOCCO CAUDIO","L185");
        this.put("TOCCO DA CASAURIA","L186");
        this.put("TOCENO","L187");
        this.put("TODI","L188");
        this.put("TOFFIA","L189");
        this.put("TOIRANO","L190");
        this.put("TOLENTINO","L191");
        this.put("TOLFA","L192");
        this.put("TOLLEGNO","L193");
        this.put("TOLLO","L194");
        this.put("TOLMEZZO","L195");
        this.put("TOLVE","L197");
        this.put("TOMBOLO","L199");
        this.put("TON","L200");
        this.put("TONADICO","L201");
        this.put("TONARA","L202");
        this.put("TONCO","L203");
        this.put("TONENGO","L204");
        this.put("TONEZZA DEL CIMONE","D717");
        this.put("TORA E PICCILLI","L205");
        this.put("TORANO CASTELLO","L206");
        this.put("TORANO NUOVO","L207");
        this.put("TORBOLE CASAGLIA","L210");
        this.put("TORCEGNO","L211");
        this.put("TORCHIARA","L212");
        this.put("TORCHIAROLO","L213");
        this.put("TORELLA DEI LOMBARDI","L214");
        this.put("TORELLA DEL SANNIO","L215");
        this.put("TORGIANO","L216");
        this.put("TORGNON","L217");
        this.put("TORINO","L219");
        this.put("TORINO DI SANGRO","L218");
        this.put("TORITTO","L220");
        this.put("TORLINO VIMERCATI","L221");
        this.put("TORNACO","L223");
        this.put("TORNARECCIO","L224");
        this.put("TORNATA","L225");
        this.put("TORNIMPARTE","L227");
        this.put("TORNO","L228");
        this.put("TORNOLO","L229");
        this.put("TORO","L230");
        this.put("TORPE'","L231");
        this.put("TORRACA","L233");
        this.put("TORRALBA","L235");
        this.put("TORRAZZA COSTE","L237");
        this.put("TORRAZZA PIEMONTE","L238");
        this.put("TORRAZZO","L239");
        this.put("TORRE ANNUNZIATA","L245");
        this.put("TORRE BERETTI E CASTELLARO","L250");
        this.put("TORRE BOLDONE","L251");
        this.put("TORRE BORMIDA","L252");
        this.put("TORRE CAJETANI","L243");
        this.put("TORRE CANAVESE","L247");
        this.put("TORRE D'ARESE","L256");
        this.put("TORRE DE' BUSI","L257");
        this.put("TORRE DE' NEGRI","L262");
        this.put("TORRE DE' PASSERI","L263");
        this.put("TORRE DE' PICENARDI","L258");
        this.put("TORRE DE' ROVERI","L265");
        this.put("TORRE DEL GRECO","L259");
        this.put("TORRE DI MOSTO","L267");
        this.put("TORRE DI RUGGIERO","L240");
        this.put("TORRE DI SANTA MARIA","L244");
        this.put("TORRE D'ISOLA","L269");
        this.put("TORRE LE NOCELLE","L272");
        this.put("TORRE MONDOVI'","L241");
        this.put("TORRE ORSAIA","L274");
        this.put("TORRE PALLAVICINA","L276");
        this.put("TORRE PELLICE","L277");
        this.put("TORRE SAN GIORGIO","L278");
        this.put("TORRE SAN PATRIZIO","L279");
        this.put("TORRE SANTA SUSANNA","L280");
        this.put("TORREANO","L246");
        this.put("TORREBELVICINO","L248");
        this.put("TORREBRUNA","L253");
        this.put("TORRECUSO","L254");
        this.put("TORREGLIA","L270");
        this.put("TORREGROTTA","L271");
        this.put("TORREMAGGIORE","L273");
        this.put("TORRENOVA","M286");
        this.put("TORRESINA","L281");
        this.put("TORRETTA","L282");
        this.put("TORREVECCHIA PIA","L285");
        this.put("TORREVECCHIA TEATINA","L284");
        this.put("TORRI DEL BENACO","L287");
        this.put("TORRI DI QUARTESOLO","L297");
        this.put("TORRI IN SABINA","L286");
        this.put("TORRIANA","I550");
        this.put("TORRICE","L290");
        this.put("TORRICELLA","L294");
        this.put("TORRICELLA DEL PIZZO","L296");
        this.put("TORRICELLA IN SABINA","L293");
        this.put("TORRICELLA PELIGNA","L291");
        this.put("TORRICELLA SICURA","L295");
        this.put("TORRICELLA VERZATE","L292");
        this.put("TORRIGLIA","L298");
        this.put("TORRILE","L299");
        this.put("TORRIONI","L301");
        this.put("TORRITA DI SIENA","L303");
        this.put("TORRITA TIBERINA","L302");
        this.put("TORTOLI'","A355");
        this.put("TORTONA","L304");
        this.put("TORTORA","L305");
        this.put("TORTORELLA","L306");
        this.put("TORTORETO","L307");
        this.put("TORTORICI","L308");
        this.put("TORVISCOSA","L309");
        this.put("TOSCOLANO MADERNO","L312");
        this.put("TOSSICIA","L314");
        this.put("TOVO DI SANT'AGATA","L316");
        this.put("TOVO SAN GIACOMO","L315");
        this.put("TRABIA","L317");
        this.put("TRADATE","L319");
        this.put("TRAMATZA","L321");
        this.put("TRAMBILENO","L322");
        this.put("TRAMONTI","L323");
        this.put("TRAMONTI DI SOPRA","L324");
        this.put("TRAMONTI DI SOTTO","L325");
        this.put("TRAMUTOLA","L326");
        this.put("TRANA","L327");
        this.put("TRANI","L328");
        this.put("TRANSACQUA","L329");
        this.put("TRAONA","L330");
        this.put("TRAPANI","L331");
        this.put("TRAPPETO","L332");
        this.put("TRAREGO VIGGIONA","L333");
        this.put("TRASACCO","L334");
        this.put("TRASAGHIS","L335");
        this.put("TRASQUERA","L336");
        this.put("TRATALIAS","L337");
        this.put("TRAUSELLA","L338");
        this.put("TRAVACO' SICCOMARIO","I236");
        this.put("TRAVAGLIATO","L339");
        this.put("TRAVEDONA-MONATE","L342");
        this.put("TRAVERSELLA","L345");
        this.put("TRAVERSETOLO","L346");
        this.put("TRAVES","L340");
        this.put("TRAVESIO","L347");
        this.put("TRAVO","L348");
        this.put("TRE VILLE","M361");
        this.put("TREBASELEGHE","L349");
        this.put("TREBISACCE","L353");
        this.put("TRECASALI","L354");
        this.put("TRECASE","M280");
        this.put("TRECASTAGNI","L355");
        this.put("TRECASTELLI","M318");
        this.put("TRECATE","L356");
        this.put("TRECCHINA","L357");
        this.put("TRECENTA","L359");
        this.put("TREDOZIO","L361");
        this.put("TREGLIO","L363");
        this.put("TREGNAGO","L364");
        this.put("TREIA","L366");
        this.put("TREISO","L367");
        this.put("TREMENICO","L368");
        this.put("TREMESTIERI ETNEO","L369");
        this.put("TREMEZZINA","M341");
        this.put("TREMEZZO","L371");
        this.put("TREMOSINE SUL GARDA","L372");
        this.put("TRENTA","L375");
        this.put("TRENTINARA","L377");
        this.put("TRENTO","L378");
        this.put("TRENTOLA DUCENTA","L379");
        this.put("TRENZANO","L380");
        this.put("TREPPO CARNICO","L381");
        this.put("TREPPO GRANDE","L382");
        this.put("TREPPO LIGOSULLO","M399");
        this.put("TREPUZZI","L383");
        this.put("TREQUANDA","L384");
        this.put("TRES","L385");
        this.put("TRESANA","L386");
        this.put("TRESCORE BALNEARIO","L388");
        this.put("TRESCORE CREMASCO","L389");
        this.put("TRESIGALLO","L390");
        this.put("TRESIGNANA","M409");
        this.put("TRESIVIO","L392");
        this.put("TRESNURAGHES","L393");
        this.put("TREVENZUOLO","L396");
        this.put("TREVI","L397");
        this.put("TREVI NEL LAZIO","L398");
        this.put("TREVICO","L399");
        this.put("TREVIGLIO","L400");
        this.put("TREVIGNANO","L402");
        this.put("TREVIGNANO ROMANO","L401");
        this.put("TREVILLE","L403");
        this.put("TREVIOLO","L404");
        this.put("TREVISO","L407");
        this.put("TREVISO BRESCIANO","L406");
        this.put("TREZZANO ROSA","L408");
        this.put("TREZZANO SUL NAVIGLIO","L409");
        this.put("TREZZO SULL'ADDA","L411");
        this.put("TREZZO TINELLA","L410");
        this.put("TREZZONE","L413");
        this.put("TRIBANO","L414");
        this.put("TRIBIANO","L415");
        this.put("TRIBOGNA","L416");
        this.put("TRICARICO","L418");
        this.put("TRICASE","L419");
        this.put("TRICERRO","L420");
        this.put("TRICESIMO","L421");
        this.put("TRICHIANA","L422");
        this.put("TRIEI","L423");
        this.put("TRIESTE","L424");
        this.put("TRIGGIANO","L425");
        this.put("TRIGOLO","L426");
        this.put("TRINITA'","L427");
        this.put("TRINITA' D'AGULTU E VIGNOLA","L428");
        this.put("TRINITAPOLI","B915");
        this.put("TRINO","L429");
        this.put("TRIORA","L430");
        this.put("TRIPI","L431");
        this.put("TRISOBBIO","L432");
        this.put("TRISSINO","L433");
        this.put("TRIUGGIO","L434");
        this.put("TRIVENTO","L435");
        this.put("TRIVERO","L436");
        this.put("TRIVIGLIANO","L437");
        this.put("TRIVIGNANO UDINESE","L438");
        this.put("TRIVIGNO","L439");
        this.put("TRIVOLZIO","L440");
        this.put("TRODENA NEL PARCO NATURALE .TRUDEN IM NATURPA","L444");
        this.put("TROFARELLO","L445");
        this.put("TROIA","L447");
        this.put("TROINA","L448");
        this.put("TROMELLO","L449");
        this.put("TRONTANO","L450");
        this.put("TRONZANO LAGO MAGGIORE","A705");
        this.put("TRONZANO VERCELLESE","L451");
        this.put("TROPEA","L452");
        this.put("TROVO","L453");
        this.put("TRUCCAZZANO","L454");
        this.put("TUBRE .TAUFERS IM MUENSTERTAL.","L455");
        this.put("TUENNO","L457");
        this.put("TUFARA","L458");
        this.put("TUFILLO","L459");
        this.put("TUFINO","L460");
        this.put("TUFO","L461");
        this.put("TUGLIE","L462");
        this.put("TUILI","L463");
        this.put("TULA","L464");
        this.put("TUORO SUL TRASIMENO","L466");
        this.put("TURANIA","G507");
        this.put("TURANO LODIGIANO","L469");
        this.put("TURATE","L470");
        this.put("TURBIGO","L471");
        this.put("TURI","L472");
        this.put("TURRI","L473");
        this.put("TURRIACO","L474");
        this.put("TURRIVALIGNANI","L475");
        this.put("TURSI","L477");
        this.put("TUSA","L478");
        this.put("TUSCANIA","L310");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
