package libreria_sibilia.codicefiscale.document ;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_OPQ extends HashMap<String, String> {

    public CitiesCodes_OPQ(){
        this.put("OCCHIEPPO INFERIORE","F992");
        this.put("OCCHIEPPO SUPERIORE","F993");
        this.put("OCCHIOBELLO","F994");
        this.put("OCCIMIANO","F995");
        this.put("OCRE","F996");
        this.put("ODALENGO GRANDE","F997");
        this.put("ODALENGO PICCOLO","F998");
        this.put("ODERZO","F999");
        this.put("ODOLO","G001");
        this.put("OFENA","G002");
        this.put("OFFAGNA","G003");
        this.put("OFFANENGO","G004");
        this.put("OFFIDA","G005");
        this.put("OFFLAGA","G006");
        this.put("OGGEBBIO","G007");
        this.put("OGGIONA CON SANTO STEFANO","G008");
        this.put("OGGIONO","G009");
        this.put("OGLIANICO","G010");
        this.put("OGLIASTRO CILENTO","G011");
        this.put("OLBIA","G015");
        this.put("OLCENENGO","G016");
        this.put("OLDENICO","G018");
        this.put("OLEGGIO","G019");
        this.put("OLEGGIO CASTELLO","G020");
        this.put("OLEVANO DI LOMELLINA","G021");
        this.put("OLEVANO ROMANO","G022");
        this.put("OLEVANO SUL TUSCIANO","G023");
        this.put("OLGIATE COMASCO","G025");
        this.put("OLGIATE MOLGORA","G026");
        this.put("OLGIATE OLONA","G028");
        this.put("OLGINATE","G030");
        this.put("OLIENA","G031");
        this.put("OLIVA GESSI","G032");
        this.put("OLIVADI","G034");
        this.put("OLIVERI","G036");
        this.put("OLIVETO CITRA","G039");
        this.put("OLIVETO LARIO","G040");
        this.put("OLIVETO LUCANO","G037");
        this.put("OLIVETTA SAN MICHELE","G041");
        this.put("OLIVOLA","G042");
        this.put("OLLASTRA","G043");
        this.put("OLLOLAI","G044");
        this.put("OLLOMONT","G045");
        this.put("OLMEDO","G046");
        this.put("OLMENETA","G047");
        this.put("OLMO AL BREMBO","G049");
        this.put("OLMO GENTILE","G048");
        this.put("OLTRE IL COLLE","G050");
        this.put("OLTRESSENDA ALTA","G054");
        this.put("OLTRONA DI SAN MAMETTE","G056");
        this.put("OLZAI","G058");
        this.put("OME","G061");
        this.put("OMEGNA","G062");
        this.put("OMIGNANO","G063");
        this.put("ONANI'","G064");
        this.put("ONANO","G065");
        this.put("ONCINO","G066");
        this.put("ONETA","G068");
        this.put("ONIFAI","G070");
        this.put("ONIFERI","G071");
        this.put("ONO SAN PIETRO","G074");
        this.put("ONORE","G075");
        this.put("ONZO","G076");
        this.put("OPERA","G078");
        this.put("OPI","G079");
        this.put("OPPEANO","G080");
        this.put("OPPIDO LUCANO","G081");
        this.put("OPPIDO MAMERTINA","G082");
        this.put("ORA .AUER.","G083");
        this.put("ORANI","G084");
        this.put("ORATINO","G086");
        this.put("ORBASSANO","G087");
        this.put("ORBETELLO","G088");
        this.put("ORCIANO DI PESARO","G089");
        this.put("ORCIANO PISANO","G090");
        this.put("ORCO FEGLINO","D522");
        this.put("ORDONA","M266");
        this.put("ORERO","G093");
        this.put("ORGIANO","G095");
        this.put("ORGOSOLO","G097");
        this.put("ORIA","G098");
        this.put("ORICOLA","G102");
        this.put("ORIGGIO","G103");
        this.put("ORINO","G105");
        this.put("ORIO AL SERIO","G108");
        this.put("ORIO CANAVESE","G109");
        this.put("ORIO LITTA","G107");
        this.put("ORIOLO","G110");
        this.put("ORIOLO ROMANO","G111");
        this.put("ORISTANO","G113");
        this.put("ORMEA","G114");
        this.put("ORMELLE","G115");
        this.put("ORNAGO","G116");
        this.put("ORNAVASSO","G117");
        this.put("ORNICA","G118");
        this.put("OROSEI","G119");
        this.put("OROTELLI","G120");
        this.put("ORRIA","G121");
        this.put("ORROLI","G122");
        this.put("ORSAGO","G123");
        this.put("ORSARA BORMIDA","G124");
        this.put("ORSARA DI PUGLIA","G125");
        this.put("ORSENIGO","G126");
        this.put("ORSOGNA","G128");
        this.put("ORSOMARSO","G129");
        this.put("ORTA DI ATELLA","G130");
        this.put("ORTA NOVA","G131");
        this.put("ORTA SAN GIULIO","G134");
        this.put("ORTACESUS","G133");
        this.put("ORTE","G135");
        this.put("ORTELLE","G136");
        this.put("ORTEZZANO","G137");
        this.put("ORTIGNANO RAGGIOLO","G139");
        this.put("ORTISEI .ST ULRICH.","G140");
        this.put("ORTONA","G141");
        this.put("ORTONA DEI MARSI","G142");
        this.put("ORTOVERO","G144");
        this.put("ORTUCCHIO","G145");
        this.put("ORTUERI","G146");
        this.put("ORUNE","G147");
        this.put("ORVIETO","G148");
        this.put("ORVINIO","B595");
        this.put("ORZINUOVI","G149");
        this.put("ORZIVECCHI","G150");
        this.put("OSASCO","G151");
        this.put("OSASIO","G152");
        this.put("OSCHIRI","G153");
        this.put("OSIDDA","G154");
        this.put("OSIGLIA","G155");
        this.put("OSILO","G156");
        this.put("OSIMO","G157");
        this.put("OSINI","G158");
        this.put("OSIO SOPRA","G159");
        this.put("OSIO SOTTO","G160");
        this.put("OSMATE","E529");
        this.put("OSNAGO","G161");
        this.put("OSOPPO","G163");
        this.put("OSPEDALETTI","G164");
        this.put("OSPEDALETTO","G168");
        this.put("OSPEDALETTO D'ALPINOLO","G165");
        this.put("OSPEDALETTO EUGANEO","G167");
        this.put("OSPEDALETTO LODIGIANO","G166");
        this.put("OSPITALE DI CADORE","G169");
        this.put("OSPITALETTO","G170");
        this.put("OSSAGO LODIGIANO","G171");
        this.put("OSSANA","G173");
        this.put("OSSI","G178");
        this.put("OSSIMO","G179");
        this.put("OSSONA","G181");
        this.put("OSSUCCIO","G182");
        this.put("OSTANA","G183");
        this.put("OSTELLATO","G184");
        this.put("OSTIANO","G185");
        this.put("OSTIGLIA","G186");
        this.put("OSTRA","F401");
        this.put("OSTRA VETERE","F581");
        this.put("OSTUNI","G187");
        this.put("OTRANTO","G188");
        this.put("OTRICOLI","G189");
        this.put("OTTANA","G191");
        this.put("OTTATI","G192");
        this.put("OTTAVIANO","G190");
        this.put("OTTIGLIO","G193");
        this.put("OTTOBIANO","G194");
        this.put("OTTONE","G195");
        this.put("OULX","G196");
        this.put("OVADA","G197");
        this.put("OVARO","G198");
        this.put("OVIGLIO","G199");
        this.put("OVINDOLI","G200");
        this.put("OVODDA","G201");
        this.put("OYACE","G012");
        this.put("OZEGNA","G202");
        this.put("OZIERI","G203");
        this.put("OZZANO DELL'EMILIA","G205");
        this.put("OZZANO MONFERRATO","G204");
        this.put("OZZERO","G206");
        this.put("PABILLONIS","G207");
        this.put("PACE DEL MELA","G209");
        this.put("PACECO","G208");
        this.put("PACENTRO","G210");
        this.put("PACHINO","G211");
        this.put("PACIANO","G212");
        this.put("PADENGHE SUL GARDA","G213");
        this.put("PADERGNONE","G214");
        this.put("PADERNA","G215");
        this.put("PADERNO D'ADDA","G218");
        this.put("PADERNO DEL GRAPPA","G221");
        this.put("PADERNO DUGNANO","G220");
        this.put("PADERNO FRANCIACORTA","G217");
        this.put("PADERNO PONCHIELLI","G222");
        this.put("PADOVA","G224");
        this.put("PADRIA","G225");
        this.put("PADRU","M301");
        this.put("PADULA","G226");
        this.put("PADULI","G227");
        this.put("PAESANA","G228");
        this.put("PAESE","G229");
        this.put("PAGANI","G230");
        this.put("PAGANICO SABINO","G232");
        this.put("PAGAZZANO","G233");
        this.put("PAGLIARA","G234");
        this.put("PAGLIETA","G237");
        this.put("PAGNACCO","G238");
        this.put("PAGNO","G240");
        this.put("PAGNONA","G241");
        this.put("PAGO DEL VALLO DI LAURO","G242");
        this.put("PAGO VEIANO","G243");
        this.put("PAISCO LOVENO","G247");
        this.put("PAITONE","G248");
        this.put("PALADINA","G249");
        this.put("PALAGANO","G250");
        this.put("PALAGIANELLO","G251");
        this.put("PALAGIANO","G252");
        this.put("PALAGONIA","G253");
        this.put("PALAIA","G254");
        this.put("PALANZANO","G255");
        this.put("PALATA","G257");
        this.put("PALAU","G258");
        this.put("PALAZZAGO","G259");
        this.put("PALAZZO ADRIANO","G263");
        this.put("PALAZZO CANAVESE","G262");
        this.put("PALAZZO PIGNANO","G260");
        this.put("PALAZZO SAN GERVASIO","G261");
        this.put("PALAZZOLO ACREIDE","G267");
        this.put("PALAZZOLO DELLO STELLA","G268");
        this.put("PALAZZOLO SULL'OGLIO","G264");
        this.put("PALAZZOLO VERCELLESE","G266");
        this.put("PALAZZUOLO SUL SENIO","G270");
        this.put("PALENA","G271");
        this.put("PALERMITI","G272");
        this.put("PALERMO","G273");
        this.put("PALESTRINA","G274");
        this.put("PALESTRO","G275");
        this.put("PALIANO","G276");
        this.put("PALIZZI","G277");
        this.put("PALLAGORIO","G278");
        this.put("PALLANZENO","G280");
        this.put("PALLARE","G281");
        this.put("PALMA CAMPANIA","G283");
        this.put("PALMA DI MONTECHIARO","G282");
        this.put("PALMANOVA","G284");
        this.put("PALMARIGGI","G285");
        this.put("PALMAS ARBOREA","G286");
        this.put("PALMI","G288");
        this.put("PALMIANO","G289");
        this.put("PALMOLI","G290");
        this.put("PALO DEL COLLE","G291");
        this.put("PALOMBARA SABINA","G293");
        this.put("PALOMBARO","G294");
        this.put("PALOMONTE","G292");
        this.put("PALOSCO","G295");
        this.put("PALU'","G297");
        this.put("PALU' DEL FERSINA","G296");
        this.put("PALUDI","G298");
        this.put("PALUZZA","G300");
        this.put("PAMPARATO","G302");
        this.put("PANCALIERI","G303");
        this.put("PANCARANA","G304");
        this.put("PANCHIA'","G305");
        this.put("PANDINO","G306");
        this.put("PANETTIERI","G307");
        this.put("PANICALE","G308");
        this.put("PANNARANO","G311");
        this.put("PANNI","G312");
        this.put("PANTELLERIA","G315");
        this.put("PANTIGLIATE","G316");
        this.put("PAOLA","G317");
        this.put("PAOLISI","G318");
        this.put("PAPASIDERO","G320");
        this.put("PAPOZZE","G323");
        this.put("PARABIAGO","G324");
        this.put("PARABITA","G325");
        this.put("PARATICO","G327");
        this.put("PARCINES .PARTSCHINS.","G328");
        this.put("PARE'","G329");
        this.put("PARELLA","G330");
        this.put("PARENTI","G331");
        this.put("PARETE","G333");
        this.put("PARETO","G334");
        this.put("PARGHELIA","G335");
        this.put("PARLASCO","G336");
        this.put("PARMA","G337");
        this.put("PARODI LIGURE","G338");
        this.put("PAROLDO","G339");
        this.put("PAROLISE","G340");
        this.put("PARONA","G342");
        this.put("PARRANO","G344");
        this.put("PARRE","G346");
        this.put("PARTANNA","G347");
        this.put("PARTINICO","G348");
        this.put("PARUZZARO","G349");
        this.put("PARZANICA","G350");
        this.put("PASIAN DI PRATO","G352");
        this.put("PASIANO DI PORDENONE","G353");
        this.put("PASPARDO","G354");
        this.put("PASSERANO MARMORITO","G358");
        this.put("PASSIGNANO SUL TRASIMENO","G359");
        this.put("PASSIRANO","G361");
        this.put("PASTENA","G362");
        this.put("PASTORANO","G364");
        this.put("PASTRENGO","G365");
        this.put("PASTURANA","G367");
        this.put("PASTURO","G368");
        this.put("PATERNO'","G371");
        this.put("PATERNO","M269");
        this.put("PATERNO CALABRO","G372");
        this.put("PATERNOPOLI","G370");
        this.put("PATRICA","G374");
        this.put("PATTADA","G376");
        this.put("PATTI","G377");
        this.put("PATU'","G378");
        this.put("PAU","G379");
        this.put("PAULARO","G381");
        this.put("PAULI ARBAREI","G382");
        this.put("PAULILATINO","G384");
        this.put("PAULLO","G385");
        this.put("PAUPISI","G386");
        this.put("PAVAROLO","G387");
        this.put("PAVIA","G388");
        this.put("PAVIA DI UDINE","G389");
        this.put("PAVONE CANAVESE","G392");
        this.put("PAVONE DEL MELLA","G391");
        this.put("PAVULLO NEL FRIGNANO","G393");
        this.put("PAZZANO","G394");
        this.put("PECCIOLI","G395");
        this.put("PECCO","G396");
        this.put("PECETTO DI VALENZA","G397");
        this.put("PECETTO TORINESE","G398");
        this.put("PECORARA","G399");
        this.put("PEDACE","G400");
        this.put("PEDARA","G402");
        this.put("PEDASO","G403");
        this.put("PEDAVENA","G404");
        this.put("PEDEMONTE","G406");
        this.put("PEDEROBBA","G408");
        this.put("PEDESINA","G410");
        this.put("PEDIVIGLIANO","G411");
        this.put("PEDRENGO","G412");
        this.put("PEGLIO","G415");
        this.put("PEGLIO","G416");
        this.put("PEGOGNAGA","G417");
        this.put("PEIA","G418");
        this.put("PEIO","G419");
        this.put("PELAGO","G420");
        this.put("PELLA","G421");
        this.put("PELLEGRINO PARMENSE","G424");
        this.put("PELLEZZANO","G426");
        this.put("PELLIO INTELVI","G427");
        this.put("PELLIZZANO","G428");
        this.put("PELUGO","G429");
        this.put("PENANGO","G430");
        this.put("PENNA IN TEVERINA","G432");
        this.put("PENNA SAN GIOVANNI","G436");
        this.put("PENNA SANT'ANDREA","G437");
        this.put("PENNABILLI","G433");
        this.put("PENNADOMO","G434");
        this.put("PENNAPIEDIMONTE","G435");
        this.put("PENNE","G438");
        this.put("PENTONE","G439");
        this.put("PERANO","G441");
        this.put("PERAROLO DI CADORE","G442");
        this.put("PERCA .PERCHA.","G443");
        this.put("PERCILE","G444");
        this.put("PERDASDEFOGU","G445");
        this.put("PERDAXIUS","G446");
        this.put("PERDIFUMO","G447");
        this.put("PEREGO","G448");
        this.put("PERETO","G449");
        this.put("PERFUGAS","G450");
        this.put("PERGINE VALDARNO","G451");
        this.put("PERGINE VALSUGANA","G452");
        this.put("PERGOLA","G453");
        this.put("PERINALDO","G454");
        this.put("PERITO","G455");
        this.put("PERLEDO","G456");
        this.put("PERLETTO","G457");
        this.put("PERLO","G458");
        this.put("PERLOZ","G459");
        this.put("PERNUMIA","G461");
        this.put("PERO","C013");
        this.put("PEROSA ARGENTINA","G463");
        this.put("PEROSA CANAVESE","G462");
        this.put("PERRERO","G465");
        this.put("PERSICO DOSIMO","G469");
        this.put("PERTENGO","G471");
        this.put("PERTICA ALTA","G474");
        this.put("PERTICA BASSA","G475");
        this.put("PERTOSA","G476");
        this.put("PERTUSIO","G477");
        this.put("PERUGIA","G478");
        this.put("PESARO","G479");
        this.put("PESCAGLIA","G480");
        this.put("PESCANTINA","G481");
        this.put("PESCARA","G482");
        this.put("PESCAROLO ED UNITI","G483");
        this.put("PESCASSEROLI","G484");
        this.put("PESCATE","G485");
        this.put("PESCHE","G486");
        this.put("PESCHICI","G487");
        this.put("PESCHIERA BORROMEO","G488");
        this.put("PESCHIERA DEL GARDA","G489");
        this.put("PESCIA","G491");
        this.put("PESCINA","G492");
        this.put("PESCO SANNITA","G494");
        this.put("PESCOCOSTANZO","G493");
        this.put("PESCOLANCIANO","G495");
        this.put("PESCOPAGANO","G496");
        this.put("PESCOPENNATARO","G497");
        this.put("PESCOROCCHIANO","G498");
        this.put("PESCOSANSONESCO","G499");
        this.put("PESCOSOLIDO","G500");
        this.put("PESSANO CON BORNAGO","G502");
        this.put("PESSINA CREMONESE","G504");
        this.put("PESSINETTO","G505");
        this.put("PETACCIATO","G506");
        this.put("PETILIA POLICASTRO","G508");
        this.put("PETINA","G509");
        this.put("PETRALIA SOPRANA","G510");
        this.put("PETRALIA SOTTANA","G511");
        this.put("PETRELLA SALTO","G513");
        this.put("PETRELLA TIFERNINA","G512");
        this.put("PETRIANO","G514");
        this.put("PETRIOLO","G515");
        this.put("PETRITOLI","G516");
        this.put("PETRIZZI","G517");
        this.put("PETRONA'","G518");
        this.put("PETROSINO","M281");
        this.put("PETRURO IRPINO","G519");
        this.put("PETTENASCO","G520");
        this.put("PETTINENGO","G521");
        this.put("PETTINEO","G522");
        this.put("PETTORANELLO DEL MOLISE","G523");
        this.put("PETTORANO SUL GIZIO","G524");
        this.put("PETTORAZZA GRIMANI","G525");
        this.put("PEVERAGNO","G526");
        this.put("PEZZANA","G528");
        this.put("PEZZAZE","G529");
        this.put("PEZZOLO VALLE UZZONE","G532");
        this.put("PIACENZA","G535");
        this.put("PIACENZA D'ADIGE","G534");
        this.put("PIADENA","G536");
        this.put("PIADENA DRIZZONA","M418");
        this.put("PIAGGE","G537");
        this.put("PIAGGINE","G538");
        this.put("PIAN CAMUNO","G546");
        this.put("PIAN DI SCO","G552");
        this.put("PIANA CRIXIA","G542");
        this.put("PIANA DEGLI ALBANESI","G543");
        this.put("PIANA DI MONTE VERNA","G541");
        this.put("PIANCASTAGNAIO","G547");
        this.put("PIANCOGNO","G549");
        this.put("PIANDIMELETO","G551");
        this.put("PIANE CRATI","G553");
        this.put("PIANELLA","G555");
        this.put("PIANELLO DEL LARIO","G556");
        this.put("PIANELLO VAL TIDONE","G557");
        this.put("PIANENGO","G558");
        this.put("PIANEZZA","G559");
        this.put("PIANEZZE","G560");
        this.put("PIANFEI","G561");
        this.put("PIANICO","G564");
        this.put("PIANIGA","G565");
        this.put("PIANO DI SORRENTO","G568");
        this.put("PIANOPOLI","D546");
        this.put("PIANORO","G570");
        this.put("PIANSANO","G571");
        this.put("PIANTEDO","G572");
        this.put("PIARIO","G574");
        this.put("PIASCO","G575");
        this.put("PIATEDA","G576");
        this.put("PIATTO","G577");
        this.put("PIAZZA AL SERCHIO","G582");
        this.put("PIAZZA ARMERINA","G580");
        this.put("PIAZZA BREMBANA","G579");
        this.put("PIAZZATORRE","G583");
        this.put("PIAZZOLA SUL BRENTA","G587");
        this.put("PIAZZOLO","G588");
        this.put("PICCIANO","G589");
        this.put("PICERNO","G590");
        this.put("PICINISCO","G591");
        this.put("PICO","G592");
        this.put("PIEA","G593");
        this.put("PIEDICAVALLO","G594");
        this.put("PIEDIMONTE ETNEO","G597");
        this.put("PIEDIMONTE MATESE","G596");
        this.put("PIEDIMONTE SAN GERMANO","G598");
        this.put("PIEDIMULERA","G600");
        this.put("PIEGARO","G601");
        this.put("PIENZA","G602");
        this.put("PIERANICA","G603");
        this.put("PIETRA DE' GIORGI","G612");
        this.put("PIETRA LIGURE","G605");
        this.put("PIETRA MARAZZI","G619");
        this.put("PIETRABBONDANTE","G606");
        this.put("PIETRABRUNA","G607");
        this.put("PIETRACAMELA","G608");
        this.put("PIETRACATELLA","G609");
        this.put("PIETRACUPA","G610");
        this.put("PIETRADEFUSI","G611");
        this.put("PIETRAFERRAZZANA","G613");
        this.put("PIETRAFITTA","G615");
        this.put("PIETRAGALLA","G616");
        this.put("PIETRALUNGA","G618");
        this.put("PIETRAMELARA","G620");
        this.put("PIETRAMONTECORVINO","G604");
        this.put("PIETRANICO","G621");
        this.put("PIETRAPAOLA","G622");
        this.put("PIETRAPERTOSA","G623");
        this.put("PIETRAPERZIA","G624");
        this.put("PIETRAPORZIO","G625");
        this.put("PIETRAROJA","G626");
        this.put("PIETRARUBBIA","G627");
        this.put("PIETRASANTA","G628");
        this.put("PIETRASTORNINA","G629");
        this.put("PIETRAVAIRANO","G630");
        this.put("PIETRELCINA","G631");
        this.put("PIEVE A NIEVOLE","G636");
        this.put("PIEVE ALBIGNOLA","G635");
        this.put("PIEVE D'ALPAGO","G638");
        this.put("PIEVE DEL CAIRO","G639");
        this.put("PIEVE DEL GRAPPA","M422");
        this.put("PIEVE DI BONO","G641");
        this.put("PIEVE DI BONO PREZZO","M365");
        this.put("PIEVE DI CADORE","G642");
        this.put("PIEVE DI CENTO","G643");
        this.put("PIEVE DI CORIANO","G633");
        this.put("PIEVE DI LEDRO","G644");
        this.put("PIEVE DI SOLIGO","G645");
        this.put("PIEVE DI TECO","G632");
        this.put("PIEVE D'OLMI","G647");
        this.put("PIEVE EMANUELE","G634");
        this.put("PIEVE FISSIRAGA","G096");
        this.put("PIEVE FOSCIANA","G648");
        this.put("PIEVE LIGURE","G646");
        this.put("PIEVE PORTO MORONE","G650");
        this.put("PIEVE SAN GIACOMO","G651");
        this.put("PIEVE SANTO STEFANO","G653");
        this.put("PIEVE TESINO","G656");
        this.put("PIEVE TORINA","G657");
        this.put("PIEVE VERGONTE","G658");
        this.put("PIEVEBOVIGLIANA","G637");
        this.put("PIEVEPELAGO","G649");
        this.put("PIGLIO","G659");
        this.put("PIGNA","G660");
        this.put("PIGNATARO INTERAMNA","G662");
        this.put("PIGNATARO MAGGIORE","G661");
        this.put("PIGNOLA","G663");
        this.put("PIGNONE","G664");
        this.put("PIGRA","G665");
        this.put("PILA","G666");
        this.put("PIMENTEL","G669");
        this.put("PIMONTE","G670");
        this.put("PINAROLO PO","G671");
        this.put("PINASCA","G672");
        this.put("PINCARA","G673");
        this.put("PINEROLO","G674");
        this.put("PINETO","F831");
        this.put("PINO D'ASTI","G676");
        this.put("PINO SULLA SPONDA DEL LAGO MAGGIORE","G677");
        this.put("PINO TORINESE","G678");
        this.put("PINZANO AL TAGLIAMENTO","G680");
        this.put("PINZOLO","G681");
        this.put("PIOBBICO","G682");
        this.put("PIOBESI D'ALBA","G683");
        this.put("PIOBESI TORINESE","G684");
        this.put("PIODE","G685");
        this.put("PIOLTELLO","G686");
        this.put("PIOMBINO","G687");
        this.put("PIOMBINO DESE","G688");
        this.put("PIORACO","G690");
        this.put("PIOSSASCO","G691");
        this.put("PIOVA' MASSAIA","G692");
        this.put("PIOVE DI SACCO","G693");
        this.put("PIOVENE ROCCHETTE","G694");
        this.put("PIOVERA","G695");
        this.put("PIOZZANO","G696");
        this.put("PIOZZO","G697");
        this.put("PIRAINO","G699");
        this.put("PISA","G702");
        this.put("PISANO","G703");
        this.put("PISCINA","G705");
        this.put("PISCINAS","M291");
        this.put("PISCIOTTA","G707");
        this.put("PISOGNE","G710");
        this.put("PISONIANO","G704");
        this.put("PISTICCI","G712");
        this.put("PISTOIA","G713");
        this.put("PITEGLIO","G715");
        this.put("PITIGLIANO","G716");
        this.put("PIUBEGA","G717");
        this.put("PIURO","G718");
        this.put("PIVERONE","G719");
        this.put("PIZZALE","G720");
        this.put("PIZZIGHETTONE","G721");
        this.put("PIZZO","G722");
        this.put("PIZZOFERRATO","G724");
        this.put("PIZZOLI","G726");
        this.put("PIZZONE","G727");
        this.put("PIZZONI","G728");
        this.put("PLACANICA","G729");
        this.put("PLATACI","G733");
        this.put("PLATANIA","G734");
        this.put("PLATI'","G735");
        this.put("PLAUS .PLAUS.","G299");
        this.put("PLESIO","G737");
        this.put("PLOAGHE","G740");
        this.put("PLODIO","G741");
        this.put("POCAPAGLIA","G742");
        this.put("POCENIA","G743");
        this.put("PODENZANA","G746");
        this.put("PODENZANO","G747");
        this.put("POFI","G749");
        this.put("POGGIARDO","G751");
        this.put("POGGIBONSI","G752");
        this.put("POGGIO A CAIANO","G754");
        this.put("POGGIO BERNI","G755");
        this.put("POGGIO BUSTONE","G756");
        this.put("POGGIO CATINO","G757");
        this.put("POGGIO IMPERIALE","G761");
        this.put("POGGIO MIRTETO","G763");
        this.put("POGGIO MOIANO","G764");
        this.put("POGGIO NATIVO","G765");
        this.put("POGGIO PICENZE","G766");
        this.put("POGGIO RENATICO","G768");
        this.put("POGGIO RUSCO","G753");
        this.put("POGGIO SAN LORENZO","G770");
        this.put("POGGIO SAN MARCELLO","G771");
        this.put("POGGIO SAN VICINO","D566");
        this.put("POGGIO SANNITA","B317");
        this.put("POGGIO TORRIANA","M324");
        this.put("POGGIODOMO","G758");
        this.put("POGGIOFIORITO","G760");
        this.put("POGGIOMARINO","G762");
        this.put("POGGIOREALE","G767");
        this.put("POGGIORSINI","G769");
        this.put("POGGIRIDENTI","G431");
        this.put("POGLIANO MILANESE","G772");
        this.put("POGNANA LARIO","G773");
        this.put("POGNANO","G774");
        this.put("POGNO","G775");
        this.put("POIRINO","G777");
        this.put("POJANA MAGGIORE","G776");
        this.put("POLAVENO","G779");
        this.put("POLCENIGO","G780");
        this.put("POLESELLA","G782");
        this.put("POLESINE PARMENSE","G783");
        this.put("POLESINE ZIBELLO","M367");
        this.put("POLI","G784");
        this.put("POLIA","G785");
        this.put("POLICORO","G786");
        this.put("POLIGNANO A MARE","G787");
        this.put("POLINAGO","G789");
        this.put("POLINO","G790");
        this.put("POLISTENA","G791");
        this.put("POLIZZI GENEROSA","G792");
        this.put("POLLA","G793");
        this.put("POLLEIN","G794");
        this.put("POLLENA TROCCHIA","G795");
        this.put("POLLENZA","F567");
        this.put("POLLICA","G796");
        this.put("POLLINA","G797");
        this.put("POLLONE","G798");
        this.put("POLLUTRI","G799");
        this.put("POLONGHERA","G800");
        this.put("POLPENAZZE DEL GARDA","G801");
        this.put("POLVERARA","G802");
        this.put("POLVERIGI","G803");
        this.put("POMARANCE","G804");
        this.put("POMARETTO","G805");
        this.put("POMARICO","G806");
        this.put("POMARO MONFERRATO","G807");
        this.put("POMAROLO","G808");
        this.put("POMBIA","G809");
        this.put("POMEZIA","G811");
        this.put("POMIGLIANO D'ARCO","G812");
        this.put("POMPEI","G813");
        this.put("POMPEIANA","G814");
        this.put("POMPIANO","G815");
        this.put("POMPONESCO","G816");
        this.put("POMPU","G817");
        this.put("PONCARALE","G818");
        this.put("PONDERANO","G820");
        this.put("PONNA","G821");
        this.put("PONSACCO","G822");
        this.put("PONSO","G823");
        this.put("PONT CANAVESE","G826");
        this.put("PONTASSIEVE","G825");
        this.put("PONTBOSET","G545");
        this.put("PONTE","G827");
        this.put("PONTE BUGGIANESE","G833");
        this.put("PONTE DELL'OLIO","G842");
        this.put("PONTE DI LEGNO","G844");
        this.put("PONTE DI PIAVE","G846");
        this.put("PONTE GARDENA .WAIDBRUCK.","G830");
        this.put("PONTE IN VALTELLINA","G829");
        this.put("PONTE LAMBRO","G847");
        this.put("PONTE NELLE ALPI","B662");
        this.put("PONTE NIZZA","G851");
        this.put("PONTE NOSSA","F941");
        this.put("PONTE SAN NICOLO'","G855");
        this.put("PONTE SAN PIETRO","G856");
        this.put("PONTEBBA","G831");
        this.put("PONTECAGNANO FAIANO","G834");
        this.put("PONTECCHIO POLESINE","G836");
        this.put("PONTECHIANALE","G837");
        this.put("PONTECORVO","G838");
        this.put("PONTECURONE","G839");
        this.put("PONTEDASSIO","G840");
        this.put("PONTEDERA","G843");
        this.put("PONTELANDOLFO","G848");
        this.put("PONTELATONE","G849");
        this.put("PONTELONGO","G850");
        this.put("PONTENURE","G852");
        this.put("PONTERANICA","G853");
        this.put("PONTESTURA","G858");
        this.put("PONTEVICO","G859");
        this.put("PONTEY","G860");
        this.put("PONTI","G861");
        this.put("PONTI SUL MINCIO","G862");
        this.put("PONTIDA","G864");
        this.put("PONTINIA","G865");
        this.put("PONTINVREA","G866");
        this.put("PONTIROLO NUOVO","G867");
        this.put("PONTOGLIO","G869");
        this.put("PONTREMOLI","G870");
        this.put("PONT SAINT MARTIN","G854");
        this.put("PONZA","G871");
        this.put("PONZANO DI FERMO","G873");
        this.put("PONZANO MONFERRATO","G872");
        this.put("PONZANO ROMANO","G874");
        this.put("PONZANO VENETO","G875");
        this.put("PONZONE","G877");
        this.put("POPOLI","G878");
        this.put("POPPI","G879");
        this.put("PORANO","G881");
        this.put("PORCARI","G882");
        this.put("PORCIA","G886");
        this.put("PORDENONE","G888");
        this.put("PORLEZZA","G889");
        this.put("PORNASSIO","G890");
        this.put("PORPETTO","G891");
        this.put("PORRETTA TERME","A558");
        this.put("PORTACOMARO","G894");
        this.put("PORTALBERA","G895");
        this.put("PORTE","G900");
        this.put("PORTE DI RENDENA","M358");
        this.put("PORTICI","G902");
        this.put("PORTICO DI CASERTA","G903");
        this.put("PORTICO E SAN BENEDETTO","G904");
        this.put("PORTIGLIOLA","G905");
        this.put("PORTO AZZURRO","E680");
        this.put("PORTO CERESIO","G906");
        this.put("PORTO CESAREO","M263");
        this.put("PORTO EMPEDOCLE","F299");
        this.put("PORTO MANTOVANO","G917");
        this.put("PORTO RECANATI","G919");
        this.put("PORTO SAN GIORGIO","G920");
        this.put("PORTO SANT'ELPIDIO","G921");
        this.put("PORTO TOLLE","G923");
        this.put("PORTO TORRES","G924");
        this.put("PORTO VALTRAVAGLIA","G907");
        this.put("PORTO VIRO","G926");
        this.put("PORTOBUFFOLE'","G909");
        this.put("PORTOCANNONE","G910");
        this.put("PORTOFERRAIO","G912");
        this.put("PORTOFINO","G913");
        this.put("PORTOGRUARO","G914");
        this.put("PORTOMAGGIORE","G916");
        this.put("PORTOPALO DI CAPO PASSERO","M257");
        this.put("PORTOSCUSO","G922");
        this.put("PORTOVENERE","G925");
        this.put("PORTULA","G927");
        this.put("POSADA","G929");
        this.put("POSINA","G931");
        this.put("POSITANO","G932");
        this.put("POSSAGNO","G933");
        this.put("POSTA","G934");
        this.put("POSTA FIBRENO","G935");
        this.put("POSTAL .BURGSTALL.","G936");
        this.put("POSTALESIO","G937");
        this.put("POSTIGLIONE","G939");
        this.put("POSTUA","G940");
        this.put("POTENZA","G942");
        this.put("POTENZA PICENA","F632");
        this.put("POVE DEL GRAPPA","G943");
        this.put("POVEGLIANO","G944");
        this.put("POVEGLIANO VERONESE","G945");
        this.put("POVIGLIO","G947");
        this.put("POVOLETTO","G949");
        this.put("POZZA DI FASSA","G950");
        this.put("POZZAGLIA SABINA","G951");
        this.put("POZZAGLIO ED UNITI","B914");
        this.put("POZZALLO","G953");
        this.put("POZZILLI","G954");
        this.put("POZZO D'ADDA","G955");
        this.put("POZZOL GROPPO","G960");
        this.put("POZZOLENGO","G959");
        this.put("POZZOLEONE","G957");
        this.put("POZZOLO FORMIGARO","G961");
        this.put("POZZOMAGGIORE","G962");
        this.put("POZZONOVO","G963");
        this.put("POZZUOLI","G964");
        this.put("POZZUOLO DEL FRIULI","G966");
        this.put("POZZUOLO MARTESANA","G965");
        this.put("PRADALUNGA","G968");
        this.put("PRADAMANO","G969");
        this.put("PRADLEVES","G970");
        this.put("PRAGELATO","G973");
        this.put("PRAIA A MARE","G975");
        this.put("PRAIANO","G976");
        this.put("PRALBOINO","G977");
        this.put("PRALI","G978");
        this.put("PRALORMO","G979");
        this.put("PRALUNGO","G980");
        this.put("PRAMAGGIORE","G981");
        this.put("PRAMOLLO","G982");
        this.put("PRAROLO","G985");
        this.put("PRAROSTINO","G986");
        this.put("PRASCO","G987");
        this.put("PRASCORSANO","G988");
        this.put("PRASO","G989");
        this.put("PRATA CAMPORTACCIO","G993");
        this.put("PRATA D'ANSIDONIA","G992");
        this.put("PRATA DI PORDENONE","G994");
        this.put("PRATA DI PRINCIPATO ULTRA","G990");
        this.put("PRATA SANNITA","G991");
        this.put("PRATELLA","G995");
        this.put("PRATIGLIONE","G997");
        this.put("PRATO","G999");
        this.put("PRATO ALLO STELVIO .PRAD AM STILFSERJOCH.","H004");
        this.put("PRATO CARNICO","H002");
        this.put("PRATO SESIA","H001");
        this.put("PRATOLA PELIGNA","H007");
        this.put("PRATOLA SERRA","H006");
        this.put("PRATOVECCHIO","H008");
        this.put("PRATOVECCHIO STIA","M329");
        this.put("PRAVISDOMINI","H010");
        this.put("PRAY","G974");
        this.put("PRAZZO","H011");
        this.put("PRECENICCO","H014");
        this.put("PRECI","H015");
        this.put("PREDAIA","M344");
        this.put("PREDAPPIO","H017");
        this.put("PREDAZZO","H018");
        this.put("PREDOI .PRETTAU.","H019");
        this.put("PREDORE","H020");
        this.put("PREDOSA","H021");
        this.put("PREGANZIOL","H022");
        this.put("PREGNANA MILANESE","H026");
        this.put("PRELA'","H027");
        this.put("PREMANA","H028");
        this.put("PREMARIACCO","H029");
        this.put("PREMENO","H030");
        this.put("PREMIA","H033");
        this.put("PREMILCUORE","H034");
        this.put("PREMOLO","H036");
        this.put("PREMOSELLO CHIOVENDA","H037");
        this.put("PREONE","H038");
        this.put("PREORE","H039");
        this.put("PREPOTTO","H040");
        this.put("PRE' SAINT DIDIER","H042");
        this.put("PRESEGLIE","H043");
        this.put("PRESENZANO","H045");
        this.put("PRESEZZO","H046");
        this.put("PRESICCE","H047");
        this.put("PRESICCE ACQUARICA","M428");
        this.put("PRESSANA","H048");
        this.put("PRESTINE","H050");
        this.put("PRETORO","H052");
        this.put("PREVALLE","H055");
        this.put("PREZZA","H056");
        this.put("PREZZO","H057");
        this.put("PRIERO","H059");
        this.put("PRIGNANO CILENTO","H062");
        this.put("PRIGNANO SULLA SECCHIA","H061");
        this.put("PRIMALUNA","H063");
        this.put("PRIMIERO SAN MARTINO DI CASTROZZA","M359");
        this.put("PRIOCCA","H068");
        this.put("PRIOLA","H069");
        this.put("PRIOLO GARGALLO","M279");
        this.put("PRIVERNO","G698");
        this.put("PRIZZI","H070");
        this.put("PROCENO","H071");
        this.put("PROCIDA","H072");
        this.put("PROPATA","H073");
        this.put("PROSERPIO","H074");
        this.put("PROSSEDI","H076");
        this.put("PROVAGLIO D'ISEO","H078");
        this.put("PROVAGLIO VAL SABBIA","H077");
        this.put("PROVES .PROVEIS.","H081");
        this.put("PROVVIDENTI","H083");
        this.put("PRUNETTO","H085");
        this.put("PUEGNAGO DEL GARDA","H086");
        this.put("PUGLIANELLO","H087");
        this.put("PULA","H088");
        this.put("PULFERO","H089");
        this.put("PULSANO","H090");
        this.put("PUMENENGO","H091");
        this.put("PUOS D'ALPAGO","H092");
        this.put("PUSIANO","H094");
        this.put("PUTIFIGARI","H095");
        this.put("PUTIGNANO","H096");
        this.put("QUADRELLE","H097");
        this.put("QUADRI","H098");
        this.put("QUAGLIUZZO","H100");
        this.put("QUALIANO","H101");
        this.put("QUARANTI","H102");
        this.put("QUAREGNA","H103");
        this.put("QUAREGNA CERRETO","M414");
        this.put("QUARGNENTO","H104");
        this.put("QUARNA SOPRA","H106");
        this.put("QUARNA SOTTO","H107");
        this.put("QUARONA","H108");
        this.put("QUARRATA","H109");
        this.put("QUART","H110");
        this.put("QUARTO","H114");
        this.put("QUARTO D'ALTINO","H117");
        this.put("QUARTU SANT'ELENA","H118");
        this.put("QUARTUCCIU","H119");
        this.put("QUASSOLO","H120");
        this.put("QUATTORDIO","H121");
        this.put("QUATTRO CASTELLA","H122");
        this.put("QUERO","H124");
        this.put("QUERO VAS","M332");
        this.put("QUILIANO","H126");
        this.put("QUINCINETTO","H127");
        this.put("QUINDICI","H128");
        this.put("QUINGENTOLE","H129");
        this.put("QUINTANO","H130");
        this.put("QUINTO DI TREVISO","H131");
        this.put("QUINTO VERCELLESE","H132");
        this.put("QUINTO VICENTINO","H134");
        this.put("QUINZANO D'OGLIO","H140");
        this.put("QUISTELLO","H143");
        this.put("QUITTENGO","H145");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
