package libreria_sibilia.codicefiscale.document ;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_B extends HashMap<String, String> {

    public CitiesCodes_B(){
        this.put("BACENO","A534");
        this.put("BACOLI","A535");
        this.put("BADALUCCO","A536");
        this.put("BADESI","M214");
        this.put("BADIA .ABTEI.","A537");
        this.put("BADIA CALAVENA","A540");
        this.put("BADIA PAVESE","A538");
        this.put("BADIA POLESINE","A539");
        this.put("BADIA TEDALDA","A541");
        this.put("BADOLATO","A542");
        this.put("BAGALADI","A544");
        this.put("BAGHERIA","A546");
        this.put("BAGNACAVALLO","A547");
        this.put("BAGNARA CALABRA","A552");
        this.put("BAGNARA DI ROMAGNA","A551");
        this.put("BAGNARIA","A550");
        this.put("BAGNARIA ARSA","A553");
        this.put("BAGNASCO","A555");
        this.put("BAGNATICA","A557");
        this.put("BAGNI DI LUCCA","A560");
        this.put("BAGNO A RIPOLI","A564");
        this.put("BAGNO DI ROMAGNA","A565");
        this.put("BAGNOLI DEL TRIGNO","A567");
        this.put("BAGNOLI DI SOPRA","A568");
        this.put("BAGNOLI IRPINO","A566");
        this.put("BAGNOLO CREMASCO","A570");
        this.put("BAGNOLO DEL SALENTO","A572");
        this.put("BAGNOLO DI PO","A574");
        this.put("BAGNOLO IN PIANO","A573");
        this.put("BAGNOLO MELLA","A569");
        this.put("BAGNOLO PIEMONTE","A571");
        this.put("BAGNOLO SAN VITO","A575");
        this.put("BAGNONE","A576");
        this.put("BAGNOREGIO","A577");
        this.put("BAGOLINO","A578");
        this.put("BAIA E LATINA","A579");
        this.put("BAIANO","A580");
        this.put("BAIARDO","A581");
        this.put("BAIRO","A584");
        this.put("BAISO","A586");
        this.put("BALANGERO","A587");
        this.put("BALDICHIERI D'ASTI","A588");
        this.put("BALDISSERO CANAVESE","A590");
        this.put("BALDISSERO D'ALBA","A589");
        this.put("BALDISSERO TORINESE","A591");
        this.put("BALESTRATE","A592");
        this.put("BALESTRINO","A593");
        this.put("BALLABIO","A594");
        this.put("BALLAO","A597");
        this.put("BALME","A599");
        this.put("BALMUCCIA","A600");
        this.put("BALOCCO","A601");
        this.put("BALSORANO","A603");
        this.put("BALVANO","A604");
        this.put("BALZOLA","A605");
        this.put("BANARI","A606");
        this.put("BANCHETTE","A607");
        this.put("BANNIO ANZINO","A610");
        this.put("BANZI","A612");
        this.put("BAONE","A613");
        this.put("BARADILI","A614");
        this.put("BARAGIANO","A615");
        this.put("BARANELLO","A616");
        this.put("BARANO D'ISCHIA","A617");
        this.put("BARANZATE","A618");
        this.put("BARASSO","A619");
        this.put("BARATILI SAN PIETRO","A621");
        this.put("BARBANIA","A625");
        this.put("BARBARA","A626");
        this.put("BARBARANO MOSSANO","M401");
        this.put("BARBARANO ROMANO","A628");
        this.put("BARBARANO VICENTINO","A627");
        this.put("BARBARESCO","A629");
        this.put("BARBARIGA","A630");
        this.put("BARBATA","A631");
        this.put("BARBERINO DI MUGELLO","A632");
        this.put("BARBERINO TAVARNELLE","M408");
        this.put("BARBERINO VAL D'ELSA","A633");
        this.put("BARBIANELLO","A634");
        this.put("BARBIANO .BARBIAN.","A635");
        this.put("BARBONA","A637");
        this.put("BARCELLONA POZZO DI GOTTO","A638");
        this.put("BARCHI","A639");
        this.put("BARCIS","A640");
        this.put("BARD","A643");
        this.put("BARDELLO","A645");
        this.put("BARDELLO CON MALGESSO E BREGANO","M433");
        this.put("BARDI","A646");
        this.put("BARDINETO","A647");
        this.put("BARDOLINO","A650");
        this.put("BARDONECCHIA","A651");
        this.put("BAREGGIO","A652");
        this.put("BARENGO","A653");
        this.put("BARESSA","A655");
        this.put("BARETE","A656");
        this.put("BARGA","A657");
        this.put("BARGAGLI","A658");
        this.put("BARGE","A660");
        this.put("BARGHE","A661");
        this.put("BARI","A662");
        this.put("BARI SARDO","A663");
        this.put("BARIANO","A664");
        this.put("BARICELLA","A665");
        this.put("BARILE","A666");
        this.put("BARISCIANO","A667");
        this.put("BARLASSINA","A668");
        this.put("BARLETTA","A669");
        this.put("BARNI","A670");
        this.put("BAROLO","A671");
        this.put("BARONE CANAVESE","A673");
        this.put("BARONISSI","A674");
        this.put("BARRAFRANCA","A676");
        this.put("BARRALI","A677");
        this.put("BARREA","A678");
        this.put("BARUMINI","A681");
        this.put("BARZAGO","A683");
        this.put("BARZANA","A684");
        this.put("BARZANO'","A686");
        this.put("BARZIO","A687");
        this.put("BASALUZZO","A689");
        this.put("BASCAPE'","A690");
        this.put("BASCHI","A691");
        this.put("BASCIANO","A692");
        this.put("BASELGA DI PINE'","A694");
        this.put("BASELICE","A696");
        this.put("BASIANO","A697");
        this.put("BASICO'","A698");
        this.put("BASIGLIO","A699");
        this.put("BASILIANO","A700");
        this.put("BASSANO BRESCIANO","A702");
        this.put("BASSANO DEL GRAPPA","A703");
        this.put("BASSANO IN TEVERINA","A706");
        this.put("BASSANO ROMANO","A704");
        this.put("BASSIANO","A707");
        this.put("BASSIGNANA","A708");
        this.put("BASTIA MONDOVI'","A709");
        this.put("BASTIA UMBRA","A710");
        this.put("BASTIDA DE' DOSSI","A711");
        this.put("BASTIDA PANCARANA","A712");
        this.put("BASTIGLIA","A713");
        this.put("BATTAGLIA TERME","A714");
        this.put("BATTIFOLLO","A716");
        this.put("BATTIPAGLIA","A717");
        this.put("BATTUDA","A718");
        this.put("BAUCINA","A719");
        this.put("BAULADU","A721");
        this.put("BAUNEI","A722");
        this.put("BAVENO","A725");
        this.put("BAZZANO","A726");
        this.put("BEDERO VALCUVIA","A728");
        this.put("BEDIZZOLE","A729");
        this.put("BEDOLLO","A730");
        this.put("BEDONIA","A731");
        this.put("BEDULITA","A732");
        this.put("BEE","A733");
        this.put("BEINASCO","A734");
        this.put("BEINETTE","A735");
        this.put("BELCASTRO","A736");
        this.put("BELFIORE","A737");
        this.put("BELFORTE ALL'ISAURO","A740");
        this.put("BELFORTE DEL CHIENTI","A739");
        this.put("BELFORTE MONFERRATO","A738");
        this.put("BELGIOIOSO","A741");
        this.put("BELGIRATE","A742");
        this.put("BELLA","A743");
        this.put("BELLAGIO","A744");
        this.put("BELLAGIO","M335");
        this.put("BELLANO","A745");
        this.put("BELLANTE","A746");
        this.put("BELLARIA IGEA MARINA","A747");
        this.put("BELLEGRA","A749");
        this.put("BELLINO","A750");
        this.put("BELLINZAGO LOMBARDO","A751");
        this.put("BELLINZAGO NOVARESE","A752");
        this.put("BELLIZZI","M294");
        this.put("BELLONA","A755");
        this.put("BELLOSGUARDO","A756");
        this.put("BELLUNO","A757");
        this.put("BELLUSCO","A759");
        this.put("BELMONTE CALABRO","A762");
        this.put("BELMONTE CASTELLO","A763");
        this.put("BELMONTE DEL SANNIO","A761");
        this.put("BELMONTE IN SABINA","A765");
        this.put("BELMONTE MEZZAGNO","A764");
        this.put("BELMONTE PICENO","A760");
        this.put("BELPASSO","A766");
        this.put("BELSITO","A768");
        this.put("BELVEDERE DI SPINELLO","A772");
        this.put("BELVEDERE LANGHE","A774");
        this.put("BELVEDERE MARITTIMO","A773");
        this.put("BELVEDERE OSTRENSE","A769");
        this.put("BELVEGLIO","A770");
        this.put("BELVI'","A776");
        this.put("BEMA","A777");
        this.put("BENE LARIO","A778");
        this.put("BENE VAGIENNA","A779");
        this.put("BENESTARE","A780");
        this.put("BENETUTTI","A781");
        this.put("BENEVELLO","A782");
        this.put("BENEVENTO","A783");
        this.put("BENNA","A784");
        this.put("BENTIVOGLIO","A785");
        this.put("BERBENNO","A786");
        this.put("BERBENNO DI VALTELLINA","A787");
        this.put("BERCETO","A788");
        this.put("BERCHIDDA","A789");
        this.put("BEREGAZZO CON FIGLIARO","A791");
        this.put("BEREGUARDO","A792");
        this.put("BERGAMASCO","A793");
        this.put("BERGAMO","A794");
        this.put("BERGANTINO","A795");
        this.put("BERGEGGI","A796");
        this.put("BERGOLO","A798");
        this.put("BERLINGO","A799");
        this.put("BERNALDA","A801");
        this.put("BERNAREGGIO","A802");
        this.put("BERNATE TICINO","A804");
        this.put("BERNEZZO","A805");
        this.put("BERRA","A806");
        this.put("BERSONE","A808");
        this.put("BERTINORO","A809");
        this.put("BERTIOLO","A810");
        this.put("BERTONICO","A811");
        this.put("BERZANO DI SAN PIETRO","A812");
        this.put("BERZANO DI TORTONA","A813");
        this.put("BERZO DEMO","A816");
        this.put("BERZO INFERIORE","A817");
        this.put("BERZO SAN FERMO","A815");
        this.put("BESANA IN BRIANZA","A818");
        this.put("BESANO","A819");
        this.put("BESATE","A820");
        this.put("BESENELLO","A821");
        this.put("BESENZONE","A823");
        this.put("BESNATE","A825");
        this.put("BESOZZO","A826");
        this.put("BESSUDE","A827");
        this.put("BETTOLA","A831");
        this.put("BETTONA","A832");
        this.put("BEURA CARDEZZA","A834");
        this.put("BEVAGNA","A835");
        this.put("BEVERINO","A836");
        this.put("BEVILACQUA","A837");
        this.put("BEZZECCA","A839");
        this.put("BIANCAVILLA","A841");
        this.put("BIANCHI","A842");
        this.put("BIANCO","A843");
        this.put("BIANDRATE","A844");
        this.put("BIANDRONNO","A845");
        this.put("BIANZANO","A846");
        this.put("BIANZE'","A847");
        this.put("BIANZONE","A848");
        this.put("BIASSONO","A849");
        this.put("BIBBIANO","A850");
        this.put("BIBBIENA","A851");
        this.put("BIBBONA","A852");
        this.put("BIBIANA","A853");
        this.put("BICCARI","A854");
        this.put("BICINICCO","A855");
        this.put("BIDONI'","A856");
        this.put("BIELLA","A859");
        this.put("BIENNO","A861");
        this.put("BIENO","A863");
        this.put("BIENTINA","A864");
        this.put("BIGARELLO","A866");
        this.put("BINAGO","A870");
        this.put("BINASCO","A872");
        this.put("BINETTO","A874");
        this.put("BIOGLIO","A876");
        this.put("BIONAZ","A877");
        this.put("BIONE","A878");
        this.put("BIRORI","A880");
        this.put("BISACCIA","A881");
        this.put("BISACQUINO","A882");
        this.put("BISCEGLIE","A883");
        this.put("BISEGNA","A884");
        this.put("BISENTI","A885");
        this.put("BISIGNANO","A887");
        this.put("BISTAGNO","A889");
        this.put("BISUSCHIO","A891");
        this.put("BITETTO","A892");
        this.put("BITONTO","A893");
        this.put("BITRITTO","A894");
        this.put("BITTI","A895");
        this.put("BIVONA","A896");
        this.put("BIVONGI","A897");
        this.put("BIZZARONE","A898");
        this.put("BLEGGIO INFERIORE","A901");
        this.put("BLEGGIO SUPERIORE","A902");
        this.put("BLELLO","A903");
        this.put("BLERA","A857");
        this.put("BLESSAGNO","A904");
        this.put("BLEVIO","A905");
        this.put("BLUFI","M268");
        this.put("BOARA PISANI","A906");
        this.put("BOBBIO","A909");
        this.put("BOBBIO PELLICE","A910");
        this.put("BOCA","A911");
        this.put("BOCCHIGLIERO","A912");
        this.put("BOCCIOLETO","A914");
        this.put("BOCENAGO","A916");
        this.put("BODIO LOMNAGO","A918");
        this.put("BOFFALORA D'ADDA","A919");
        this.put("BOFFALORA SOPRA TICINO","A920");
        this.put("BOGLIASCO","A922");
        this.put("BOGNANCO","A925");
        this.put("BOGOGNO","A929");
        this.put("BOISSANO","A931");
        this.put("BOJANO","A930");
        this.put("BOLANO","A932");
        this.put("BOLBENO","A933");
        this.put("BOLGARE","A937");
        this.put("BOLLATE","A940");
        this.put("BOLLENGO","A941");
        this.put("BOLOGNA","A944");
        this.put("BOLOGNANO","A945");
        this.put("BOLOGNETTA","A946");
        this.put("BOLOGNOLA","A947");
        this.put("BOLOTANA","A948");
        this.put("BOLSENA","A949");
        this.put("BOLTIERE","A950");
        this.put("BOLZANO .BOZEN.","A952");
        this.put("BOLZANO NOVARESE","A953");
        this.put("BOLZANO VICENTINO","A954");
        this.put("BOMARZO","A955");
        this.put("BOMBA","A956");
        this.put("BOMPENSIERE","A957");
        this.put("BOMPIETRO","A958");
        this.put("BOMPORTO","A959");
        this.put("BONARCADO","A960");
        this.put("BONASSOLA","A961");
        this.put("BONATE SOPRA","A963");
        this.put("BONATE SOTTO","A962");
        this.put("BONAVIGO","A964");
        this.put("BONDENO","A965");
        this.put("BONDO","A967");
        this.put("BONDONE","A968");
        this.put("BONEA","A970");
        this.put("BONEFRO","A971");
        this.put("BONEMERSE","A972");
        this.put("BONIFATI","A973");
        this.put("BONITO","A975");
        this.put("BONNANARO","A976");
        this.put("BONO","A977");
        this.put("BONORVA","A978");
        this.put("BONVICINO","A979");
        this.put("BORBONA","A981");
        this.put("BORCA DI CADORE","A982");
        this.put("BORDANO","A983");
        this.put("BORDIGHERA","A984");
        this.put("BORDOLANO","A986");
        this.put("BORE","A987");
        this.put("BORETTO","A988");
        this.put("BORGARELLO","A989");
        this.put("BORGARO TORINESE","A990");
        this.put("BORGETTO","A991");
        this.put("BORGHETTO D'ARROSCIA","A993");
        this.put("BORGHETTO DI BORBERA","A998");
        this.put("BORGHETTO DI VARA","A992");
        this.put("BORGHETTO LODIGIANO","A995");
        this.put("BORGHETTO SANTO SPIRITO","A999");
        this.put("BORGHI","B001");
        this.put("BORGIA","B002");
        this.put("BORGIALLO","B003");
        this.put("BORGIO VEREZZI","B005");
        this.put("BORGO A MOZZANO","B007");
        this.put("BORGO CHIESE","M352");
        this.put("BORGO D'ALE","B009");
        this.put("BORGO D'ANAUNIA","M429");
        this.put("BORGO DI TERZO","B010");
        this.put("BORGO LARES","M353");
        this.put("BORGO MANTOVANO","M396");
        this.put("BORGO PACE","B026");
        this.put("BORGO PRIOLO","B028");
        this.put("BORGO SAN DALMAZZO","B033");
        this.put("BORGO SAN GIACOMO","B035");
        this.put("BORGO SAN GIOVANNI","B017");
        this.put("BORGO SAN LORENZO","B036");
        this.put("BORGO SAN MARTINO","B037");
        this.put("BORGO SAN SIRO","B038");
        this.put("BORGO TICINO","B043");
        this.put("BORGO TOSSIGNANO","B044");
        this.put("BORGO VAL DI TARO","B042");
        this.put("BORGO VALBELLUNA","M421");
        this.put("BORGO VALSUGANA","B006");
        this.put("BORGO VELINO","A996");
        this.put("BORGO VENETO","M402");
        this.put("BORGO VERCELLI","B046");
        this.put("BORGO VIRGILIO","M340");
        this.put("BORGOCARBONARA","M406");
        this.put("BORGOFORTE","B011");
        this.put("BORGOFRANCO D'IVREA","B015");
        this.put("BORGOFRANCO SUL PO","B013");
        this.put("BORGOLAVEZZARO","B016");
        this.put("BORGOMALE","B018");
        this.put("BORGOMANERO","B019");
        this.put("BORGOMARO","B020");
        this.put("BORGOMASINO","B021");
        this.put("BORGOMEZZAVALLE","M370");
        this.put("BORGONE SUSA","B024");
        this.put("BORGONOVO VAL TIDONE","B025");
        this.put("BORGORATTO ALESSANDRINO","B029");
        this.put("BORGORATTO MORMOROLO","B030");
        this.put("BORGORICCO","B031");
        this.put("BORGOROSE","B008");
        this.put("BORGOSATOLLO","B040");
        this.put("BORGOSESIA","B041");
        this.put("BORMIDA","B048");
        this.put("BORMIO","B049");
        this.put("BORNASCO","B051");
        this.put("BORNO","B054");
        this.put("BORONEDDU","B055");
        this.put("BORORE","B056");
        this.put("BORRELLO","B057");
        this.put("BORRIANA","B058");
        this.put("BORSO DEL GRAPPA","B061");
        this.put("BORTIGALI","B062");
        this.put("BORTIGIADAS","B063");
        this.put("BORUTTA","B064");
        this.put("BORZONASCA","B067");
        this.put("BOSA","B068");
        this.put("BOSARO","B069");
        this.put("BOSCHI SANT'ANNA","B070");
        this.put("BOSCO CHIESANUOVA","B073");
        this.put("BOSCO MARENGO","B071");
        this.put("BOSCONERO","B075");
        this.put("BOSCOREALE","B076");
        this.put("BOSCOTRECASE","B077");
        this.put("BOSENTINO","B078");
        this.put("BOSIA","B079");
        this.put("BOSIO","B080");
        this.put("BOSISIO PARINI","B081");
        this.put("BOSNASCO","B082");
        this.put("BOSSICO","B083");
        this.put("BOSSOLASCO","B084");
        this.put("BOTRICELLO","B085");
        this.put("BOTRUGNO","B086");
        this.put("BOTTANUCO","B088");
        this.put("BOTTICINO","B091");
        this.put("BOTTIDDA","B094");
        this.put("BOVA","B097");
        this.put("BOVA MARINA","B099");
        this.put("BOVALINO","B098");
        this.put("BOVEGNO","B100");
        this.put("BOVES","B101");
        this.put("BOVEZZO","B102");
        this.put("BOVILLE ERNICA","A720");
        this.put("BOVINO","B104");
        this.put("BOVISIO MASCIAGO","B105");
        this.put("BOVOLENTA","B106");
        this.put("BOVOLONE","B107");
        this.put("BOZZOLE","B109");
        this.put("BOZZOLO","B110");
        this.put("BRA","B111");
        this.put("BRACCA","B112");
        this.put("BRACCIANO","B114");
        this.put("BRACIGLIANO","B115");
        this.put("BRAIES .PRAGS.","B116");
        this.put("BRALLO DI PREGOLA","B117");
        this.put("BRANCALEONE","B118");
        this.put("BRANDICO","B120");
        this.put("BRANDIZZO","B121");
        this.put("BRANZI","B123");
        this.put("BRAONE","B124");
        this.put("BREBBIA","B126");
        this.put("BREDA DI PIAVE","B128");
        this.put("BREGANO","B131");
        this.put("BREGANZE","B132");
        this.put("BREGNANO","B134");
        this.put("BREGUZZO","B135");
        this.put("BREIA","B136");
        this.put("BREMBATE","B137");
        this.put("BREMBATE DI SOPRA","B138");
        this.put("BREMBILLA","B140");
        this.put("BREMBIO","B141");
        this.put("BREME","B142");
        this.put("BRENDOLA","B143");
        this.put("BRENNA","B144");
        this.put("BRENNERO .BRENNER.","B145");
        this.put("BRENO","B149");
        this.put("BRENTA","B150");
        this.put("BRENTINO BELLUNO","B152");
        this.put("BRENTONICO","B153");
        this.put("BRENZONE SUL GARDA","B154");
        this.put("BRESCELLO","B156");
        this.put("BRESCIA","B157");
        this.put("BRESIMO","B158");
        this.put("BRESSANA BOTTARONE","B159");
        this.put("BRESSANONE .BRIXEN.","B160");
        this.put("BRESSANVIDO","B161");
        this.put("BRESSO","B162");
        this.put("BREZ","B165");
        this.put("BREZZO DI BEDERO","B166");
        this.put("BRIAGLIA","B167");
        this.put("BRIATICO","B169");
        this.put("BRICHERASIO","B171");
        this.put("BRIENNO","B172");
        this.put("BRIENZA","B173");
        this.put("BRIGA ALTA","B175");
        this.put("BRIGA NOVARESE","B176");
        this.put("BRIGNANO GERA D'ADDA","B178");
        this.put("BRIGNANO FRASCATA","B179");
        this.put("BRINDISI","B180");
        this.put("BRINDISI MONTAGNA","B181");
        this.put("BRINZIO","B182");
        this.put("BRIONA","B183");
        this.put("BRIONE","B184");
        this.put("BRIONE","B185");
        this.put("BRIOSCO","B187");
        this.put("BRISIGHELLA","B188");
        this.put("BRISSAGO VALTRAVAGLIA","B191");
        this.put("BRISSOGNE","B192");
        this.put("BRITTOLI","B193");
        this.put("BRIVIO","B194");
        this.put("BROCCOSTELLA","B195");
        this.put("BROGLIANO","B196");
        this.put("BROGNATURO","B197");
        this.put("BROLO","B198");
        this.put("BRONDELLO","B200");
        this.put("BRONI","B201");
        this.put("BRONTE","B202");
        this.put("BRONZOLO .BRANZOLL.","B203");
        this.put("BROSSASCO","B204");
        this.put("BROSSO","B205");
        this.put("BROVELLO CARPUGNINO","B207");
        this.put("BROZOLO","B209");
        this.put("BRUGHERIO","B212");
        this.put("BRUGINE","B213");
        this.put("BRUGNATO","B214");
        this.put("BRUGNERA","B215");
        this.put("BRUINO","B216");
        this.put("BRUMANO","B217");
        this.put("BRUNATE","B218");
        this.put("BRUNELLO","B219");
        this.put("BRUNICO .BRUNECK.","B220");
        this.put("BRUNO","B221");
        this.put("BRUSAPORTO","B223");
        this.put("BRUSASCO","B225");
        this.put("BRUSCIANO","B227");
        this.put("BRUSIMPIANO","B228");
        this.put("BRUSNENGO","B229");
        this.put("BRUSSON","B230");
        this.put("BRUZOLO","B232");
        this.put("BRUZZANO ZEFFIRIO","B234");
        this.put("BUBBIANO","B235");
        this.put("BUBBIO","B236");
        this.put("BUCCHERI","B237");
        this.put("BUCCHIANICO","B238");
        this.put("BUCCIANO","B239");
        this.put("BUCCINASCO","B240");
        this.put("BUCCINO","B242");
        this.put("BUCINE","B243");
        this.put("BUDDUSO'","B246");
        this.put("BUDOIA","B247");
        this.put("BUDONI","B248");
        this.put("BUDRIO","B249");
        this.put("BUGGERRU","B250");
        this.put("BUGGIANO","B251");
        this.put("BUGLIO IN MONTE","B255");
        this.put("BUGNARA","B256");
        this.put("BUGUGGIATE","B258");
        this.put("BUJA","B259");
        this.put("BULCIAGO","B261");
        this.put("BULGAROGRASSO","B262");
        this.put("BULTEI","B264");
        this.put("BULZI","B265");
        this.put("BUONABITACOLO","B266");
        this.put("BUONALBERGO","B267");
        this.put("BUONCONVENTO","B269");
        this.put("BUONVICINO","B270");
        this.put("BURAGO DI MOLGORA","B272");
        this.put("BURCEI","B274");
        this.put("BURGIO","B275");
        this.put("BURGOS","B276");
        this.put("BURIASCO","B278");
        this.put("BUROLO","B279");
        this.put("BURONZO","B280");
        this.put("BUSACHI","B281");
        this.put("BUSALLA","B282");
        this.put("BUSANA","B283");
        this.put("BUSANO","B284");
        this.put("BUSCA","B285");
        this.put("BUSCATE","B286");
        this.put("BUSCEMI","B287");
        this.put("BUSETO PALIZZOLO","B288");
        this.put("BUSNAGO","B289");
        this.put("BUSSERO","B292");
        this.put("BUSSETO","B293");
        this.put("BUSSI SUL TIRINO","B294");
        this.put("BUSSO","B295");
        this.put("BUSSOLENGO","B296");
        this.put("BUSSOLENO","B297");
        this.put("BUSTO ARSIZIO","B300");
        this.put("BUSTO GAROLFO","B301");
        this.put("BUTERA","B302");
        this.put("BUTI","B303");
        this.put("BUTTAPIETRA","B304");
        this.put("BUTTIGLIERA ALTA","B305");
        this.put("BUTTIGLIERA D'ASTI","B306");
        this.put("BUTTRIO","B309");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
